clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/LowerToLLVM.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CIRToLLVM/unary-inc-dec.cir, clang/test/CIR/CodeGen/inc-dec.cpp, clang/test/CIR/IR/invalid.cir
Relates to #7, starting the unary operations with increment and decrement.  Note we lower the load/store explicitly, so the operations themselves are just the "math" part.
=> Basic Increment and Decrement support

clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/lib/CIR/CodeGen/CIRGenValue.h, clang/test/CIR/CodeGen/lambda.cpp
Implement another early return so the empty lambda also bail for this optimization -- in particular not performing it for small types.
Fixes llvm/clangir#6.
=> [CIR] Implement more of CheckAggExprForMemSetUse()

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/LowerToLLVM.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CIRToLLVM/unary-plus-minus.cir, clang/test/CIR/CodeGen/unary.cpp
=> [CIR][CodeGen] Basic support for unary plus and minus

clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/IR/struct.cir
The parsing function wasn't considering the commas separating the types
inside the angle brackets, that are used by printing.
Related to llvm/clangir#9.
=> [CIR] Fix parsing of CIR dialect's struct type

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/String.cpp, clang/test/CIR/CodeGen/assign-operator.cpp, clang/test/CIR/CodeGen/ctor-alias.cpp, clang/test/CIR/CodeGen/ctor-member-lvalue-to-rvalue.cpp, clang/test/CIR/CodeGen/ctor.cpp, clang/test/CIR/CodeGen/lambda.cpp, clang/test/CIR/CodeGen/lvalue-refs.cpp, clang/test/CIR/CodeGen/struct.c, clang/test/CIR/CodeGen/struct.cpp
For those types, the mangled name started with a number which is not a valid start character for alias types in MLIR.  Prefix these aliases with "ty_".
Relates to llvm/clangir#9.
=> [CIR] Fix invalid alias name for dialect's struct types

clang/lib/CIR/CodeGen/CIRGenRecordLayout.h
`CIRGenTypes.h` This file seems to include `CIRGenRecordLayout.h`, these two files have circular dependencies.
=> [CIR][CIRGen][NFC] Fix circular include dependency

clang/lib/CIR/CodeGen/CIRGenExprCst.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp
Just replace llvm::makeArrayRef with llvm::ArrayRef and silence these warnings on build.
=> [NFC] deprecated on makeArrayRef.

clang/lib/CIR/CodeGen/CIRGenExprCst.cpp, clang/lib/CIR/CodeGen/CIRGenTypes.cpp
Summary: The following compilation command is broken:
```
ninja clang
```
It will produce the following output
```
.../clangir/clang/lib/CIR/CodeGen/CIRGenTypes.cpp: In member function ‘std::__cxx11::string cir::CIRGenTypes::getRecordTypeName(const clang::RecordDecl*, llvm::StringRef)’:
.../clangir/clang/lib/CIR/CodeGen/CIRGenTypes.cpp:56:35: error: ‘clang::DeclaratorDecl’ is not a base of ‘const clang::RecordDecl’
recordDecl->DeclaratorDecl::printName(outStream);
```
Test Plan:
```
ninja clang
```
=> [clang] Fix for broken clang build

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/CodeGen/unary.cpp, clang/test/CIR/Lowering/unary-not.cir
Add Unary Not operation on CIRGen and Lowerings.
--------
Most follow the work like https://github.com/llvm/clangir/pull/20
Currently not add LNot operation, since it requires  the type to be cir.bool.
=> [CIR][CodeGen][Lower] CIR Unary Not Operation.

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/binop-unsigned-int.cir, clang/test/CIR/Lowering/binop-unsigned-int.cir
Fix lower cir to mlir with signed, signless integer type on
DIV, REM, SHR operations. But now on .c -> .cir -> .llvm, it will
generate unsigned operation at end, no matter the given type 'int'
or 'unsigned'. Need more fix.
---------------------
I just change the code https://github.com/llvm/clangir/blob/90e6ee2819b1a7515ff3cad78de43dbb98f8053a/clang/test/CIR/CodeGen/binop.cpp#L4-L5
with `int` to `unsigned`, run with clang -emit-cir , then cir-tool -cir-to-mlir.
They both get mlir operation with unsigned. I guess it may need some process on CIRGen to fix it next.
=> [CIR][LowerToMLIR] Fix lowering signless integer type on DIV, REM, SHR ops

clang/tools/cir-tool/cir-tool.cpp
* (to be filled)
When lowering from CIR to the LLVM dialect, DLTI module attributes
generated errors due to them being from an unregistered dialect.
This commit fixes these errors.
=> [CIR][Bugfix] Register missing DLTI dialect in cir-tool's registry

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/lib/Frontend/CompilerInvocation.cpp, clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp, clang/test/CIR/CodeGen/cast.cpp, clang/test/CIR/CodeGen/globals.cpp, clang/test/CIR/CodeGen/literals.c, clang/test/CIR/CodeGen/literals.cpp, clang/test/CIR/Executables/hello.c, clang/test/CIR/Lowering/call.cir, clang/test/CIR/Lowering/cast.cir, clang/test/CIR/Lowering/globals.cir, clang/tools/cir-tool/cir-tool.cpp
Add a series of functionalities and bug fixes to easily compile a simple "Hello world!" C program.
Most programs will require some standard library to compile. Printf is specially used for correctness. This is meant to be a first step to testing Clang IR against some benchmarks and other "real-world" programs.
Additions:
- Add code gen visitor for character literals.
- Implement pointer decay casts to convert char arrays to char pointers.
- Implement direct lowering conversion patterns for both `cir.get_global` and `cir.global` operations.
- Test compiling a `hello.c` program using `clang -fclangir-enable -fclangir-direct-lowering`.
Bug fixes:
- Use converted LLVM types when generating `llvm.call` operations instead of CIR types.
- Fix `-fclangir-direct-lowering` flag being ignored …
=> Compile a "Hello, world!" C program

clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
* #66
* #65
* #64
* __->__ #63
The buildArrayConstant method is only used when generating code for some
constant expression in the AST. To ensure encapsulation, this patch
moves the method to the CIRGenExprConst anonymous namespace, ensuring
any (and only) expression constant visitors have access to it.
=> [CIR][Codegen][NFC] Move buildArrayConstant to CIRGenExprConst namespace

clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/test/CIR/CodeGen/globals.c
* #66
* #65
* __->__ #64
* #63
When emitting variable initializers, if the initializer's evaluation
fails, CodeGen will fall back to regular visitors for the emission.
String literals are then emitted as a constant array of bytes.
This fixes issues with C constant expression initializers that fail
to be evaluated.
=> [CIR][Codegen] Emit string literals

clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/test/CIR/CodeGen/globals.c
* #66
* __->__ #65
* #64
* #63
Implement InitListExpr visitor to emit a cir.const_array attribute.
As a dependency, also implemented methods tryEmitPrivate and
tryEmitForMemory, to both handle emission failures and emissions of
elements not in memory.
=> [CIR][CodeGen] Emit array initialization

clang/lib/CIR/CodeGen/CIRGenCstEmitter.h, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/test/CIR/CodeGen/globals.c
* __->__ #66
* #65
* #64
* #63
Initializer lists can have more or fewer elements than the destination
the array can hold, and the compiler will deal with it.
This patch handles handle these scenarios.
=> [CIR][CodeGen] Handle init list size mismatch

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/Lowering/globals.cir
Fixes parsing for const_arrays with values (ArrayAttribute) with omitted types. In this case, it infers the value's type from the const_array type.
=> [CIR][BugFix] Allow implicit value type in const_array parser

clang/include/clang/Driver/Options.td, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/cc1.c, clang/test/CIR/driver.c
Summary:
This change turns on direct lowering from CIR to LLVM IR by default. A missing API call to register the builtin LLVM dialtect is added, otherwise an error `cannot be converted to LLVM IR: missing `LLVMTranslationDialectInterface` registration for dialect for op: builtin.module` is hit during llvm IR conversion.  A test is also tweaked.
=> [CIR] Enable -fclangir-direct-lowering by default.

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/sourcelocation.cpp
Summary:
As titled. To achieve that I have to update the loc attribute of a func op from using a fused range loc to a single file/loc, since the MLIR builtin support doesn't seem to allow fused locs when converted to LLVM (https://github.com/llvm/clangir/blob/main/mlir/lib/Dialect/LLVMIR/Transforms/DIScopeForLLVMFuncOp.cpp#L27)
=> [CIR] Enabling debug loc to be progatated into LLVM.

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Executables/hello.c
* #106
* #105
* #104
* #102
* #101
* __->__ #100
Adds a function to emit the printf builtin declaration, alongside
some updates to generate calls for said builtin.
=> [CIR][CIRGen] Implement support for printf builtin

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRDataLayout.h, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/cast.cpp, clang/test/CIR/Lowering/cast.cir
* #106
* #105
* #104
* __->__ #102
* #101
* #100
Add required codegen and ABI calls to implement ptr-to-int and
int-to-ptr casts in CIR. Also adds lowering for these casts.
=> [CIR][CIRGen] Implement ptr-to-int and int-to-ptr casts

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/if.cir
* #106
* #105
* __->__ #104
* #102
* #101
* #100
Lowering if operations without an else block would crash during.
Some steps in the IfOp lowering were updated to only be applied
if the else block is not empty.
=> [CIR][Lowering] Patch If without Else lowering

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
* #106
* __->__ #105
* #104
* #102
* #101
* #100
Improves code reusability and readability when lowering CIR's CmpOp to
some LLVM comparison op.
=> [CIR][Lowering] Refactor CmpOp lowering

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/cmp.cir, clang/test/CIR/Lowering/dot.cir, clang/test/CIR/Lowering/for.cir
* __->__ #106
* #105
* #104
* #102
* #101
* #100
Updates CIR's CmpOp lowering to use CIR's custom cir::IntType, allowing
it to handle signed comparisons.
=> [CIR][Lowering] Add support for signed comparisons

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/variadics.c
* #95
* __->__ #94
* #93
Implement the necessary codegen to emit the va_start, va_end, va_arg,
and va_copy builtins as custom CIR instructions.
=> [CIR][CIRGen] Add codegen for stdarg builtins

clang/include/clang/Driver/Options.td, clang/include/clang/Frontend/FrontendOptions.h, clang/lib/Driver/ToolChains/Clang.cpp, clang/lib/FrontendTool/CMakeLists.txt, clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp, clang/test/CIR/CodeGen/mlirargs.c
Summary:
With this change MLIR command line arguments can be passed in with -mmlir, e.g,
clang -mmlir -mlir-disable-threadingd
clang -mmlir -debug-only=mlircontext
=> [CIR] Support MLIR command line arguments.

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/unary.cpp, clang/test/CIR/Lowering/unary-plus-minus.cir
* #110
* #109
* #108
* __->__ #107
Lower plus and minus unary operators when applied to float types.
=> [CIR][Lowering] Lower float plus and minus unary ops

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/unary.c, clang/test/CIR/Lowering/unary-not.cir
* __->__ #110
* #109
* #108
* #107
In C, value negation implicitly casts to int, in C++, it casts to bool.
This patch adds support for the C-specific scenario.
Since both C and C++ share code gen paths for unary negation, the C
cases are handled by casting the boolean type that is already generated
for the C++ cases to an int. The following additions were made:
- Added C style unary negation test case.
- Updated CIR cast to support bool_to_int conversions.
- Lowering bool_to_int conversion as a ZExt operation.
=> [CIR][CIRGen][Lowering] Support C values unary negation

clang/lib/CIR/CMakeLists.txt, clang/lib/CIR/CodeGen/CMakeLists.txt, clang/lib/CIR/Dialect/CMakeLists.txt, clang/lib/CIR/FrontendAction/CMakeLists.txt, clang/lib/CIR/Lowering/DirectToLLVM/CMakeLists.txt, clang/lib/CIR/Lowering/ThroughMLIR/CMakeLists.txt
Summary:
It looks like we can just set up the MLIR include_directories paths in the outermost dirctory of CIR instead of specifying them in each of the subdirectory.
=> [CIR] Clean up include_directories for subdirectories.

clang/lib/CIR/CodeGen/CIRPasses.cpp, clang/lib/FrontendTool/CMakeLists.txt, clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp, clang/test/CIR/CodeGen/mlirprint.c
Summary:
Adding support to print IR after each pass. Example usage: -mmlir --mlir-print-ir-after-all
```
// -----// IR Dump After MergeCleanups (cir-merge-cleanups) //----- // !s32i = !cir.int<s, 32>
module @"/home/hoy/src/clangir/clang/test/CIR/CodeGen/mlirargs.c" attributes {cir.sob = #cir.signed_overflow_behavior<undefined>, dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<i32, dense<32> : vector<2xi32>>, #dlti.dl_entry<f16, dense<16> : vector<2xi32>>, #dlti.dl_entry<f128, dense<128> : vector<2xi32>>, #dlti.dl_entry<f64, dense<64> : vector<2xi32>>, #dlti.dl_entry<!llvm.ptr, dense<64> : vector<4xi32>>, #dlti.dl_entry<i1, dense<8> : vector<2xi32>>, #dlti.dl_entry<i8, dense<8> : vector<2xi32>>, #dlti.dl_entry<i16, dense<16> : vector<2xi32>>, #dlti.dl_entry<f80, dense<128> : vector<2xi32>>, …
```
=> [CIR] Enable per-pass IR printing

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/mlirprint.c
Enabling IR printing to LLVM-lowering related passes.
=> [CIR][Lowering] Enable IR-printing for LLVM passes.

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenCoroutine.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenTypeCache.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/agg-init.cpp, clang/test/CIR/CodeGen/cast.cpp, clang/test/CIR/CodeGen/coro-task.cpp, clang/test/CIR/CodeGen/dtors.cpp, clang/test/CIR/CodeGen/new.cpp, clang/test/CIR/CodeGen/rangefor.cpp, clang/test/CIR/CodeGen/struct.cpp, clang/test/CIR/CodeGen/ternary.cpp, clang/test/CIR/IR/ternary.cir
* #118
* __->__ #117
Implements a custom `!cir.void` type to represent absence of value and
support for void pointers (`!cir.ptr<!cir.void>`).
The `VoidPtrTy` and `UInt8PtrTy` type cache variables no longer share a
union, as they cannot be considered the same in terms of CIR types
(`!cir.ptr<u8i>` is not equivalent to `!cir.ptr<!cir.void>`).
Due to this pointer differentiation, improper occurrences of
`!cir.int<u, 8>` is replaced with `!cir.void` where applicable.
This was mostly done in coroutine-related builtin calls.
Return values for `cir.ternary` operations are now optional allowing
`!cir.void` return types. Consequentially, `!cir.yield` operations with
no operands are allowed within ternary regions.
=> [CIR][CIRGen][Lowering] Implement CIR void type

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenCoroutine.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/IR/func.cir, clang/test/CIR/IR/invalid.cir
* __->__ #118
* #117
Updates FuncType table gen definition to restrict the number of return
types to exactly one.
Patches FuncOp, CallOp, and codegen builders to work with the new
function type definition.
Empty results in FuncType builders are replaced by void types.
Void function definitions can be parsed in three different ways:
- No return type specified: the return type is implicitly void
- Return type specified as void: the return type is explicitly void
- Return type specified as empty: the return type is implicitly void
Some verification checks are removed since they are now implicitly
checked.
Added lowering for void types in both direct and indirect lowering.
=> [CIR] Restrict FuncType to exactly one return type

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/cast.cpp, clang/test/CIR/Lowering/cast.cir
* #127
* #126
* #125
* __->__ #124
Lowering of these casts is done by mapping them to LLVM's SIToFP and
UIToFP casts. Sign interpretation is deferred from CodeGen to the
lowering stage.
=> [CIR][CIRGen][Lowering] Add integral to FP casts

clang/include/clang/CIR/CIRGenerator.h, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/CIRGenerator.cpp, clang/lib/CIR/FrontendAction/CIRGenAction.cpp, clang/test/CIR/CodeGen/globals.c
* #127
* #126
* __->__ #125
* #124
Only external tentative definitions were added.
A method to easily create initialization attributes for distinct types
was added as well.
=> [CIR][CIRGen] Implement tentative definitions

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/cast.cpp, clang/test/CIR/Lowering/cast.cir
* #127
* __->__ #126
* #125
* #124
Essentially lower !cir.cast ops to LLVM's fptosi/fptoui operations.
=> [CIR][Lowering] Lower FP to integral casts

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/func.cir
* __->__ #123
* #130
* #122
* #120
Lowers bitcasts and function types to LLVM Dialect. These are required
to represent indirect call generated by no-proto functions.
=> [CIR][Lowering] Support no-proto functions lowering

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h
* #133
* __->__ #132
MLIR Types are inherently wrappers. Checking if a value exists is a
matter of checking if the type is null.
The Optional wrapper was causing a bug in the `CIRGenModule::buildGlobal`
method. If an empty type (`mlir::Type{}`) was passed as `Ty`, the
`if (!ty)` clause would evalute to true, because the `!` operator would
simply validate that there was a `mlir::Type` in the optional wrapper.
Then the code gen would continue and try to emit an invalid type.
This patch removes the wrapper, which ensures that the `!Ty` clause now
checks if the given `mlir::Type` is an empty type. In that case, it
generates a real type from the AST Type:
```
if (!Ty)
Ty = getTypes().convertTypeForMem(ASTTy);
```
=> [CIR][CIRGen][Bugfix] Remove Optional wrapper from MLIR Type

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/test/CIR/CodeGen/linkage.c, clang/test/CIR/Lowering/globals.cir
* __->__ #133
* #132
Implements the required changes to support static global variables,
ensuring they present the proper linkage type in CIR.
Also tests lowering of CIR globals with internal linkage.
=> [CIR][CIRGen] Add support for static global variables

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/tenary.cir
- Support cir::TernaryOp lowering -cir-to-llvm.
- Mostly mirror the scf.if to cf and cir.if lowerings.
- also support cir.br lowering with type converter, like the `cir.br ^bb3(%9 : !s32i)` , !s32i is !cir.int<s, 32>. and this type not supported in LLVM dialect level.
- current generate `builtin.unrealized_conversion_cast` Ops in tests, will cause the next rountine mlir-translate failed. Need to consider whether to include ReconcileUnrealizedCasts pass or find some other methods.
=> [CIR][Lowering] Support lowering on cir::TernaryOp.

GettingStarted/testing.md
Update `testing.md` `lit` instructions to be in sync with installation `build-install.md`.
=> Update testing.md `lit` instructions

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenClass.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/String.cpp, clang/test/CIR/CodeGen/agg-init.cpp, clang/test/CIR/CodeGen/assign-operator.cpp, clang/test/CIR/CodeGen/ctor-member-lvalue-to-rvalue.cpp, clang/test/CIR/CodeGen/derived-to-base.cpp, clang/test/CIR/CodeGen/lambda.cpp, clang/test/CIR/CodeGen/rangefor.cpp, clang/test/CIR/CodeGen/struct.cpp, clang/test/CIR/CodeGen/unary-deref.cpp
* #149
* __->__ #148
A `member_index` index attribute in `cir.struct_element_addr` now holds
the index for the member being accessed. A APInt is used as the storage
type for the index, alongside a custom builder to abstract the APInt
object creation.
Before, we only passed the name of the field to cir.struct_element_addr,
which was not very useful since it couldn't be used to recover the index
of the member being accessed. This index is essential for lowering CIR
to LLVM, as LLVM needs to know which element is being accessed in the
struct data aggregate.
=> [CIR][CIRGen] Pass field index to cir.struct_element_addr

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/struct.cir
* __->__ #149
* #148
Maps StructElementAddrOp field indexes to LLVM's GEPOp offsets to access
struct members. The current implementation does not account for
anonymous structs nor nested structs, only simple structs.
=> [CIR][Lowering] Lower basic structs

clang/lib/CIR/CodeGen/CIRGenExpr.cpp
* #142
* __->__ #141
Refactor portions of CIRGenFunction::buildArraySubscriptExpr to be more
akin to the original codegen, while also replacing TODO comments and
assertions by `llvm_unreachable` statements with proper messages.
=> [CIR][CIRGen][NFC] Update array subscript feature guarding

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/loop.cir
* #147
* #146
* __->__ #145
* #144
Essentially converts a `cir.loop` op of the `while` kind to a CFG. The
implementation, however, was only tested with structured loops, so if
breaks, continues, or returns are found in the body, it is likely to
break.
=> [CIR][Lowering] Lower structured while loops

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/tenary.cir, clang/tools/cir-tool/cir-tool.cpp
* __->__ #147
* #146
* #145
* #144
=> [CIR] Add reconcile unrealized casts pass

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/test/CIR/CodeGen/binop.c
In C, whenever we logically compare two values, we may store it in any variable type. In this case, the boolean result should be cast to whatever type the variable is. This patch adds support for this.
=> [CIR][CodeGen] Support conditional result implicit cast

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/cast.cpp, clang/test/CIR/Lowering/cast.cir, clang/test/CIR/Lowering/globals.cir
* #157
* #156
* #155
* __->__ #154
Casts from one integer type to another, should not be lowered to LLVM
if the integers are of the same size. These may represent sign drops or
inclusion in CIR but do not make sense in LLVM. This patch fixes that.
=> [CIR][Lowering] Fix CIR casts lowering

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/dot.cir, clang/test/CIR/Lowering/loop.cir
* #157
* __->__ #156
* #155
* #154
This refactor merges the lowering logic of all the different kinds of
loops into a single function.
It also removes unnecessary LIT tests that validate LLVM dialect to
LLVM IR lowering, as this functionality is not within CIR's scope.
Fixes #153
=> [CIR][Lowering][Bugfix] Refactor for loop lowering

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/Lowering/DirectToLLVM/LowerAttrToLLVMIR.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
* __->__ #163
* #162
LLVM's dialect does not have (at the time of writing) a way to represent
zero-initializers. And, despite being possible to represent null
pointers, it requires it to use a region-based initialization. To avoid
this, LLVM operations that use either of these attributes are marked
with a cir.zero string attribute that will be identified by the
LowerAttrToLLVMIR interface and patch the LLVM IR operation to be
initialized with a zero-initializer or null.
=> [CIR][Lowering] Lower #cir.zero and #cir.null attributes

clang/test/CIR/CodeGen/pointer.cpp, clang/test/CIR/CodeGen/struct.c, clang/test/CIR/Translation/zeroinitializer.cir
The goal is to keep tests self-contained and focused. Mixing CIR to LLVM IR translation with codegen tests, or with CIR to LLVM Dialect lowering tests, makes it harder to understand what is being tested and requires the same file to go through multiple tools.
This patch creates a separate `clang/tests/CIR/Translation` folder dedicated strictly to CIR's LLVM IR translation interface. While `tests/Lowering` should validate the `lowerDirectlyFromCIRToLLVMIR` pass, `tests/Translation` should validate `CIRDialectLLVMIRTranslationInterface`.
=> [CIR] Separate CIR to LLVM IR translation tests

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/test/CIR/CodeGen/binop.cpp
While the original codegen attempts to generate a fmuladd, this patch ignores this optimization as it should be deferred to MLIR.
It also updates FP options builder to be closer to the original codegen and improve the tracking of missing features.
=> [CIR][CIRGen] Support floating point subtraction

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/loop.cpp, clang/test/CIR/CodeGen/rangefor.cpp, clang/test/CIR/IR/branch.cir, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/loop.cir, clang/test/CIR/Lowering/dot.cir, clang/test/CIR/Lowering/loop.cir, clang/test/CIR/Transforms/merge-cleanups.cir
Before this patch, the loop operation condition block yielded either empty or continue. This was replaced by a yield of a boolean value.
This change simplifies both codegen and lowering, while also being semantically closer to the C language.
It also refactors loop op codegen tests to validate only the lowering related to the cir.loop operation.
Fixes #161
=> [CIR] Yield boolean value in cir.loop condition region

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/test/CIR/CodeGen/spelling-locations.cpp
Refactors LexicalScopContext to receive a single location and decide
how to use it. This allows the context to have one or two locations for
distinguishing between the start and end of the scope.
Fixes a bug where a mlir::Location was wrongly casted to a mlir::FusedLoc
when building the scope surrounding if statements.
In the rare case where the if statement originates from a preprocessor
macro definition, the location where the macro is expanded is used as
the source location for both the start and the end of the range. Once
these locations are fused, MLIR automatically detects the duplicated
start and end locations and merges them resulting in single a regular
location. This patch allows the if statement to have a single location
as its "begin" and "end" locations.
Note: spelling …
=> [CIR][CIRGen][Bugfix] Refactor lexical scope locations

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/shift.cir
The new cir.shift op allows for distinct value and amount types, however LLVM does not. Before this patch, the amount was not cast to the same width as the value, breaking the lowering process. This patch fixes the issue by casting the amount to the same width as the value.
=> [CIR][Lowering][Bufix] Cast cir.shift amount to same width as the value

clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/test/CIR/CodeGen/struct.c, clang/test/CIR/CodeGen/struct.cpp
* #186
* #185
* __->__ #184
When const initializing a struct builder, the element initialization was
not returning the expected typed attribute with the constant value,
which caused a cast error. This patch fixes this issue. It also adds
missing codegen for building basic records initialization.
=> [CIR][CIRGen][Bugfix] Patch struct builder element initialization

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
* #186
* __->__ #185
* #184
The rationale here is that, since `isNullValue` is meant to check if the
given constant is what the `getNullValue` method would return for a
certain type, it makes sense for `isNullValue` to be encapsulated in
the builder along the `getNullValue` method.
=> [CIR][CIRGen][NFC] Move isNullValue check to CIRGenBuilder

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/loop.cpp, clang/test/CIR/CodeGen/rangefor.cpp, clang/test/CIR/IR/branch.cir, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/loop.cir, clang/test/CIR/Lowering/dot.cir, clang/test/CIR/Lowering/loop.cir, clang/test/CIR/Transforms/merge-cleanups.cir
The changes made to `getSuccessorRegion` seem to have caused an issue. Reverting it until an alternative is found.
This reverts commit 5e449c0cd5d3ba4de61357cafc4ea0fb4463dfd5.
=> Revert "[CIR] Yield boolean value in cir.loop condition region"

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/bool-to-int.cir, clang/test/CIR/Lowering/bool.cir
Before this fix `foo(1, 1)` returned `255` in
```
int foo(int a, int b) {
return a && b;
}
```
The root cause is the sign extension in LLVM dialect to LLVM IR translation in ModuleTranslation.cpp:
```
if (auto intAttr = dyn_cast<IntegerAttr>(attr))                                                                                                                                                          
return llvm::ConstantInt::get(                                              
llvmType,                                                               
intAttr.getValue().sextOrTrunc(llvmType->getIntegerBitWidth()));        
```
=> Fixed generation of LLVM code for true boolean constants.

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/test/CIR/CodeGen/static-vars.c, clang/test/CIR/CodeGen/static-vars.cpp
Whenever a variable declaration is found, it is created as a global variable in the module. In C, these variables must be instantiated with the CIRGenBuilder::createVersionedGlobal to prevent naming conflicts when multiple static variables are declared across the compilation unit. In C++, name mangling is used to prevent naming conflicts.
=> [CIR][CIRGen] Support function basic static variables

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
* #203
* #202
* #201
* #200
* __->__ #199
Remove boilerplate code for replacing a CIR global op with a region
initialized LLVM global op and mark variables as constant whenever
possible.
=> [CIR][Lowering][NFC] Cleanup global ops lowering

clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/struct.c, clang/test/CIR/Lowering/struct.cir
* #203
* #202
* __->__ #201
* #200
* #199
Adds support for CIR globals with basic struct initializers. This patch
tackes only primitive, pointers, and simple nested structs. Arrays,
char pointers, and other more complex types are not supported yet.
=> [CIR][Lowering] Partially lower global #cir.const_struct initializers

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/struct.cir
* __->__ #203
* #202
* #201
* #200
* #199
Updates the lowering of cir.const to support #cir.const_struct as a
initializer, allowing the initialization of local structs with said
attribute.
=> [CIR][Lowering] Partially lower local #cir.const_struct initializers

clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/CodeGen/static-vars.c
* #207
* __->__ #206
Constant initialization of static local arrays would fail due to a
mismatch between the variable and the initializer type size. This patch
fixes the data layout interface implementation for the cir.array type.
A complete array in C/C++ should have its type size in bits equal to
the size of the array times the size of the element type.
=> [CIR][Bugfix] Fix cir.array getTypeSizeInBits method

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/globals.c, clang/test/CIR/Lowering/globals.cir
This change extends `GlobalOpLowering` to handle multi-dimensional arrays in addition to structs.
It slightly changes the logic of how `ConstArrayAttr` is processed: we now first try to lower it to dense attribute (via `lowerConstArrayAttr`) and then, if it failed, proceed with heavyweight region-based lowering.
I'm not sure this commit is in line with future plans for design of `lowerCirAttrAsValue` and friends so let me know if it should be refactored in some way.
=> [CIR][Lowering] Lower global multidimensional array initializers.

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/CodeGen/ConstantInitBuilder.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/vtable-rtti.cpp, clang/test/CIR/IR/vtableAttr.cir
PR #200 broke the vtableAttr usage, as it was not properly refactored to use ArrayAttr instead of ConstStructAttr to store its members.
=> [CIR][Bugfix] Fix vtableAttr const struct usage

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenCXX.cpp, clang/lib/CIR/CodeGen/CIRGenCoroutine.cpp, clang/lib/CIR/CodeGen/CIRGenDeclCXX.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/static.cpp, clang/test/CIR/IR/global.cir
This change does the CIR generation for globals initialized by a constructor call. It currently only covers C++ to CIR generation. The corresponding LLVM lowering will be in a follow-up commit.
A motivating example is
```
class Init {
friend class ios_base;
public:
Init(bool);
~Init();
private:
static bool _S_synced_with_stdio;
};
static Init ioinit(true);
```
Unlike what the default Clang codegen generates LLVM that detaches the initialization code from the global var definition (like below), we are taking a different approach that keeps them together, which we think will make the later dataflow analysis/transform easier.
```
@_ZL8ioinit = internal global %class.Init zeroinitializer, align 1, !dbg !0
define internal void @cxx_global_var_init() #0 section ".text.startup" !dbg !23 {
entry: …
```
=> [CIR][CodeGen] Emit globals with constructor initializer

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/loops-with-break.cir, clang/test/CIR/Lowering/loops-with-continue.cir
This PR fixes lowering for `break/continue`  in loops.
The idea is to replace `cir.yield break`  and `cir.yield continue` with the branch operations to the corresponding blocks. Note, that we need to ignore nesting loops and don't touch `break` in switch operations. Also, `yield` from `if` need to be considered only when it's not the loop `yield` and `continue` in switch is ignored since it's processed in the loops lowering. 
Fixes #160
=> [CIR][Lowering] Fixed break/continue lowering for loops

clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenCall.h, clang/test/CIR/CodeGen/struct.c
Essentially emits an LValue for the struct and then passes it as a call argument.
=> [CIR][CIRGen] Support for struct call arguments

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerAttrToLLVMIR.cpp, clang/test/CIR/CodeGen/optnone.cpp
Summary:
Setting the Optnone attribute for CIR functions and progating it all the way down to LLVM IR for those not supposed to be optimized.
=> [ClR] Set optnone attribute for functions.

clang/include/clang/CIR/Dialect/Passes.h, clang/include/clang/CIR/Dialect/Passes.td, clang/lib/CIR/CodeGen/CIRPasses.cpp, clang/lib/CIR/Dialect/Transforms/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/mlirprint.c
This change is a prerequisite of https://github.com/llvm/clangir/pull/235
=> [CIR][Lowering] Add an empty LoweringPrepare pass

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenCXX.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/static.cpp
As a follow up to https://github.com/llvm/clangir/pull/197, this change pre-lowers high-level CIR for global initializers.
High-level CIR:
```
cir.global "private" internal @_ZL8__ioinit = ctor : !ty_22class2EInit22 {
%0 = cir.get_global @_ZL8__ioinit : cir.ptr <!ty_22class2EInit22> loc(#loc8)
%1 = cir.const(#true) : !cir.bool loc(#loc5)
cir.call @_ZN4InitC1Eb(%0, %1) : (!cir.ptr<!ty_22class2EInit22>, !cir.bool) -> () loc(#loc6)
}
```
After pre-lowering:
```
cir.global "private" internal @_ZL8__ioinit =  #cir.zero : !ty_22class2EInit22 {ast = #cir.vardecl.ast}
cir.func internal private @__cxx_global_var_init() {
%0 = cir.get_global @_ZL8__ioinit : cir.ptr <!ty_22class2EInit22>
%1 = cir.const(#true) : !cir.bool
cir.call @_ZN4InitC1Eb(%0, %1) : (!cir.ptr<!ty_22class2EInit22>, !cir.bool) -> …
```
=> [CIR][Lowering] Add LoweringPrepare pass to pre-lower global initializers

clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/test/CIR/CodeGen/switch.cpp
This PR fixes CIR generation for the `switch-case` cases like the following:
```
case 'a':
default:
... 
```
or
```
default:
case 'a':
...
```
i.e. when the `default` clause is sub-statement of the `case` one and vice versa.
=> [CIR][CIRGen][Bugfix] Fixes switch-case sub statements

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/test/CIR/CodeGen/array.c
* #221
* #220
* #219
* #218
* #217
* __->__ #216
Whenever a global array is declared and initialized with fewer elements
than its size, the remaining elements are implicitly initialized with
zero. For aggregates types, such as structs, the initialization is done
through the #cir.zero attribute.
=> [CIR][CIRGen] Implicitly zero-initialize global arrays elements

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/test/CIR/CodeGen/array.cpp
* #221
* #220
* #219
* #218
* __->__ #217
* #216
This small improvement allows for a more compact representation of
structs with zero-initialized fields in the C++ codegen.
=> [CIR][CIRGen] Update C++ codegen to use #cir.zero on structs

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Lowering/DirectToLLVM/LowerAttrToLLVMIR.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Translation/zeroinitializer.cir
* #221
* #220
* #219
* __->__ #218
* #217
* #216
Due to the lack of zeroinitializer support in LLVM, some cases are
tricky to lower #cir.zero. An example is when an array is only partially
initialize with #cir.zero attributes. Since we can't just zeroinitialize
the whole array, the current #cir.zero attribute amend does not suffice.
To simplify the lowering, this patch introduces a new operation that is
solely used to generate zeroinitialize LLVM IR constants.
=> [CIR][Lowering] Implement cir.llvmir.zeroinit operation

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/array.cir
* #221
* #220
* __->__ #219
* #218
* #217
* #216
Supports lowering for #cir.zero attributes when it appears in aggregate
attributes such as #const.array and #cir.struct.
=> [CIR][Lowering] Lower #cir.zero nested in initializer attributes

clang/lib/CIR/Lowering/DirectToLLVM/CMakeLists.txt, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp
* #221
* __->__ #220
* #219
* #218
* #217
* #216
The rationale is that we are lowering more than just attributes now,
also to maintain the naming standard of the other lowering files
(e.g. LowerToLLVM).
=> [CIR][Lowering][NFC] Rename LowerAttrToLLVMIR to LowerToLLVMIR

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp, clang/test/CIR/Translation/zeroinitializer.cir
* __->__ #221
* #220
* #219
* #218
* #217
* #216
This replaces the usage of attributes for zero-initializing global
variables, with a more robust zero-initialization op-based method
(cir.llvmir.zeroinit).
The downside of this approach is that is not as compact or efficient as
the attribute-based method, however:
- Both are temporary solutions, but it's easier to track and patch
the usage of a single op than an attribute in any op.
- Attribute-based method is more difficult to lower, requiring more
maintenance.
- Op-based method may require a region, but it will populate the region
with at most a couple of operations.
=> [CIR][Lowering] Deprecate attributes for LLVM zero-initialization

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/array.cpp, clang/test/CIR/CodeGen/pointers.cpp
When using subscript access operators on pointers and decayed arrays, an `array_to_ptrdecay` was wrongly applied, generating invalid strides.
=> [CIR][CIRGen][Bugfix] Fix pointer subscript operator access

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/static.cpp, clang/test/CIR/Lowering/globals.cir
Creating the `llvm.global_ctors` list to hold all global dynamic initializers. The list has the following format:
```
%0 = type { i32, ptr, ptr }
@llvm.global_ctors = appending global [1 x %0] [%0 { i32 65535, ptr @ctor, ptr @data }]
```
The list will be converted to `.init_array` for ELF by LLVM which will be loaded and executed by the C++ runtime.
=> [CIR][Lowering] Emit llvm.global_ctors list

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.cpp, clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/lib/CIR/CodeGen/ConstantInitBuilder.cpp
* #230
* #229
* #228
* #227
* #226
* __->__ #225
Updates every struct type creation to use the CIRGenBuilder API.
=> [CIR][CIRGen][NFC] Refactor struct type building

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/CodeGen/agg-init.cpp, clang/test/CIR/CodeGen/atomic.cpp, clang/test/CIR/CodeGen/bitfields.cpp, clang/test/CIR/CodeGen/coro-task.cpp, clang/test/CIR/CodeGen/ctor.cpp, clang/test/CIR/CodeGen/derived-to-base.cpp, clang/test/CIR/CodeGen/dtors.cpp, clang/test/CIR/CodeGen/lambda.cpp, clang/test/CIR/CodeGen/move.cpp, clang/test/CIR/CodeGen/nrvo.cpp, clang/test/CIR/CodeGen/rangefor.cpp, clang/test/CIR/CodeGen/struct.c, clang/test/CIR/CodeGen/struct.cpp, clang/test/CIR/CodeGen/union.cpp, clang/test/CIR/CodeGen/vtable-rtti.cpp, clang/test/CIR/IR/global.cir, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/struct.cir, clang/test/CIR/IR/vtableAttr.cir, clang/test/CIR/Lowering/globals.cir, clang/test/CIR/Lowering/struct.cir, clang/test/CIR/Lowering/variadics.cir
* #230
* #229
* #228
* #227
* __->__ #226
* #225
This change simplifies the StructType printing/parsing methods. It also
updates the representations to group members between braces and to
remove commas between type attributes (e.g. id, packed, etc.).
=> [CIR] Refactor StructType printing/parsing

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/String.cpp, clang/test/CIR/CodeGen/agg-init.cpp, clang/test/CIR/CodeGen/assign-operator.cpp, clang/test/CIR/CodeGen/ctor-member-lvalue-to-rvalue.cpp, clang/test/CIR/CodeGen/derived-to-base.cpp, clang/test/CIR/CodeGen/lambda.cpp, clang/test/CIR/CodeGen/rangefor.cpp, clang/test/CIR/CodeGen/struct.cpp, clang/test/CIR/CodeGen/unary-deref.cpp, clang/test/CIR/Lowering/struct.cir
* #230
* #229
* __->__ #228
* #227
* #226
* #225
Improves a few aspects of the old CIR GEP equivalent:
* Generalize the name to GetMemberOp, since it can be used for
unions, classes, structs, and others.
* Add custom assembly format to improve readability.
* Add a new CIR dialect operation to represent the operation.
* Remove redundancy from arguments names (e.g. "member_index" to just
"index") for terseness.
* Add verifier to check if:
* The index is within bounds.
* The type is a record (has members to be accessed).
* The result type matches the type of the member.
* Use CIRGenBuilder when building GetMemberOps.
* Also add some getter wrappers.
=> [CIR] Refactor StructElementAddr into GetMemberOp

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/test/CIR/CodeGen/union.cpp
* #230
* __->__ #229
* #228
* #227
* #226
* #225
This diverges from the original codegen by tracking all members of a
union, instead of just the largest one. This is necessary to support
type-checking at the MLIR level when accessing union members. It also
preserves more information about the source code, which might be useful.
Fixes #224
=> [CIR][CIRGen][Bugfix] Update unions to track all members

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/unions.cir
* __->__ #230
* #229
* #228
* #227
* #226
* #225
Converts a union to a struct containing only its largest element.
GetMemberOp for unions is lowered as bitcasts instead of GEPs, since
union members share the same address space.
=> [CIR][Lowering] Lower unions

GettingStarted/testing.md, Standalone/single-source-tests-table.md
- Move SingleSource results table to an isolated page.
- Fix `make` command for building SingleSource tests.
- Add the percentage of SingleSource tests successfully passing.
=> Isolate SingleSource tests results table

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenCXX.cpp, clang/lib/CIR/CodeGen/CIRGenCXXABI.h, clang/lib/CIR/CodeGen/CIRGenDeclCXX.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/static.cpp, clang/test/CIR/IR/global.cir, clang/test/CIR/IR/invalid.cir
Similar with the previous ctor support, I'm bringing up the dtor support for global var initialization.
This change only contains the CIR early codegen work. The upcoming lowering prepare work will be in a separate change.
=> [CIR][Codegen] Destructor support for global variable initialization

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/cast.cpp
This a small  PR  that is a sort of copy-pasta from the original `Codegen` and handles expressions like `(int *) &a `.
Also, a small bug was fixed - no `!` in assert for the `&` operator
=> [CIR][CIRGen] fixes explicit cast and minor bug in unary & operator

clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/static.cpp
This change adds lowering support for global variable definition with destructor.
For example:
```
cir.global "private" internal @_ZL8__ioinit = ctor : !ty_22Init22 {
%0 = cir.get_global @_ZL8__ioinit : cir.ptr <!ty_22Init22>
%1 = cir.const(#true) : !cir.bool
cir.call @_ZN4InitC1Eb(%0, %1) : (!cir.ptr<!ty_22Init22>, !cir.bool) -> ()
} dtor {
%0 = cir.get_global @_ZL8__ioinit : cir.ptr <!ty_22Init22>
cir.call @_ZN4InitD1Ev(%0) : (!cir.ptr<!ty_22Init22>) -> ()
}
```
is now lowered to 
```
cir.func internal private @__cxx_global_var_init() {
%0 = cir.get_global @_ZL8__ioinit : cir.ptr <!ty_22Init22>
%1 = cir.const(#true) : !cir.bool
cir.call @_ZN4InitC1Eb(%0, %1) : (!cir.ptr<!ty_22Init22>, !cir.bool) -> ()
%2 = cir.get_global @_ZL8__ioinit : cir.ptr <!ty_22Init22>
%3 = cir.get_global …
```
=> [CIR][Lowering] Global destructor support

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/globals.c, clang/test/CIR/CodeGen/globals.cpp, clang/test/CIR/IR/global.cir, clang/test/CIR/Lowering/globals.cir
This PR replaces `SymbolRefAttr`'s generated for string literals with `GlobalViewAttr`'s to get rid of the
```
this should always be typed
UNREACHABLE executed at /home/huawei/src/clangir/clang/lib/CIR/CodeGen/CIRGenExprConst.cpp:1428!
```
error in
```
char *name;
} A;
A foo = {"1"};
```
I'm not sure that my usage of `GlobalViewAttr`'s `indices` matches its intentions so marking this as draft.
=> [CIR][CIRGen][Lowering] Generate GlobalViewAttr for string literals (#242).

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/bool.c
This PR removes the method `hasBooleanRepresentation` as was discussed in [PR#233](https://github.com/llvm/clangir/pull/233)
Briefly, the `cir.bool` has the same representation in memory and after load. The LLVM IR differs, that's why the  check is there, in the origin `CodeGen`.
Also, in order to trigger the path and make the implementation to be conform with the original `CodeGen`,  there are changes in the `CIRGenExprScalar`: call the common `buildFromLValue`  instead of manaul `load` creation.
Also, a couple of tests for the bool load/store added
=> Removes hasBooleanRepresentation

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.cpp, clang/lib/CIR/CodeGen/ConstantInitBuilder.h, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/String.cpp, clang/test/CIR/CodeGen/agg-init.cpp, clang/test/CIR/CodeGen/basic.cpp, clang/test/CIR/CodeGen/constptr.c, clang/test/CIR/CodeGen/coro-task.cpp, clang/test/CIR/CodeGen/derived-to-base.cpp, clang/test/CIR/CodeGen/pointer.cpp, clang/test/CIR/CodeGen/struct.c, clang/test/CIR/CodeGen/struct.cpp, clang/test/CIR/CodeGen/types-nullptr.cpp, clang/test/CIR/CodeGen/vtable-rtti.cpp, clang/test/CIR/IR/global.cir, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/vtableAttr.cir, clang/test/CIR/Lowering/globals.cir, clang/test/CIR/Lowering/struct.cir, clang/test/CIR/Lowering/types.cir
Introducing `cir.ConstPtrAttr` to represent arbitrary absolute pointer value initializations. Also incorporating previous `cir.nullptr` effort into this work.
=> [CIR] Introduce ConstPtrAttr for absolute pointer value initialization.

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/loop.cir
This is a dumb fix for #161 which fixes crashes on endless loops like `for(;;)`. A better long-term approach could be to resurrect the reverted #178.
=> [CIR][Lowering] Support endless loops (gh-161)

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/libc.c, clang/test/CIR/IR/libc-fabs.cir, clang/test/CIR/Lowering/libc.cir
Following discussion in #237 this adds support for `fabs` builtins which are used extensively in llvm-test-suite.
=> [CIR] Implement cir.libc.fabs operation.

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/getmember.cir, clang/test/CIR/IR/invalid.cir
Temporary workaround until we patch the codegen for record types.
=> [CIR][IR] Bypass get_member verifier for incomplete types

clang/lib/CIR/CodeGen/CIRGenCXXABI.h, clang/lib/CIR/CodeGen/CIRGenClass.cpp, clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.h, clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/test/CIR/CodeGen/vbase.cpp
This patch brings up the basic support for C++  virtual inheritance. VTT (virtual table table) now can be laid out as expected for simple program with single virtual inheritance. RTTI support is on the way.
This patch does not include LLVM lowering support.
=> [CIR][Codegen] VTT support for virtual class inheritance

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/derived-to-base.cpp
There is a bug in the code generation:  the field index for the `GetMemberOp` is taken from the `FieldDecl`, with no respect to the record layout. One of the manifestation of the bug is the wrong index  generated for a field in a derived class that does not take into the account the instance of the base class (that has index 0).  
You can take a look at the example in `test/CIR/CodeGen/derived-to-base.cpp`, i.e. the current test is not the correct one
```
// CHECK-DAG: !ty_22C23A3ALayer22 = !cir.struct<class "C2::Layer" {!ty_22C13A3ALayer22, !cir.ptr<!ty_22C222>
// CHECK-DAG: !ty_22C33A3ALayer22 = !cir.struct<struct "C3::Layer" {!ty_22C23A3ALayer22
// CHECK: cir.func @_ZN2C35Layer10InitializeEv
// CHECK:  cir.scope {
// CHECK:    %2 = cir.base_class_addr(%1 : cir.ptr …
```
=> [CIR][CodeGen][Bugfix] generate field index with respect to layout 

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/scope.cir
This PR adds MLIR lowering of `cir.scope`.
I also notice that the MLIR unit tests still uses old integer types. I will fix those in a separate PR.
=> [CIR][Lowering] Add scf.scope lowering to standard dialects

clang/lib/CIR/Dialect/IR/CMakeLists.txt
Looks like that after [AST attributes PR](https://github.com/llvm/clangir/pull/250)  the build with shared libs (`-DBUILD_SHARED_LIBS=ON `) is broken. This PR fix it
=> [CIR][Bugfix] adds missing clangAST dependency

clang/lib/CIR/CodeGen/CIRGenClass.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/derived-to-base.cpp
This is a minor fix similar to the one introduced in #263.
Basically, all calls to the `buildLValueForFieldInitialization`  are even with  the origin codegen `emitLValueForFieldInitialization` calls, i.e. the field index is calculated from the record layout, but not from the decl `field->getFieldIndex()`.
Added just one test, because looks like we need to implement some `NYI` features first  to test another places e.g. in `CIRGenExprAgg.cpp`, though I could miss something. 
Anyway, given the original codegen doesn't use `getFieldIndex` in these places, we also should not.
All the remaining usages of `getFieldIndex` are ok.
=> [CIR][Codegen][Bugfix] use record layout to generate index for a field

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/array.cir, clang/test/CIR/Lowering/binop-fp.cir, clang/test/CIR/Lowering/bool.cir, clang/test/CIR/Lowering/call.cir, clang/test/CIR/Lowering/cast.cir, clang/test/CIR/Lowering/dot.cir, clang/test/CIR/Lowering/func.cir, clang/test/CIR/Lowering/globals.cir, clang/test/CIR/Lowering/hello.cir, clang/test/CIR/Lowering/loadstorealloca.cir, clang/test/CIR/Lowering/loop.cir, clang/test/CIR/Lowering/ptrstride.cir, clang/test/CIR/Lowering/scope.cir, clang/test/CIR/Lowering/struct.cir, clang/test/CIR/Lowering/tenary.cir, clang/test/CIR/Lowering/types.cir, clang/test/CIR/Lowering/unary-not.cir, clang/test/CIR/Lowering/unary-plus-minus.cir, clang/test/CIR/Lowering/unions.cir, clang/test/CIR/Lowering/variadics.cir
Updates the lowering pass to use only opaque pointers. This essentially involves updating the type converter to drop pointee types and explicitly defining the types loaded/stored/GEPed by LLVM operations.
The reasons for this are twofold:
- LLVM dialect is currently transitioning to deprecate typed pointers, allowing only opaque pointers. The sooner we transition the fewer changes we will have to make.
- Opaque pointers greatly simplify lowering self-references, since all self-references in records are wrapped in a pointer.
=> [CIR][Lowering] Deprecate typed LLVM dialect pointers

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/cast.cir, clang/test/CIR/Lowering/dot.cir, clang/test/CIR/Lowering/globals.cir, clang/test/CIR/Lowering/hello.cir, clang/test/CIR/Lowering/ptrstride.cir, clang/test/CIR/Lowering/struct.cir, clang/test/CIR/Lowering/variadics.cir
The wrong element type was being passed to LLVM's GEP op, generating an invalid IR. Tests were also updated to properly validate the `llvm.getelementptr` element type.
Fixes #272
=> [CIR][Lowering][Bugfix] Fix GetMemberOp lowering

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/branch.cir
This PR adds `cir.brcond` lowering, which more or less follows the one in LLVM dialect lowering.
=> [CIR][Lowering] Add cir.brcond lowering

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/struct.c
This is a suggestion to relax the existing verification even more than we did it in PR #257. 
Here we also skip verification if a field on the given index is also of incomplete type - and we can not compare it with the result type of the operation.
Now the next code fails with type mismatch error:
```
typedef struct Node {    
struct Node* next;
} NodeStru;
void foo(NodeStru* a) {        
a->next = 0;
}
```
because the result type is kind of full and the type of field is not (for the reasons discussed in #256). 
Basically, the problem is in the `GetMemberOp`  result type generated as following (via `CIRGenTypes::convertType`)
`!cir.ptr<!cir.struct<struct "Node" {!cir.ptr<!cir.struct<struct "Node" incomplete #cir.record.decl.ast>>} #cir.record.decl.ast>>`
where the field type at index …
=> [CIR][IR] Relax get_member verifier for incomplete types

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/test/CIR/CodeGen/struct.c
Just a trivial fix that enables declaration of local structs. 
Basically, there it's a copy-pasta from the original `CodeGen`, without debug info handling.
=> [CIR][CodeGen][Bugfix] supports local structs decl

clang/lib/CIR/CodeGen/CIRGenCXX.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/globals.cpp
This PR handles globals initializations for c++ code for the case when a global is inited from a function call or another global.
=> [CIR][CodeGen][Bugfix] fixes global vars initialization

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/test/CIR/CodeGen/bitfields.c, clang/test/CIR/CodeGen/bitfields.cpp, clang/test/CIR/CodeGen/coro-task.cpp, clang/test/CIR/CodeGen/lambda.cpp, clang/test/CIR/CodeGen/union.cpp
Traditional Clang's codegen generates IDs for anonymous records (e.g. "struct.anon.1") and ensures that they are unique. This patch does the same for CIRGen, which, until now, would just identify any anonymous record as "anon".
This will be required to support mutable structs uniquely identified by their names.
=> [CIR][CIRGen] Ensure unique IDs for anonymous records

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/IR/aliases.cir
Rename `typeName` to just `name`, also use `StringAttr`'s nullability to identify if the record is identified or anonymous. Unnamed structs are also no longer aliased, as they have no unique name to be used in the alias.
=> [CIR] Rename StructType "typeName" attribute to "name"

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/vbase.cpp
This patch adds RTTI support for C++ virtual inheritance. 
This patch does not include LLVM lowering support.
=> [CIR][Codegen] RTTI support for virtual class inheritence

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.cpp, clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp
The `body` attribute is used to identify if a struct type has a body or not. In other words, it separates complete from incomplete structs. For this reason, the `body` attribute was renamed to `incomplete`, matching its keyword in the CIR language.
=> [CIR][NFC] Refactor StructType body attribute

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp
MLIR's attributes are inherently nullable, so there is no need to use std::optional to represent a nullable attribute. This patch removes std::optional from StructType's ast attribute to simplify its usage.
=> [CIR][NFC] Remove std::optional from StructType ast attribute

clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/test/CIR/Lowering/ThroughMLIR/scope.cir
Fixes a switch case warning in which not all cases were being handled. And also fixes an incorrect XFAIL in the tests.
=> [CIR][CIRGen][NFC] Fix post-rebase errors and warnings

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/cast.cpp
In the CIR CodeGen function `ScalarExprEmitter::buildScalarCast`, implement conversions from bool to an integral type.  This was inadvertently left out in earlier changes.
Reorganize the code in the function to be more clear, with better assertion failure messages when encountering an unimplemented construct.
This is a partial fix for issue #290
=> [CIR] Implement bool->int conversion

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/lib/CIR/CodeGen/CIRGenBuilder.h
As discussed in #279, we  split  `CIRGenBuilder`  in two parts, which make some of the helpers  usable outside of the `CodeGen` part. 
Basically, I placed casts and binary operations  into a separate class, `CIRBaseBuilder`. Later, it can be extended with another helpers. But right now an idea to have a state less builder as a base one.
=> [CIR][CodeGen] introduce CIRBaseBuilder

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/cast.cpp
A silly fix for code like
```
*(char *)0 = 0;
```
=> [CIR][CodeGen] Support integer-to-pointer casts.

clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/test/CIR/CodeGen/coro-task.cpp, clang/test/CIR/CodeGen/new.cpp, clang/test/CIR/CodeGen/nrvo.cpp, clang/test/CIR/CodeGen/rangefor.cpp, clang/test/CIR/CodeGen/vector.cpp
Currently, different specializations of a template will generate distinct types with the same name. To properly differentiate each specialization, this patch includes the template arguments in the name of the type.
This will be required to support mutable structs uniquely identified by their names.
=> [CIR][CIRGen] Ensure unique names for template specializations

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/CodeGen/struct.c, clang/test/CIR/CodeGen/vtable-rtti.cpp, clang/test/CIR/IR/aliases.cir, clang/test/CIR/IR/invalid.cir
Instead of using a single builder for every possible StructType, we now have three builders: identified complete, identified incomplete, and anonymous struct types. This allows us to enforce correctness and to explicitly show the intent when creating a StructType.
=> [CIR][CIRGen] Refactor StructType builders

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/IR/global.cir, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/struct.cir, clang/test/CIR/IR/vtableAttr.cir
There are instances of CIR where anonymous structs are generated as identified structs with an empty name. This patch Adds a verifier for StructType, which ensures structs have a non-empty name.
This will be required for properly uniqueing mutable CIR structs.
=> [CIR] Forbid identified structs with empty names

clang/include/clang/CIR/Dialect/IR/CIRTypes.h, clang/include/clang/CIR/Dialect/IR/CIRTypesDetails.h, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/CodeGen/agg-init.cpp, clang/test/CIR/CodeGen/atomic.cpp, clang/test/CIR/CodeGen/bitfields.c, clang/test/CIR/CodeGen/bitfields.cpp, clang/test/CIR/CodeGen/coro-task.cpp, clang/test/CIR/CodeGen/ctor.cpp, clang/test/CIR/CodeGen/derived-to-base.cpp, clang/test/CIR/CodeGen/dtors.cpp, clang/test/CIR/CodeGen/forward-decls.cpp, clang/test/CIR/CodeGen/lambda.cpp, clang/test/CIR/CodeGen/move.cpp, clang/test/CIR/CodeGen/nrvo.cpp, clang/test/CIR/CodeGen/rangefor.cpp, clang/test/CIR/CodeGen/struct.c, clang/test/CIR/CodeGen/struct.cpp, clang/test/CIR/CodeGen/union.cpp, clang/test/CIR/CodeGen/vtable-rtti.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/struct.cir
* __->__ #303
* #302
This allows a named StructType to be mutated after it has been created,
if it is identified and incomplete.
The motivation for this is to improve the codegen of CIR in certain
scenarios where an incomplete type is used and later completed. These
usually leave the IR in an inconsistent state, where there are two
records types with the same identifier but different definitions (one
complete the other incomplete).
For example:
```c++
struct Node {
Node *next;
};
void test(struct Node n) {}
```
Generates:
```mlir
!temp_struct = !cir.struct<struct "Node" incomplete>
!full_struct = !cir.struct<struct "Node" {!cir.ptr<!temp_struct>}>
```
To generate the `Node` struct type, its members must be created …
=> [CIR][CIRGen] Support mutable and recursive named records

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
Matrix types are already checked for in `buildScalarConversion`, so they don't need to be checked for again in `buildScalarCast`. Not having to worry about matrix types means the `Element` local variables are no longer necessary.
Remove duplicate code by having a variable to store the `CastKind`, and have only one call to `Builder.create<CastOp>`.
There are no test changes, because this is refactoring only. There should be no functional changes.
=> [CIR] Refactor ScalarExprEmitter::buildScalarCast

clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/test/CIR/CodeGen/constptr.c
The PR fixes a var initialization with explicit cast.
=> [CIR][CodeGen][Bugfix] fixes explicit cast in initialization

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/cast.cpp, clang/test/CIR/IR/invalid.cir
Add a new entry to enum `CastKind`, `bool_to_float`, since none of the existing enum values adequately covered that conversion.  Add code to code gen, CIR validation, LLVM lowering, and the cast test to cover this conversion.
Fix ClangIR issue #290
=> [CIR] Support bool-to-float conversions

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/invalid.cir
Fix a couple typos in the validation failure messages for scalar casts
=> [CIR] Add validation tests for scalar casts

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/invalid.cir
* #314
* #313
* #312
* #311
* __->__ #310
The `shouldPrintTerm` and `checkBlockTerminator` were replaced in favor
of `omitRegionTerm` and `ensureRegionTerm` respectively. The first is
essentially the same method but simplified. The latter was refactored to
do only two things: check if the terminator omission of a region is
valid and, if so, insert the omitted terminator into the region.
The simplifications mostly leverage the fact that we only omit empty
yield values in a single-block region.
=> [CIR][IR] Refactor parsing/printing of implicitly terminated regions

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/cast.cpp
Conversions from an integer to a pointer are implemented in CIR code gen as an integral conversion to uintptr_t followed by the integral-to-pointer conversion.  Conversions from bool to pointer were following the same code path.  But bool-to-int is a different CastKind than int-to-int in CIR, and CIR was failing validation.  Fix the integer to pointer conversion code to correctly handle a source type of bool.
(A conversion from bool to pointer makes no sense and should never happen in the real world.  But it is legal due to bool being sort of an integral type.  So we need to support it.)
Also, in `ScalarExprEmitter::buildScalarConversion` change a couple not-yet-implemented messages about pointer types into assertion failures.  Conversions involving pointer types should never go through …
=> [CIR] Fix bool-to-pointer conversions

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/test/CIR/CodeGen/agg-init.cpp, clang/test/CIR/CodeGen/vtable-rtti.cpp
This PR fixes a bug with wrong arguments passed into the call to `buildAnyExpr`. This function has args with default  values, hence the bug occurred. 
All the changes are even with the clang's original codegen.
For the reference, the LLVM IR code for `agg-init.cpp::usev()` function looks like the following:
```
define dso_local void @_Z3usev() #0 {
entry:
%agg.tmp.ensured = alloca %struct.yep_, align 4
%Status = getelementptr inbounds %struct.yep_, ptr %agg.tmp.ensured, i32 0, i32 0
store i32 0, ptr %Status, align 4
%HC = getelementptr inbounds %struct.yep_, ptr %agg.tmp.ensured, i32 0, i32 1
store i32 0, ptr %HC, align 4
ret void
}
```
=> [CIR][Codegen][Bugfix] ensure proper tmp location for agg exprs

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/test/CIR/CodeGen/globals.c
This PR adds proper handling for address offsets in global initializers as e.g. in
```
int val[10];                                                                     
int *addr = &val[1];                                                               
```
(such offsets are ignored on current trunk).
I'm not proud of this patch because it performs an ugly conversion from byte offset, produced by `APValue::getLValueOffset`, to a sequence of CIR indices. Alternative suggestions are welcomed.
=> [CIR][CodeGen] Support global variable offsets in initializers (gh-299).

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/vbase.cpp
Two fixes were applied:
- A couple of `lowerCirAttrAsValue` visitors were fixed as one of the arguments was missing the const qualifier on the type converter. To avoid this problem, the const qualifier was moved to before the type.
- In the type converter, `cir.struct`s were wrongly identified by their name's length, now, they are identified by their name's existence.
=> [CIR][Lowering] Fix vbase.cpp test

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/test/CIR/CodeGen/agg-init2.cpp
This patch fixes the agg-init2.cpp test by doing two things:
- Updating the `VisitCXXConstructExpr` to return a zero attribute initializer for trivial zero-initialized objects.
- Forcing the `buildAutoVarInit` method to use ctor calls on temporary object expressions even if the object can be constant-initialized.
=> [CIR][CIRGen] Fix agg-init2.cpp test

clang/test/CIR/Lowering/ThroughMLIR/array.cir, clang/test/CIR/Lowering/ThroughMLIR/dot.cir
Replaces the usage of builtin integers in the CIR code and removes the dynamic dimension from `memref`s lowered from `!cir.ptr` types.
=> [CIR][NFC] Remove XFAIL from ThroughMLIR tests

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/scope.cir
* __->__ #311
* #321
This simplifies and modularizes the assembly format for ScopeOp by
using the Tablegen assembly description and a new custom printer/parser
that handles regions with omitted terminators.
It also fixes an issue where the parser would not correctly handle
`cir.scopes` with a return value.
=> [CIR][IR] Refactor ScopeOp assembly format

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/IR/alloca.cir, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/alloca.cir
This PR adds array size into `AllocaOp` that will be useful in future  - currently I work on variable length array support. So I start to make tiny PRs in advance)
No changes in tests needed, I tried  to make the changes as smooth as possible, so no existing `AllocaOp` usages need to be changed.
=> [CIR][CodeGen] adds array size into AllocaOp

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/globals.cir
This PR fixes a global vars lowering with a funciton ptr field. Previously, the next code caused fail in the `foo` lowering:
```
static void myfun(int a) {}
static struct {
void (*func)(int flag);
} const Handlers[] = {
{myfun}, {myfun}, {myfun}
};
void foo(int i, int flag) {
Handlers[i].func(flag);
}
```
=> [CIR][Lowering] fix lowering for a function ptr field in a global struct

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/test/CIR/CodeGen/globals.c
Before this fix conversion of flat offset to GlobalView indices could crash or compute invalid result.
=> [CIR][CodeGen] Fix flat offset lowering code to consider field alignments

clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/switch.cpp, clang/test/CIR/Lowering/switch.cir
This PR adds a support for the multi-block case statements.
Previously, the code example below caused crash in cir verification 
Lowering to the `llvm` dialect is pretty straightforward: the same logic as before is applied to all the region's blocks with no successors, i.e. we no longer think a case/default region contains only one block.
The `CodeGen` part is a little bit tricky. Previously, any sub-statement  of `case` or`default`, that was not any of them (i.e. neither `case` nor `default`) was processed with an insertion guard, meaning that the next sub-statement in the same clause was inserted again in the same block as the first one. It would be fine, once sub-statement didn't generate any blocks as well. 
For instance, 
```
void foo(int a) {
switch (a)
{
case 3:
return;
break;
}
} …
```
=> [CIR][CodeGen][Lowering] Support multi-block case/default clauses

GettingStarted/build-install.md
This renaming was forgotten in "Build and install" section after
https://github.com/llvm/clangir/commit/3bdb4f282f928843605d041726ab20f47332e93b
=> [CIR][DOC] Rename cir-tool to cir-opt

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenTypeCache.h, clang/test/CIR/CodeGen/ptr_diff.cpp
Before this fix attached test case has been failing due to type mismatch (signed vs unsigned).
=> [CIR][CodeGen] Use signed type for result of ptrdiff operation.

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/test/CIR/CodeGen/gnu89.c
Tiny PR, support `-std=gnu89` option
This is quite frequent bug in `llvm-test-suite`
=> [CIR] support -std=gnu89

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/test/CIR/CodeGen/globals.c
This PR "adds" the support of extern vars in function body. Actually, I just erased an assert. Any reason it was there?
```
int foo() {
extern int optind;
return optind;
}
```
This is quite frequent bug in `llvm-test-suite`
=> [CIR][CodeGen] support extern var in function

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/switch.cir
This PR fixes lowering of the next code: 
```
void foo(int x, int y) {
switch (x) {
case 0: 
if (y) 
break;
break;
}
}
```
i.e. when some sub statement contains `break` as well. Previously, we did this trick for `loop`: process nested `break`/`continue` statements while `LoopOp` lowering if they don't belong to another  `LoopOp` or `SwitchOp`. This is why there is some refactoring here as well, but the idea is stiil the same: we need to process nested operations and emit branches to the proper blocks. 
This is quite frequent bug in `llvm-test-suite`
=> [CIR][Lowering][Bugfix] Lower nested breaks in switch statements

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/scope.cir
`ScopeOp` may end with `ReturnOp` instead of `YieldOp`, that is not expected now. This PR fix this. 
The reduced example is:
```
int foo() {
{
return 0;
}
}
```
This is quite frequent bug in `llvm-test-suite`
=> [CIR][Lowering][Bugfix] lower ScopeOp with return op

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, mlir/lib/Dialect/LLVMIR/IR/LLVMDialect.cpp
This PR fixes `CallOp` lowering and now we use different builders from `llvm IR` dialect  for direct and indirect calls
After variadic  calls were added in the `llvm IR` dialect, the  lowering of the dialect to the true LLVM IR  was slightly changed, hence we got several fails in tests recently after rebasing.  Actually, the bug was always there, and these changes just made it visible.
It turned out that one of the `mlir::LLVM::CallOp` builders  in the dialect is not supposed for using with indirect calls. My initial approach was to fix this builder  and infer the fact if the call is direct or indirect right there in order to simplify life of the dialect users (i.e. ours life in this case :) ). LLVM guys have some other thoughts though, and the only change they want to see is an assert …
=> Fix lowering of the callOp to llvm IR dialect

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/tenary.cir
This PR adds `cir.ternary` lowering. There are two approaches to lower `cir.ternary` imo:
1. Use `scf.if` op.
2. Use `cf.cond_br` op. 
I choose `scf.if`  because `scf.if` + canonicalization produces `arith.select` whereas `cf.cond_br` requires scf lifting. In many ways `scf.if` is more high-level and closer to `cir.ternary`.
A separate `cir.yield` lowering is required since we cannot directly replace `cir.yield` in the ternary op lowering -- the yield operands may still be illegal and doing so produces `builtin.unrealized_cast` ops. I couldn't figured out a way to solve this issue without adding a separate lowering pattern. Please let me know if you know a way to solve this issue.
=> [CIR][Lowering] add cir.ternary to scf.if lowering

clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/test/CIR/CodeGen/agg-copy.c
This PR fixes the next case 
```
typedef struct { } A;
A create() { A a; return a; }
void foo() {
A a;
a = create();
}
```
i.e. when a struct  is assigned to a function call result
=> [CIR][CodeGen] supports struct copy from function call result

GettingStarted/testing.md
In consistency with creating the comparison table,  the script use `clangir_$i.json`
=> [CIR][DOC] Rename clang_$i.json to clangir_$i.json

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/globals.cir
The error manifested in code like
```
int a[16];
int *const p = a;
void foo() {
p[0];
}
```
It's one the most frequent errors in current llvm-test-suite.
I've added the test to globals.cir which is currently XFAILed, I think @gitoleg will fix it soon.
=> [CIR][Lowering] Support lowering of cir.const with GlobalViewAttr (gh-352)

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/test/CIR/CodeGen/globals.c
This PR addresses #248 .
Currently string literals are always lowered to a `cir.const_array` attribute even if the string literal only contains null bytes. This patch make the CodeGen emits `cir.zero` for these string literals.
=> [CIR][CodeGen] emit cir.zero for constant string literals

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/comma.cpp
Currently, codegen of lvalue comma expression would crash:
```cpp
int &foo1();
int &foo2();
void c1() {
int &x = (foo1(), foo2());  // CRASH
}
```
This simple patch fixes this issue.
=> [CIR][CodeGen] codegen of lvalue comma expression

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/test/CIR/CodeGen/array-unknown-bound.cpp
Arrays can be first declared without a known bound, and then defined with a known bound. For example:
```cpp
extern int data[];
int test() { return data[1]; }
int data[3] {1, 2, 3};
```
Currently `clangir` crashes on generating CIR for this case. This is due to the type of the `data` definition being different from its declaration. This patch adds support for such a case.
=> [CIR][CodeGen] support array def after decl with unknown bound

clang/lib/CIR/Dialect/Transforms/MergeCleanups.cpp
Breaks the pass into smaller more manageable rewrites.
=> [CIR][Transforms][NFC] Refactor MergeCleanups pass

clang/lib/CIR/Dialect/Transforms/IdiomRecognizer.cpp, clang/lib/CIR/Dialect/Transforms/MergeCleanups.cpp
Some tests started failing under `-DLLVM_USE_SANITIZER=Address` due to trivial use-after-free errors.
=> [CIR][Transforms][Bugfix] Do not use-after-free in MergeCleanups and IdiomRecognizer.

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/int.cir, clang/test/CIR/IR/invalid.cir
When introducing attribute `#cir.int`, the constant type verification is not updated. If a `cir.const` operation produces an integral constant from a `#cir.int` attribute, the integer's type is not verified:
```mlir
%1 = cir.const(#cir.int<0> : !cir.int<s, 8>) : !cir.int<u, 8>
// Not verified: !cir.int<s, 8> differs from !cir.int<u, 8>
```
The corresponding test is also wrong but fail to be detected.
This patch fixes this issue.
=> [CIR] fix constant type verification

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/loop.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/loop.cir, clang/test/CIR/Lowering/loops-with-continue.cir
* #397
* #396
* #395
* __->__ #394
Detaches the representation of the C/C++ `continue` statement into a
separate operation. This simplifies mostly lowering and verifications
related to `continue` statements, as well as the definition and lowering
of the `cir.yield` operation.
A few checks regarding region terminators were also removed from the
lowering stage, since they are already enforced by MLIR.
=> [CIR][IR] Implement `cir.continue` operation

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/switch.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/loop.cir, clang/test/CIR/IR/switch.cir, clang/test/CIR/Lowering/loop.cir, clang/test/CIR/Lowering/loops-with-break.cir, clang/test/CIR/Lowering/switch.cir, clang/test/CIR/Transforms/merge-cleanups.cir
* #397
* #396
* __->__ #395
* #394
Same rationale as `cir.continue`, it detaches the representation of the
C/C++ `break` statement into a separate operation. This simplifies
lowering and verifications related to `break` statements, as well as the
definition and lowering of the `cir.yield` operation.
=> [CIR][IR] Implement `cir.break` operation

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenCoroutine.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/coro-task.cpp, clang/test/CIR/IR/await.cir, clang/test/CIR/IR/invalid.cir
* #397
* __->__ #396
* #395
* #394
This changes the `cir.await` operation to expect a `cir.condition` as
the terminator for the ready region. This simplifies the `cir.await`
while also simplifying the `cir.yield`. If `cir.condition` holds a
true value, then the `cir.await` will continue the coroutine, otherwise,
it will suspend its execution.
The `cir.condition` op was also updated to allow `cir.await` as its
parent operation.
=> [CIR][IR] Deprecate `cir.yield nosuspend`

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/switch.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/switch.cir, clang/test/CIR/Lowering/switch.cir, clang/test/CIR/Transforms/merge-cleanups.cir
* __->__ #397
* #396
* #395
* #394
Instead of having a `cir.yield fallthrough` operation, the default
branching behavior of the parent operation is denoted by `cir.yield`.
In other words, a `cir.yield` operation in a switch case region
represents the default branching behavior of the switch operation, which
is a fallthrough.
The `cir.yield` operation now represents the default branching behavior
of the parent operation's region. For example, in a if-else region, a
`cir.yield` operation represents a branch to the exit block.
=> [CIR][IR] Deprecate `cir.yield fallthrough`

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/test/CIR/CodeGen/wide-string.cpp
This commit supports the codegen of wide string literals, including `wchar_t` string literals, `char16_t` string literals, and `char32_t` string literals.
I'm not following the proposal in #374. The clang frontend doesn't record the literal string. It only records the encoded code units for wide string literals. So I believe that a dedicated string attribute with an encoding tag as described in #374 may not be that helpful as I thought.
=> [CIR][CodeGen] support wide string literals

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/CIRGenOpenMPRuntime.cpp, clang/lib/CIR/CodeGen/CIRGenOpenMPRuntime.h, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/CodeGen/CIRGenStmtOpenMP.cpp, clang/lib/CIR/CodeGen/CIRGenerator.cpp, clang/lib/CIR/CodeGen/CMakeLists.txt, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/lib/CIR/Lowering/DirectToLLVM/CMakeLists.txt, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/CIR/Lowering/ThroughMLIR/CMakeLists.txt, clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/CodeGen/openmp.cpp, clang/test/CIR/Lowering/openmp.cir, clang/tools/cir-opt/cir-opt.cpp
This patch introduces initial support for:
```
pragma omp parallel
```
This patch doesn't add support for any of the `parallel` clauses, including variable privatization; thus, all variables are handled as shared.
This PR fixes issue #285.
=> [CIR][OpenMP] Initial commit for OpenMP support in CIR

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
* #409
* #408
* #407
* __->__ #406
* #405
Leverages the new LoopOpInterface for lowering instead of the LoopOp
operation. This is a step towards removing the LoopOp operation.
=> [CIR][Lowering][NFC] Refactor LoopOp lowering

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/loop.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/IR/loop.cir, clang/test/CIR/IR/while.cir, clang/test/CIR/Lowering/loop.cir, clang/test/CIR/Lowering/loops-with-break.cir, clang/test/CIR/Lowering/loops-with-continue.cir
* #409
* __->__ #408
* #407
* #406
* #405
Creates a separate C/C++ operation for while loops, while keeping the
LoopOpInterface to generically handle loops. This simplifies the IR
generation and printing/parsing of while loops.
=> [CIR][IR] Refactor while loops

.github/workflows/clang-cir-tests.yml
=> [CIR] Move CI to CLANG_ENABLE_CIR

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/volatile.cpp, clang/test/CIR/Lowering/alloca.cir, clang/test/CIR/Lowering/loadstorealloca.cir
This patch adds a new `volatile` tag to the following operations to distinguish volatile loads and stores from normal loads and stores:
- `cir.load`
- `cir.store`
- `cir.get_bitfield`
- `cir.set_bitfield`
Besides, this patch also updates the CodeGen and LLVMIR lowering code to start emitting CIR and LLVMIR operations with volatile flag.
=> [CIR] add a new volatile flag to distinguish volatile accesses

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/vectype.cpp, clang/test/CIR/Lowering/cmp.cir, clang/test/CIR/Lowering/vectype.cpp
This is part 3 of implementing vector types and vector operations in ClangIR, issue #284.
Create new operation `cir.vec.cmp` which implements the relational comparison operators (`== != < > <= >=`) on vector types.  A new operation was created rather than reusing `cir.cmp` because the result is a vector of a signed intergral type, not a `bool`.
Add CodeGen and Lowering tests for vector comparisons.
Fix the floating-point comparison predicate when lowering to LLVM.  To handle NaN values correctly, the comparisons need to be ordered rather than unordered.  (Except for `!=`, which needs to be unordered.)  For example, "ueq" was changed to "oeq".
=> [CIR] Vector types, comparison operators

clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/test/CIR/CodeGen/agg-copy.c
Compilation of the following test
```
void foo6(A* a1) {
A a2 = (*a1);
}
```
fails with.
```
NYI
UNREACHABLE executed at /home/huawei/cir/repo/llvm-project/clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp:175!
```
Commit adds required visitor and fixes the issue.
=> [CIR][CIRGen] Add missing visitor for ParenExpr

clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/test/CIR/CodeGen/derived-to-base.cpp
In the original codegen a new type is created for the base class, while in CIR we were rewriting the type being processed (due tp misused pointers). This  PR fix this, and also makes CIR codegen even with the original one.
=> [CIR][CodeGen][BugFix] use proper base type for derived class

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenTypeCache.h, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h
This is a first PR for variable length array support. There are one (or more :) ) ahead. 
Basically,  we already did lot's of preliminary job in order to land VLA in CIR in #367 #346 #340. So now we add initial VLA support itself. 
Most of the changes are taken from the original codegen, so there is nothing to be scary of) 
I added just one test, and basically that's all we can test right now. Later, I will add more, from the original codegen tests.
=> [CIR][CodeGen] Initial variable length array support

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/const.cir
Compiling the given c-code
```
void foo() { 
int      i [2][1] = { { 1 }, { 0 } };
long int li[2][1] = { { 1 }, { 0 } };
float    fl[2][1] = { { 1 }, { 0 } };
double   d [2][1] = { { 1 }, { 0 } };
}
```
leads to compilation error
```
unknown element in ConstArrayAttr
UNREACHABLE executed at /home/huawei/cir/repo/van/llvm-project/clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp:951!
```
PR implements conversion the cir.zero attr to dense constant and fixed this error.
=> [CIR][Lowering] Support conversion of cir.zero to dense consts

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenCXXABI.h, clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/test/CIR/CodeGen/dynamic-cast.cpp
This PR introduces CIR CodeGen support for `dynamic_cast`.
The full feature set of `dynamic_cast` is not fully implemented in this PR as it's already pretty large. This PR only include support for downcasting and sidecasting a pointer or reference. `dynamic_cast<void *>` is not yet implemented.
=> [CIR][CodeGen] initial support for dynamic_cast

clang/lib/CIR/CodeGen/CIRGenCXXABI.h, clang/lib/CIR/CodeGen/CIRGenClass.cpp, clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/test/CIR/CodeGen/dynamic-cast.cpp
This patch adds CIRGen for downcasting a pointer to the complete object through `dynamic_cast<void *>`.
Together with #426 , the full functionality of `dynamic_cast` should be supported in CIRGen after this PR merges.
=> [CIR][CIRGen] Support dynamic_cast to void ptr

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/const-array.c, clang/test/CIR/Lowering/const.cir
This PR adds support for constant arrays with trailing zeros.
The original `CodeGen` does the following: once a constant array contain trailing zeros,  a struct with two members is generated: initialized elements and `zeroinitializer` for the remaining part. And depending on some conditions,  `memset` or `memcpy` are emitted.  In the latter case a global const array is created. 
Well, we may go this way, but it requires us to implement [features](https://github.com/llvm/clangir/blob/main/clang/lib/CIR/CodeGen/CIRGenDecl.cpp#L182) that are not implemented yet. 
Another option is to add one more parameter to the `constArrayAttr` and utilize it during the lowering.  So far I chose this way, but if you have any doubts, we can discuss here. So we just emit constant array as usually and once …
=> [CIR][CodeGen][Lowering] Supports arrays with trailing zeros

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
Originally, the location associated with a function is checked to be an `mlir::FileLineColLoc` before the function is lowered to an LLVMIR FuncOp. However, runtime function declarations do not have such locations. This patch further allows `mlir::UnknownLoc` to be associated with a function.
=> [CIR] allow mlir::UnknownLoc in function op

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/cast.cir
The minimal bug repro:
```
#include <stdbool.h>
#include <stdint.h>
void bar() {
bool x = true;
uint8_t y = (uint8_t)x;
}
```
Fails on verification stage:
```
loc("repro.c":5:24): error: integer width of the output type is smaller or equal to the integer width of the input type
fatal error: error in backend: The pass manager failed to lower CIR to LLVMIR dialect!
```
The problem is that in some cases lowering from CIR emits the invalid zext operation. PR fixes this issue by emitting the llvm.bitcast instead of llvm.zext in such cases.
=> [CIR][Lowering][Bugfix] Fix lowering of bool_to_int cast

clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/test/CIR/CodeGen/fun-ptr.c
The issue is that the CIR codegen assumes that function pointer is always result of cir.load op.
But it isn't true because the funcion pointer may be result of other operations (f.e cir.call).
=> [CIR][CIRGen][BugFix] Fix building of calls

clang/lib/CIR/CodeGen/CIRGenCstEmitter.h, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/test/CIR/CodeGen/compound-literal.c
This PR adds support for global compound literals. 
The implementation is almost the same as in original codegen. But the original codegen can reuse the value of emitted compound literal global variable in case then the init expression of new variable and this variable are the same.
It's easy to implement this feature. But I can't find any test-case then this feature will be applied. So I decided to ignore this optimization opportunity to avoid mistakes.
=> [CIR][CIRGen] Add codegen for global compound literals

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/test/CIR/CodeGen/vla.c
Here is the next step in VLA support.
Basically,  these changes handle different expressions, like `int (*a[5])[n]` or `sizeof(a[n])`.
I took tests from the original `codegen`  - they don't check anything, just verify we don't fail. 
There is still an issue with a proper cleanup - there are cases when `stack_save`  doesn't dominate a corresponded `stack_restore`. For example in the next example: 
```
void test(unsigned x) {
while (1) {
char a[x];
if (x > 5) 
break;
++x;
}
}
```
Look like `break` here doesn't  lead to `stack_restore`. But I would say this is less related to VLA, though probably I need to fix this as well. 
Btw, looks like somehow I didn't attach tests last time, my bad!
=> [CIR][CodeGen] VLA support next step

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/evaluate-expr.c
This PR fixes the issue connected with folding a simple boolean expresion pattern (f.e. `0 && RHS = 0`). 
The problem is that the scalar expression emitter always creates a `cir.bool` attribute as a result of expression. But in some cases the result expression should be a `cir.int` attr.
=> [CIR][CIRGen][Bugfix] Emit valid type for evaluated const

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/const-array.c
The change is taken from the original llvm codegen.
=> [CIR][CIRGen] Support for local const arrays

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/test/CIR/CodeGen/bitfields.c
The second part of  the job started in #412 , now about local structures.
As it was mentioned previously, sometimes the layout for structures with bit fields inited with constants differ from the originally created in `CIRRecordLayoutBuilder` and it cause `storeOp` verification fail due to different structure type was used to allocation.
This PR fix it.
An example:
```
int a : 4;
int b : 5;
int c;
} D;
void bar () {
D d = {1,2,3};  
}
```
Well, I can't say I'm proud of these changes - it seems like a type safety violation, but looks like it's the best we can do here.
The original codegen doesn't have this problem at all, there is just a `memcpy` there, I provide LLVM IR just for reference:
```
%struct.D = type { i16, i32 }
@__const.bar.d = private unnamed_addr constant { …
```
=> [CIR][CodeGen] Locally inited structures with bitfields

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/dynamic-cast.cpp, clang/test/CIR/CodeGen/unreachable.cpp, clang/test/CIR/IR/unreachable.cir, clang/test/CIR/Lowering/intrinsics.cir
In #426 we confirmed that CIR needs a `cir.unreachable` operation to mark unreachable program points [(discussion)](https://github.com/llvm/clangir/pull/426#discussion_r1472287368). This PR adds it.
=> [CIR] introduce cir.unreachable operation

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/evaluate-expr.c
This PR adds support for evaluating constants in member exprs.
The change is taken from original codegen.
=> [CIR][CIRGen] add missing case to VisitMemberExpr

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRAsm.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/asm.c
One more tiny step!
This a tiny PR that adds clobbers to constraint string. 
Note, that `~{dirflag},~{fpsr},~{flags}` is a [X86](https://github.com/llvm/clangir/blob/main/clang/lib/Basic/Targets/X86.h#L281) dependent clobbers.
Basically, the next things remain:
- lowering
- store the results of the `cir.asm`
=> [CIR][CodeGen] Adds clobbers to inline assembly

clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/test/CIR/CodeGen/array-init.c
As in original codegen this PR uses the do-while loop to initialize the array elements with the filler expression.
But unlike the original codegen we allocates the temporary variable on stack. Allocation is necessary to store the pointer to the first uniinitialized element.
=> [CIR][CIRGen] Support for zero initialization of arrays

clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/test/CIR/CodeGen/bitfields.c
This PR fixes a bug caused by `IntType` size limitations in CIR (and by some magic of numbers as well). 
As you know, we need to create a storage for bit fields that usually contain several of them. There next code fails with `IntType` size check which exceeds 64 bits.
```
uint8_t a;
uint8_t b;
uint8_t c;
int d: 2;
int e: 2;
int f: 4;
int g: 25;  
int h: 3;
int i: 4;  
int j: 3;
int k: 8;
int l: 14;
} D;
void foo() {
D d;	
} 
```
Note, if we remove first three fields (or even one) everything will be fine even without this fix, because [this](https://github.com/llvm/clangir/blob/main/clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp#L553) check won't pass. The bug is kind of hard to reproduce and I would say it's a rare case. I mean the problem is not only in the number of …
=> [CIR][CodeGen][Bugfix] fixes storage size for bitfields

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/bitfield-ops.c, clang/test/CIR/IR/invalid.cir
This PR fixes a couple of  NIY features for bit fields. 
Basically, such expressions with bit fields `x->a++` and `x->a |= 42`  are supported now.
The main problem is `UnOp` verification - now it can be defined both by `loadOp` and by `GetBitfieldOp` or even by `CastOp`. So shame on me, I removed a test from `invalid.cir`
=> [CIR][Codegen] Fixes bitfields unary and binary ops

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/agg-copy.c, clang/test/CIR/CodeGen/no-proto-fun-ptr.c, clang/test/CIR/CodeGen/no-prototype.c
CIR codegen always casts the no-proto function pointer to `FuncOp`. But the function pointer may be result of cir operations (f.e. `cir.load`). As a result in such cases the function pointer sets to `nullptr`. That leads to compilation error.
So this PR removes the unecessary cast to 'FuncOp' and resolves the issue.
=> [CIR][CIRGen] fix calling a function through a function pointer

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/IR/CIRTypes.h, clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenClass.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/CodeGen/pointer-to-data-member.cpp, clang/test/CIR/IR/data-member-ptr.cir, clang/test/CIR/IR/invalid.cir
This patch adds initial support for the pointer-to-data-member type. Specifically, this commit includes:
- New ops, types, and attributes:
- Add a new type `!cir.member_ptr`
- Add a new attribute `#cir.data_member_ptr`
- Add a new operation `cir.get_indirect_member`
- CodeGen for pointer-to-data-member types and values
- Lower C++ pointer-to-member type to `!cir.member_ptr`
- Lower C++ expression `&C::D` to `cir.const(#cir.data_member_ptr)`
- Lower C++ expression `c.*p` and `c->*p` to `cir.get_indirect_member`
This patch only includes an initial support. The following stuff related to pointer-to-member types are not supported yet:
- Pointer to member function;
- Conversion from `T Base::*` to `T Derived::*`;
- LLVMIR lowering.
Hopefully they will eventually be supported in later PRs :)
=> [CIR] initial support for pointer-to-data-member type

clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/lib/CIR/Dialect/IR/MissingFeatures.h, clang/lib/CIR/Dialect/IR/UnimplementedFeatureGuarding.h
As discussed in pull #401 , The present `UnimplementedFeature` class is made for the CIRGen submodule and we need similar facilities for code under `clang/lib/CIR/Dialect/IR`. This NFC patch adds a new `CIRDialectUnimplementedFeature` class that provides unimplemented feature guards for CIR dialect code.
=> [CIR][NFC] Add unimplemented feature guard for dialect code

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRAsm.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/asm.c, clang/test/CIR/Lowering/asm.cir
This PR adds lowering for `cir.asm`.
Also, two flags were added to the `cir.asm` : `hasSideEffects` and `isStackAligned` in order to match with the llvm dialect. 
Also, I added several simple tests for lowering.
I'm not sure but most likely the next PR will be the last one in this story about assembly support )
=> [CIR][Lowering]  cir.asm lowering

clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/test/CIR/CodeGen/implicit-return.cpp
This patch changes the emission of implicit returns from functions whose return type is not `void`. Instead of emitting `cir.return`, this PR aligns to the original clang CodeGen and emits a `cir.unreachable` operation.
Related issue: #457 .
=> [CIR][CIRGen] Emit `cir.unreachable` on implicit returns

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/vectype.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/vectype.cpp
This is part 4 of implementing vector types and vector operations in ClangIR, issue #284.  This change has three small additions.
Implement a "vector splat" conversion, which converts a scalar into vector, initializing all the elements of the vector with the scalar.
Implement incomplete initialization of a vector, where the number of explicit initializers is less than the number of elements in the vector. The rest of the elements are implicitly zero initialized.
Implement conversions between different vector types.  The language rules require that the two types be the same size (in bytes, not necessarily in the number of elements).  These conversions are always implemented with a bitcast.
The first two changes only required changes to the AST -> ClangIR code gen.  There are no changes to …
=> [CIR] Vector types - part 4

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/pred-info-builtins.c, clang/test/CIR/Lowering/expect.cir, clang/test/CIR/Lowering/if.cir, clang/test/CIR/Lowering/switch.cir
This PR adds the new `cir.expect` opcode which is similar to llvm.expect intricnsics. 
Codegen of  `__builtin_expect` emits `cir.expect` opcode. Then `cir.expect` will be lowered to `llvm.expect` intrinsic.
When implementing __builtin_expect I faced with minor issue.
CIR lowering of `if` often emits the lllvm IR with redundant cast instructions. Like this:
```
%0 = call i64 @llvm.expect.i64(i64 %any, i64 1), !dbg !13
%1 = icmp ne i64 %0, 0
%2 = zext i1 %0 to i8   // redundant
%3 = trunc i8 %1 to i1 // redundant
br i1 %3, label %l1, label %l2
```
But the llvm pass `LowerExpectIntrinsicPass` (that should replace `llvm.expect` with branch metadata) performs only simple pattern-matching. And it can't handle this zext/trunc intructions. So this pass in such cases just removes the `llvm.expect` …
=> [CIR][CIRGen] Support for __builtin_expect

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/offsetof.c
Support `offset` expression in case when we can evaluate offset expression as integer.
=> [CIR][CIRGen] Partial support for `offsetof`

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/implicit-return.cpp, clang/test/CIR/CodeGen/trap.cpp, clang/test/CIR/Lowering/intrinsics.cir
This PR adds the `cir.trap` operation, which corresponds to the `__builtin_trap` builtin function. When executed, the operation terminates the program abnormally in an implementation-defined manner.
This PR also includes CIRGen and LLVM lowering support for the new operation.
=> [CIR] Add `cir.trap` operation

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/vectype.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/vectype.cpp
Implement the vector version of the ternary (`?:`) operator.  This is a separate MLIR op than the regular `?:` operator because the vector version is not short-circuiting and always evaluates all its arguments.
=> [CIR] Vector ternary operator

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/bit.cir
This PR adds the LLVMIR lowering support for CIR bit operations.
For `cir.bit.clz`, `cir.bit.ctz`, and `cir.bit.popcount`, they can be lowered directly to LLVM intrinsic calls to `@llvm.ctlz`, `@llvm.cttz`, and `@llvm.ctpop`, respectively.
For the other three bit operations, namely `cir.bit.clrsb`, `cir.bit.ffs`, and `cir.bit.parity`, they are lowered to a sequence of LLVM IR instructions that implements their functionalities. This lowering scheme is also used by the original clang CodeGen.
=> [CIR][Lowering] Add LLVMIR lowering support for CIR bit operations

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/inc-bool.cpp
CIRGenFunction::buildFromMemory can handle the `cir.bool` values. So we no longer need to emit the `NIY` error here.
=> [CIR][CIRGen] Enable support of bool increment

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/Address.h, clang/lib/CIR/CodeGen/CIRAsm.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/asm.c, clang/test/CIR/Lowering/asm.cir
This is the next step in inline assembly support and it's more like a service PR and mostly dedicated to the in/out argument types.
Also, operand attributes are added and it's the last change in the `cir.asm` operation afaik. But I would wait untill the next PR,
which will contain more examples and maybe will help us to get more readable format for the operation.
Note, that we have to add an attribute for each operand  - because the lowering of the llvm dialect to LLVM IR iterates over them in the same order.
The next PR will be last one (so far) in the series of PRs dedicated to the inline assembly support. It will add storing of the results.
=> [CIR][CodeGen] Inline assembler: service PR before the result obtaining

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/vectype.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/vectype.cpp
Three small changes, all cleanup or refactoring in nature.
1. Fix the assemblyFormat for all the vector operations in the ClangIR dialect so that vector types appear in ClangIR as `!cir.vector<type x n>` instead of as just `<type x n>`. When I first created the vector ops, I forgot to use `qualified` as necessary when writing out types. This change fixes that. There is no change in behavior, but there is a change to the text version of ClangIR, which required changing the ClangIR expected results and ClangIR inputs in the tests.
2. Create a new `cir.vec.splat` operation and use that for "vector splat", i.e. a conversion from a scalar to a vector. A "vector splat" conversion had been implemented with `cir.vec.create` before. This change results in different ClangIR and different LLVM IR, …
=> [CIR] Vector type cleanup and refactoring

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/test/CIR/CodeGen/union-init.c
PR adds support for initialization of unions. The change is copy-pasted from the original CodeGen.
=> [CIR][CIRGen] Support for initialization of unions.

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/builtin-prefetch.c
This PR adds support for `__builtin_prefetch`. CIRGen of this builtin emits the new 'cir.prefetch' opcode. Then `cir.prefetch` lowers to `llvm.prefetch` intrinsic.
=> [CIR][CIRGen] Support for __builtin_prefetch

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
This PR adds MemRead/MemWrite  markers to the `GetBitfieldOp` and `SetBitfieldOp` (as discussed in #487)
Also, minor renaming in the `SetBitfieldOp`
=> [CIR] adds MemRead/MemWrite markers to bitfield ops

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/builtin-constant-p.c
This PR adds support for `__builtin_constant_p`.
Implementation introduces the new `cr.is_constant` opcode to it during the codegeneration of builtin.
Codegeneration is taken from the original llvm codegen.
=> [CIR][CIRGen] Support for __builtin_constant_p

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/Inputs/std-compare.h, clang/test/CIR/CodeGen/three-way-comparison.cpp
This patch adds CIRGen support for the C++20 three-way comparison operator `<=>`. The binary operator is directly lowered to existing CIR operations.
Most of the changes are tests.
=> [CIR][CIRGen] Support for C++20 three-way comparison

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/compound-literal.c
This change is taken from the original codegen.
=> [CIR][CIRGen] Support for compound literal lvalue

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/gnu-extension.c
This change is taken from the original codegen
=> [CIR][CIRGen] Add handling __extension__ keyword for lvalue

clang/include/clang/CIR/CIRToCIRPasses.h, clang/include/clang/CIR/Dialect/Passes.h, clang/include/clang/CIR/Dialect/Passes.td, clang/include/clang/CIR/Passes.h, clang/include/clang/CIRFrontendAction/CIRGenAction.h, clang/include/clang/Driver/Options.td, clang/include/clang/Driver/Types.def, clang/include/clang/Frontend/FrontendOptions.h, clang/lib/CIR/CodeGen/CIRPasses.cpp, clang/lib/CIR/Dialect/Transforms/CIRFlattening.cpp, clang/lib/CIR/Dialect/Transforms/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp, clang/lib/CIR/Dialect/Transforms/StructuredCFG.cpp, clang/lib/CIR/FrontendAction/CIRGenAction.cpp, clang/lib/CIR/Lowering/DirectToLLVM/CMakeLists.txt, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/Driver/Driver.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/lib/Frontend/CompilerInvocation.cpp, clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp, clang/test/CIR/mlirprint.c, clang/tools/cir-opt/cir-opt.cpp
We start our journey towards `goto` support and this is a first step on this way.
There are some discussion in #508  and according to the plan we do the following here:
1) a new pass called `StructuredCFG`  that is a stub now but later will be responsible for the regions inlining. The pass works only if `emit-cir` is not passed in cmd line. Thus, the clang behavior  is not changed here from the user's point of view.
2)  The pass will be accomplished with `goto` solver later, so we talk about several passes that are mandatory for the lowering into `llvm` dialect. There are at least two clients of this pass that will be affected: `clang` itself and `cir-opt`, so we need a common point for them: and `populateCIRFlatteningPasses` and `populateCIRToLLVMPasses` guarantee that `CIR` will be in …
=> [CIR] Introduce a flattening pass

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/vectype.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/vectype.cpp
Implement `__builtin_shufflevector` and `__builtin_convertvector` in ClangIR.  This change contributes to the implemention of issue #284.
`__builtin_convertvector` is implemented as a cast.  LLVM IR uses the same instructions for arithmetic conversions of both individual scalars and entire vectors.  So ClangIR does the same.  The code for handling conversions, in both CodeGen and Lowering, is cleaned up to correctly handle vector types.  To simplify the lowering code and avoid `if (type.isa<VectorType>())` statements everywhere, the utility function `elementTypeIfVector` was added to `LowerToLLVM.cpp`.
`__builtin_shufflevector` has two forms, only one of which appears to be documented.
The documented form, which takes a variable-sized list of integer constants for the indices, is …
=> [CIR] shufflevector and convertvector built-ins

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/bswap.cpp, clang/test/CIR/Lowering/bswap.cir
This PR adds support for the following intrinsic functions:
- `__builtin_bswap{16, 32, 64}`
- `_byteswap_{ushort, ulong, uint64}`
This PR adds a new `cir.bswap` operation to represent such an intrinsic call. CIRGen and LLVMIR lowering for the new operation is included in this PR.
=> [CIR] Add support for byteswap intrinsic

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h
This is the final commit for issue #284.  Vector types other than GNU vector types will be covered by other yet-to-be-created issues.
Now that GNU vector types (the ones defined via the vector_size attribute) are implemented, do a final cleanup of the assertions and other checks related to vector types.
Remove `UnimplementedFeature::cirVectorType()`.  Deal with the remaining calls to that function.  When the that is not yet implemented has to do with Arm SVE vectors, the assert was changed to `UnimplementedFeature::scalableVectors()` instead.  The assertion was removed in cases where the code correctly handle GNU vector types.
While cleaning up the assertion checks, I noticed that BinOp handling of vector types wasn't quite complete.  Any special handling for integer or floating-point …
=> [CIR] GNU vector type cleanup

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/test/CIR/CodeGen/builtin-bits.cpp
This patch adds the CIRGen for the following builtin functions:
- `__builtin_clzg`;
- `__builtin_ctzg`;
- `__builtin_popcountg`.
CIRGen for these three functions are missing in the original PR which introduces CIR bit ops.
=> [CIR][CIRGen] Add missing CIRGen for generic bit operation builtins

clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/if.cir, clang/test/CIR/mlirprint.c, clang/tools/cir-opt/cir-opt.cpp
This PR perform flattening for `cir::IfOp` 
Basically, we just move the code from `LowerToLLVM.cpp` to `FlattenCFG.cpp`.
There are several important things though I would like to highlight.
1) Consider the next code from the tests:
```
cir.func @foo(%arg0: !s32i) -> !s32i {
%4 = cir.cast(int_to_bool, %arg0 : !s32i), !cir.bool
cir.if %4 {
%5 = cir.const(#cir.int<1> : !s32i) : !s32i
cir.return %5 : !s32i
} else {
%5 = cir.const(#cir.int<0> : !s32i) : !s32i
cir.return %5 : !s32i
}
cir.return %arg0 : !s32i
}
```
The last `cir.return` becomes unreachable after flattening and hence is not reachable in the lowering. So we got the next error:
```
error: 'cir.return' op expects parent op to be one of 'cir.func, cir.scope, cir.if, cir.switch, cir.do, cir.while, cir.for'
cir.return %arg0 : !s32i
``` …
=> [CIR][Codegen] IfOp flattening

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/CodeGen/bitint.c, clang/test/CIR/CodeGen/bitint.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/bitint.cir
This PR adds initial support for the bit-precise integer type `_BitInt(N)`. This type goes into the C23 standard, and has already been supported by clang since 2020, previously known as `_ExtInt(N)`.
This PR is quite simple and straight-forward. Basically it leverages the existing `cir.int` type to represent such types. Previously `cir.int` verifies that its width must be a multiple of 8, and this verification has been removed in this PR.
=> [CIR] Add initial support for bit-precise integer types

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRAsm.cpp, clang/lib/CIR/CodeGen/TargetInfo.h, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/asm.c, clang/test/CIR/Lowering/asm.cir
This PR adds storing of the results of inline assembly operation. 
This is a **final** step (I hope: ) ) from my side to support inline assembly.
There are some features that remains unimplemented, but basic things should work now, For example, we can do addition and get the results - I explicitly added several tests for that, so you can test them in real.
For instance, the next program being compiled with CIR should give you 7 as the result:
```
int add(int x, int y) {  
int a;
__asm__("addl %[y], %[x]"
: "=r" (a)
: [x] "r" (x), 
[y] "r" (y)
);
return a;
}
int main() {
printf("run %d\n", add(3, 4));
return 0;
}
```
So, the main thing remains is pretty printing. As I said I added several examples, and may be it will become more clear how to print better.
Also, I added several tests from …
=> [CIR][CodeGen] Inline assembly: store the results

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/binop.cpp, clang/test/CIR/CodeGen/call.cpp, clang/test/CIR/CodeGen/int-wrap.c, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/int-wrap.cir
This PR fixes some cases when a program compiled with `-fwrapv` fails with `NYI` . 
Basically, the default behavior  is no overlap: 
```
void baz(int x, int y) {
int z = x - y;
}
```
LLVM IR (no CIR enabled):
```
%sub = sub nsw i32 %0, %1
```
and with `-fwrapv` :
```
%sub = sub i32 %0, %1
```
We need something similar in CIR. The only way I see how to implement it is to add a couple of attributes to the `BinOp` to make things even with the llvm dialect.
Well, are there any other ideas?
=> [CIR][CodeGen][Lowering] Support Integer overflow with fwrap

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenCXXABI.h, clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/MissingFeatures.h, clang/lib/CIR/Dialect/Transforms/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepareCXXABI.h, clang/lib/CIR/Dialect/Transforms/LoweringPrepareItaniumCXXABI.cpp, clang/test/CIR/CodeGen/dynamic-cast.cpp, clang/test/CIR/IR/invalid.cir
This PR adds the `cir.dyn_cast` operation for representing `dynamic_cast` in C++. It contains the following contents:
~This is a draft PR. Now I only added the new operation / attributes, and updated the CIRGen part. The LoweringPrepare for the new operation is not implemented. Hopefully the draft can get some initial feedbacks from the community and make sure it is on the right direction so we don't waste time on wrong things.~
Related issue: #470 .
=> [CIR] Add `cir.dyn_cast` operation

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenTypeCache.h, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/builtin-floating-point.c, clang/test/CIR/CodeGen/types.c, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/float.cir
This PR adds support for the `long double` type in C/C++. It includes a new CIR type `!cir.long_double` to represent the `long double` type. CIRGen and LLVMIR lowering support for the new type is also added.
Since the underlying floating point format used by a `long double` value is implementation-defined, the `!cir.long_double` type is parameterized to include information about the underlying floating point format. Specifically, a `long double` value may have one of the following formats:
1) IEEE-754 binary64 format (i.e. the same format used by `double`);
2) x87 80-bit floating point format;
3) IEEE-754 binary128 format;
4) PowerPC double double format.
This PR invents 3 more CIR types to represent the above floating-point formats, and `!cir.long_double` is parameterized by another CIR …
=> [CIR] Add support for long double type

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenTypeCache.h, clang/lib/CIR/CodeGen/TargetInfo.h, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h
ASTAllocaAddressSpace is a target-specific definition specificed by the codegen target info.
In this commit, initial support is introduced which asserts that only the default (no qualifier) address space is supported.
=> [CIR][CIRGen] Introduce initial support for ASTAllocaAddressSpace

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/switch.cir
This PR adds flattening for `SwitchOp`. Despite of the previous PRs, here we have to introduce an operation for the flattening, since later we'll need to create `llvm.switch` in the lowering.
So `cir.flat.switch`  is a  new operation, which barely copied from the dialect.  I added several tests as well.
=> [CIR][CodeGen] Adds SwitchOp flattening

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/builtin-alloca.c, clang/test/CIR/CodeGen/builtin-ms-alloca.c
This patch adds the CIRGen for the following builtin functions:
- `alloca`;
- `_alloca`;
- `__builtin_alloca`;
- `__builtin_alloca_uninitialized`.
Missing support to add in the future:
- Non-default auto initialization setting. The default is to not initialize the allocated buffer, which is simpler to implement. This commit is leaving the skeleton to implement this feature following clang's codegen pattern.
- It may be possible that the frontend has set non-default address space for the alloca's return value. This is the case for OpenCL or AMDGPU codes for example. This is handled in clang codegen via address space cast, and is left for future implementation. This commit introduces a guard-rail around this behaviour.
----------------
P.S.:
I'm aware this is rather an "esoteric" feature to …
=> [CIR][CIRGen] Add dynamic builtin alloca intrinsics support

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/bswap.cir, clang/test/CIR/Lowering/intrinsics.cir
This PR does not introduce any functional changes. It cleans up code in `LowerToLLVM.cpp` and creates all LLVM intrinsic calls through the unified `createCallLLVMIntrinsicOp` function, as suggested by [this comment](https://github.com/llvm/clangir/pull/556#discussion_r1575198259) in #556 .
Some LLVM intrinsics already have specialized LLVMIR operations. CIR operations that depend on these intrinsics are lowered to those specialized operations rather than `llvm.call_intrinsic` operation.
=> [CIR][NFC] Create LLVM intrinsic calls through `createCallLLVMIntrinsicOp`

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/cos.cir
#563 This PR add cir.cos lowering to MLIR math dialect, now it only surpport single and double float types, I add an assertation for the long double and other unimplemented types
=> [CIR][Lowering] Add MLIR lowering support for CIR cos operations

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/invalid.cir
ASMParser::parseAttribute is responsible for emitting its own errors or forwarding errors of the parsers below it. There is no reason to emit a subsequent error as it doesn't add extra information to the user.
As a driveby, beutify a bit the tests that "relied" on this error and make the expected error easier to read by moving it to the line before.
=> [CIR] Remove redundant error from parseConstantValue

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/global.cir
This commit introduce CIRGlobalOpLowering and CIRGetGlobalOpLowering for lowering to memref.
=> [CIR] Support lowering GlobalOp and GetGlobalOp to memref

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/cast.cir
This commit introduce CIRCastOpLowering for lowering to arith.
=> [CIR][ThroughMLIR] Support lowering CastOp to arith

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/coro-task.cpp, clang/test/CIR/CodeGen/lambda.cpp
Do not print in cir.func definition the 'attr { ... }' with coroutine or lambda attributes since they are already printed before the function name. Otherwise redundancy breaks a future parsing. Sort the attributes to be skipped so it is more obvious to see the list of attributes.
Improve the tests to check there are no spurious attributes anymore.
=> [CIR][Asm] Remove duplicated lambda & coroutine attributes

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/builtins-overflow.cpp, clang/test/CIR/Lowering/binop-overflow.cir
This patch adds support for checked arithmetic builtins, including:
- `__builtin_add_overflow` and `__builtin_{s|u}add{|l|ll}_overflow`;
- `__builtin_sub_overflow` and `__builtin_{s|u}sub{|l|ll}_overflow`;
- `__builtin_mul_overflow` and `__builtin_{s|u}mul{|l|ll}_overflow`.
This patch adds a new operation `cir.checked_arith` to represent these builtins. Unlike other CIR operations, this new operation has two result values. One for the possibly truncated result, and the other for a boolean flag that indicates whether the operation has overflowed.
CIRGen and LLVMIR lowering support for the new operation is both included in this PR.
=> [CIR][CIRGen][LLVMLowering] Add support for checked arithmetic builtins

clang/test/CIR/IR/data-member-ptr.cir
As suggested in #401, this PR removes the `get_global_member` test in `CIR/IR/data-member-ptr.cir` as it is redundant.
The original comment: https://github.com/llvm/clangir/pull/401#discussion_r1589952990
=> [CIR][NFC] remove redundant test in CIR/IR/data-member-ptr.cir

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/ptrstride.cir
This commit introduce CIRPtrStrideOpLowering to lower the following pattern to memref load or store.
Rewrite
%0 = cir.cast(array_to_ptrdecay, %base)
%1 = cir.ptr_stride(%0, %index)
cir.load %1
To
memref.load %base[%index]
=> [CIR][ThroughMLIR] Support lowering ptrStrideOp with loadOp or storeOp to memref

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/Passes.h, clang/include/clang/CIR/Dialect/Passes.td, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/CodeGen/CIRPasses.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp, clang/lib/CIR/Dialect/Transforms/GotoSolver.cpp, clang/lib/CIR/Dialect/Transforms/MergeCleanups.cpp, clang/test/CIR/CodeGen/goto.cpp, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/goto.cir, clang/test/CIR/Lowering/region-simplify.cir
This PR:
1) adds new operations: `GotoOp` and `LabelOp` and inserts them in the codegen 
2) adds a pass that replaces `goto` operations with branches to the corresponded blocks (and erases `LabelOp` from CIR)
3) adds an attribute for `FuncOp` to track which functions should be processed by the pass
4) adds several tests for goto-s
=> [CIR][CodeGen] Goto pass

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/pointer-arith-ext.c
Same as void pointers `void *`, we treat function pointer arithmetic as `GEP i8`, according to the original behavior of clang ([godbolt](https://godbolt.org/z/EMdvfdTe7)).
It's a part of #579, since I would like to split it to two tasks:
- **support pointer arithmetic for function types (this PR)**
- support to dereference void pointer (#595)
=> [CIR][LowerToLLVM] Support pointer arithmetic for function types

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenTypeCache.h, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/CodeGen/bf16-ops.c, clang/test/CIR/CodeGen/fp16-ops.c
This PR adds two new CIR floating-point types, namely `!cir.f16` and `!cir.bf16`, to represent the float16 format and bfloat format, respectively.
This PR converts the clang extension type `_Float16` to `!cir.f16`, and converts the clang extension type `__bf16` type to `!cir.bf16`. The type conversion for clang extension type `__fp16` is not included in this PR since it requires additional work during CIRGen.
Only CIRGen is implemented here, LLVMIR lowering / MLIR lowering should come next.
=> [CIR][CIRGen] Add CIRGen support for float16 and bfloat

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/func.cir
This patch ensures that only the pretty-print version of function param and result attributes is printed. The tailing dictionary attributes are no longer printed.
It also ensures some FuncOp tests are properly validating both parsing and printing.
=> [CIR][IR] Fix FuncOp duplicate attr printing

clang/test/CIR/CodeGen/ctor-member-lvalue-to-rvalue.cpp
Seems the FIXME has been solved since I've confirmed that these CHECK can pass now. 
So I removed the FIXME and recovered these CHECK.
=> [NFC][CIR] Complete CIR check in test case ctor-member-lvalue-to-rvalue

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/vectype.cpp, clang/test/CIR/Lowering/vectype.cpp
There is [a code path](https://github.com/llvm/clangir/blob/3da10fafac66ff125fb59c602e41ad4b4f5cb382/clang/lib/CodeGen/CGExpr.cpp#L2190) missing the counterpart in CIRGen of vector types. When using compound assignments like `a[0] += a[1]`, this code path is activated and end up with NYI.
=> [CIR][CIRGen] Fix compound assignment for vector types

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.cpp, clang/lib/CIR/CodeGen/ConstantInitBuilder.h, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Dialect/Transforms/LibOpt.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/constptr.c, clang/test/CIR/CodeGen/vbase.cpp, clang/test/CIR/IR/constptrattr.cir, clang/test/CIR/Lowering/types.cir
The constant initialization isn't related to the pointee. We should be able to write #cir.ptr<-1 ： i64> : !cir.ptr<whatever>
=> [CIR][CIRGen] Support for signed #cir.ptr

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/address-space.c, clang/test/CIR/IR/address-space.cir, clang/test/CIR/Lowering/address-space.cir
This is the prelude of address space support. Linked issue: #418 .
I want to solve it by these steps:
1. This PR, add the attribute and implement asm format & type conversion.
2. Enable the feature flag of address space, but break it into several other flags. And re-categorize / fix occurrences in the codebase. There is already [a draft commit for this part](https://github.com/seven-mile/clangir/commit/d6752161b23f7872a7999219137a9dd241fe8fa5). PR coming soon.
* The proposed new feature flags are: `addressSpaceCasting` and (existing) `addressSpaceInGlobalVar`
3. Implement `clang::CK_AddressSpaceConversion` as a new kind of `cir.cast`. Also fix the corresponding occurrences.
4. Make ops like `cir.global` and `cir.get_global` aware of address space, and solve the latter flag.
5. Relax the …
=> [CIR][CIRGen][LowerToLLVM] Add address space attribute for pointer type

clang/lib/CIR/CodeGen/CIRGenClass.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/multi-vtable.cpp, clang/test/CIR/IR/constptrattr.cir, clang/test/CIR/Lowering/ThroughMLIR/vtable.cir
This PR adds Vtable support for C++ multiple inheritance without thunk. This change contains the CIR codegen and lowering work:
1. `VTableAttr` should allow adding multiple `ArrayAttr` for multi-inheritance.
3. `VTableAddrPointOpLowering` has been fixed for the multi-vtable during the MLIR lowering phase.
Example:
```c++
class Mother {
virtual void MotherFoo() {}
virtual void MotherFoo2() {}
}
class Father {
virtual void FatherFoo() {}
}
class Child : public Mother, public Father {
void MotherFoo() override {}
}
```
```mlir
cir.global linkonce_odr @_ZTV5Child = #cir.vtable<
{#cir.const_array<[
#cir.ptr<null> :  #!cir.ptr<!u8i>,
#cir.global_view<@_ZTI5Child> : !cir.ptr<!u8i>,
#cir.global_view<@_ZN5Child9MotherFooEv> : !cir.ptr<!u8i>,
#cir.global_view<@_ZN6Mother10MotherFoo2Ev> : …
```
=> [CIR][CIRGen][LLVMLowering] Vtable support for simple multiple inhertance without thunk

clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/test/CIR/CodeGen/switch-gnurange.cpp, clang/test/CIR/CodeGen/switch.cpp
=> [CIR][CIRGen] Add support for gnu range on switch stmts

clang/include/clang/CIR/Dialect/IR/CIRDataLayout.h, clang/lib/CIR/CodeGen/CIRGenAtomic.cpp, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/lib/CIR/CodeGen/CIRGenException.cpp, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp
Move it up for visibility, just like the other dialect headers.
=> [CIR] Move CIRDataLayout.h into include/clang/CIR/Dialect/IR

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/structural-binding.cpp
In this PR I added the support for structural bindings in CIR codegen, to reason `DecompositionDecl` and `BindDecl` properly.
Note that since `ArrayInitLoopExpr` is not implemented so binding to arrays is not supported yet. I'll look into it later : )
=> [CIR][CIRGen] Support CodeGen for structural bindings

clang/include/clang/CIR/LowerToMLIR.h, clang/lib/CIR/Lowering/ThroughMLIR/CMakeLists.txt, clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRLoopToSCF.cpp, clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/for.cir
This commit introduces CIRForOpLowering for lowering to scf.
The initial commit only support increment loop with lt or le comparison.
=> [CIR][ThroughMLIR] Support lowering ForOp to scf

Dialect/cir-style-guide.md
This PR adds documentation for CIR assembly style guide. Follows #583 .
=> [CIR][doc] Add CIR assembly style guide

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/agg-copy.c
This PR fixes a fail on `llvm_unreachable`  for the next case:
``` 
volatile A vol_a;
A foo7() {
return vol_a;
}
```
Basically, it's just a copy-pasta from the original `code-gen`. 
Also, I added the `isVolatile` attribute for the `cit.copy` operation
=> [CIR][CodeGen][Bugfix] fixes volatile structs copy

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/store.c
This PR fixes the next bug showed in the example below:
```
typedef int (*fn_t)();
int get42() { return 42; }
void foo() {
fn_t f = get42;
}
```
The function type `fn_t`  is generated as the variadic one due to no arg types listed, this is the `codegen` feature. And once we store the function pointer to a real function - a pointer to `get42` here has the expected `i32 ()*` type - we get a verification error, so `bitcast` is needed. The original `codegen` doesn't have it because of opaque pointers used, and had the `bitcast` earlier, long time ago:
```
%f = alloca i32 (...)*
store i32 (...)* bitcast (i32 ()* @get42 to i32 (...)*), i32 (...)** %f
```
=> [CIR][CodeGen][Bugfix] store fptr of a function with no args

clang/include/clang/CIR/CIRToCIRPasses.h, clang/include/clang/CIR/Dialect/Passes.h, clang/include/clang/CIR/Dialect/Passes.td, clang/lib/CIR/CodeGen/CIRPasses.cpp, clang/lib/CIR/Dialect/Transforms/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/SCFPrepare.cpp, clang/lib/CIR/FrontendAction/CIRGenAction.cpp, clang/test/CIR/Transforms/scf-prepare.cir, clang/test/CIR/mlirprint.c, clang/tools/cir-opt/cir-opt.cpp
This commit introduces SCFPreparePass to
1) Canonicalize IV to LHS of loop comparison
For example, transfer  `cir.cmp(gt, %bound, %IV)` to `cir.cmp(lt, %IV, %bound)`. So we could use RHS as boundary and use `lt` to determine it's an upper bound.
2) Hoist loop invariant operations in condition block out of loop.
The condition block may be generated as following which contains the operations produced upper bound.
SCF for loop required loop boundary as input operands. So we might need to hoist the boundary operations out of loop.
```
cir.for : cond {
%4 = cir.load %2 : !cir.ptr<!s32i>, !s32i
%5 = cir.const #cir.int<100> : !s32i       <- upper bound
%6 = cir.cmp(lt, %4, %5) : !s32i, !s32i
%7 = cir.cast(int_to_bool, %6 : !s32i), !cir.boo
cir.condition(%7
} body {
```
=> [CIR] Add -cir-mlir-scf-prepare to simplify lowering to SCF

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenCoroutine.cpp, clang/lib/CIR/Dialect/Transforms/IdiomRecognizer.cpp, clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepareItaniumCXXABI.cpp
One of the builders was adding a retun value to the CallOp when given a void return type. The expected behavior is to not add a return value. Two other minor fixes were added to the return value: its constraint was replaced from variadic to optional and it was assigned a name. This prevents function calls with multiple returns and facilitates access to the single return value, respectively.
=> [CIR][IR][NFC] Fix CallOp builder with void return

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/lib/CIR/Dialect/IR/MissingFeatures.h, clang/lib/CIR/Dialect/Transforms/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepareAArch64CXXABI.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepareCXXABI.h, clang/lib/CIR/Dialect/Transforms/LoweringPrepareItaniumCXXABI.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepareItaniumCXXABI.h, clang/test/CIR/CodeGen/var-arg-float.c, clang/test/CIR/CodeGen/var-arg.c, clang/test/CIR/CodeGen/variadics.c
lowering var_arg op for ARM64 architecture. This is CIR lowering.
This PR modified LoweringPrepare CXXABI code to make LoweringPrepareArm64CXXABI class inherit more generic LoweringPrepareItaniumCXXABI, this way lowering var_arg would be only meaningful for arm64 targets and for other arch its no op for now.
The ABI doc and detailed algorithm description can be found in this official doc.
[](https://github.com/ARM-software/abi-aa/blob/617079d8a0d45bec83d351974849483cf0cc66d5/aapcs64/aapcs64.rst#appendix-variable-argument-lists)
The following pic is a easier-to-understand and close to lowered code explanation
=> [CIR][LowerToLLVM][CXXABI] Lower cir.va.arg

clang/test/CIR/Lowering/ThroughMLIR/for.cir
With C source code, we would able to update the CIR tests when needed.
=> [CIR] Add C source code as comments in for.cir unit test

clang/include/clang/CIR/CIRToCIRPasses.h, clang/include/clang/CIR/Dialect/Passes.h, clang/include/clang/CIR/Dialect/Passes.td, clang/include/clang/Driver/Options.td, clang/include/clang/Frontend/FrontendOptions.h, clang/lib/CIR/CodeGen/CIRPasses.cpp, clang/lib/CIR/Dialect/Transforms/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/CallConvLowering.cpp, clang/lib/CIR/FrontendAction/CIRGenAction.cpp, clang/lib/Driver/ToolChains/Clang.cpp, clang/lib/Frontend/CompilerInvocation.cpp, clang/test/CIR/Transforms/Target/x86/x86-call-conv-lowering-pass.cpp
This patch adds a new CallConvLowering pass that aims to lower the calling conventions of the functions in the module. It also includes a new Clang command line option to enable it. Also, it is considered a part of the lowering prepare set of passes, as it is unlikely to be used elsewhere in the pipeline.
Since this will be dealing with ABI/Target-specific information, it requires AST info. For this reason, it can only be executed through the clang driver or cc1 tool for now as CIR does not encode AST info.
This pass is disabled by default and can be enabled by passing the flag `-fclangir-call-conv-lowering`. Once this pass is more mature, it should be enabled by default as a required step to lower to LLVM Dialect.
=> [CIR][Passes] Add CallConvLowering pass skeleton

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/builtin-floating-point.c, clang/test/CIR/Lowering/builtin-binary-fp2fp.c
This PR adds the following operations for the builtin binary fp2fp functions:
- `cir.copysign` for `__builtin_copysign`;
- `cir.fmax` for `__builtin_fmax`;
- `cir.fmin` for `__builtin_fmin`;
- `cir.fmod` for `__builtin_fmod`;
- `cir.pow` for `__builtin_pow`.
This PR also includes CIRGen support for these new operations.
=> [CIR][CIRGen] Add CIRGen for binary fp2fp builtin operations

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Interfaces/CIROpInterfaces.td, clang/lib/CIR/CodeGen/CIRGenCXX.cpp, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp
CIRGlobalValueInterface inherits from mlir::Symbol as it should, and GlobalOp and FuncOp now has interface mlir::Symbol through CIRGlobalValueInterface
and this PR basically make function isDeclarationForLinker into the CIRGlobalValueInterface interface. We also change some call sites of isDeclaration to use CIRGlobalValueInterface when its appropriate.
=> [CIR][Interface] introduce CIRGlobalValueInterface for GlobalOp and FuncOp

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp, clang/test/CIR/CodeGen/switch-gnurange.cpp, clang/test/CIR/Transforms/switch.cir
Make lowering result of case range smart.
Resolve #632
=> [CIR] Add Case Op Kind Range

clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/builtin-floating-point.c
This patch adds LLVM lowering support for unary fp2fp builtins.
Those builtins that should be lowered to runtime function calls are lowered to such calls during lowering prepare. Other builtins are lowered to LLVM intrinsic calls during LLVM lowering.
=> [CIR][LLVMLowering] Add LLVM lowering for unary fp2fp builtins

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenValue.h, clang/test/CIR/CodeGen/vectype-ext.cpp
Resolve #532 .
Support CIRGen of `ExtVectorElementExpr` that includes swizzle `v.xyx` and subscription `v.s0`.
=> [CIR][CIRGen] Support OpenCL Vector Types

clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/test/CIR/CodeGen/goto.cpp, clang/test/CIR/CodeGen/loop.cpp, clang/test/CIR/CodeGen/return.cpp, clang/test/CIR/CodeGen/switch-unreachable-after-break.cpp, clang/test/CIR/CodeGen/switch.cpp
Without this patch, CIR CodeGen continue to generate in the same block after `cir.break` and `cir.continue`, which would cause verification error because `cir.break` and `cir.continue` should appear at the end of blocks.
This patch creates a new dangling block after generating `cir.break` and `cir.continue` to fix the issue.
This will fix #323.
=> [CIR][CIRGen] Create a new block after break and continue

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/TargetInfo.cpp, clang/lib/CIR/CodeGen/TargetInfo.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/address-space-conversion.cpp, clang/test/CIR/IR/cast.cir, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Transforms/merge-cleanups.cir
* New `CastKind::addrspace_cast` for `cir.cast`
* `TargetCIRGenInfo::performAddrSpaceCast` helper for non-constant values only
* CIRGen for address space casting of pointers and references
* Lowering to LLVM
=> [CIR][CIRGen][LowerToLLVM] Support address space casting

clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/LoweringPrepareAArch64CXXABI.cpp, clang/test/CIR/CodeGen/var-arg-float.c, clang/test/CIR/CodeGen/var-arg-scope.c, clang/test/CIR/CodeGen/var-arg.c
When loweringPrepare cg.var_arg for AArch64, we create multiple basic blocks, but didn't really get ordering of the blocks in the blocklist of the parent region right. That is, we didn't make sure the last of the block list is the naturally last block (exit) of the region. This PR fixes this problem.
If we don't fix this problem, FlattenCFGPass will fail verification because CIRScopeOpFlattening in this pass is onlyy expecting to see cir.yield op in the last block of the region's block list.
=> [CIR][LowerToLLVM][CXXABI] Fix basic block ordering issue.

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/vectype-ext.cpp
Continue the work of #613 .
Original CodeGen treat vec3 as vec4 to get aligned memory access. This PR enable these paths.
=> [CIR][CodeGen] Special treatment of 3-element extended vector load and store

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/address-space-conversion.cpp
Continue the work of #652 . Test the branch of null pointer expressions with side effects.
=> [CIR][CodeGen] Support side effects in address space casting

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/dot.cir
This PR is to fix the issue #658 .
Now we can get the correct result using the following command.
```
echo "void test(int *){}" |  ./build/Debug/bin/clang -cc1 -triple x86_64-unknown-linux-gnu -fclangir -fno-clangir-direct-lowering -emit-mlir -o -
```
result:
```
module attributes {cir.lang = #cir.lang<c>, cir.sob = #cir.signed_overflow_behavior<undefined>, cir.triple = "x86_64-unknown-linux-gnu", dlti.dl_spec = #dlti.dl_spec<#dlti.dl_entry<!llvm.ptr, dense<64> : vector<4xi64>>, #dlti.dl_entry<i1, dense<8> : vector<2xi64>>, #dlti.dl_entry<f16, dense<16> : vector<2xi64>>, #dlti.dl_entry<i32, dense<32> : vector<2xi64>>, #dlti.dl_entry<i8, dense<8> : vector<2xi64>>, #dlti.dl_entry<i16, dense<16> : vector<2xi64>>, #dlti.dl_entry<!llvm.ptr<272>, dense<64> : vector<4xi64>>, …
```
=> [CIR][ThroughMLIR] Fix FuncOp for functions with pointer arguments.

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenCoroutine.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/LoweringPrepareItaniumCXXABI.cpp, clang/test/CIR/CodeGen/call-extra-attrs.cpp
Some function attributes are also callsite attributes, for instance, nothrow. This means they are going to show up in both. We don't support that just yet, hence the PR.
CIR has an attribute `ExtraFuncAttr` that we current use as part of `FuncOp`, see CIROps.td. This attribute also needs to be added to `CallOp` and `TryCalOp`.
Right now, In `CIRGenCall.cpp: AddAttributesFromFunctionProtoType` fills in `FuncAttrs`, but doesn't use it for anything. We should use the `FuncAttrs` result to populate constructing a `ExtraFuncAttr` and add it to the aforementioned call operations.
=> [CIR] Add FuncAttrs to cir.calls

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/vectype.cpp
This pr adds cir.vec.create, extract, insert op lowering to MLIR passes and test files.
Can we lower the vector-related operations in CIR to the vector dialect? This is feasible, although the vector dialect hasn't been used in the CIRToMLIR conversion before. If this lowering is acceptable, I will complete the remaining operations' lowering in the next PR. If there is a more suitable dialect, feel free to discuss it.
=> [CIR][ThroughMLIR] lowering cir.vec.create, extract, insert op to MLIR vector Dialect

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/data-member.cir
This PR adds LLVM lowering support for data member pointers. It includes the following changes:
- ~~The `#cir.data_member` attribute now has a new parameter named `memberOffset`. When the data member pointer is not null, this parameter gives the offset of the pointed-to member within its containing object. This offset is calculated by target ABI.~~
- ~~A new attribute `#cir.data_member_ptr_layout` is added. It contains ABI-specific layout information about a data member pointer that is required to lower it to LLVM IR. This attribute is attached to the module op, and it is queried during LLVMIR lowering to obtain the lowering information in it.~~
- Some CIRGen of the data member pointers is refactored to follow the upstream CodeGen skeleton.
=> [CIR][LLVMLowering] Add LLVM lowering for data member pointers

clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/lib/CIR/Dialect/IR/CIRDataLayout.cpp, clang/lib/CIR/Dialect/IR/CMakeLists.txt
fix build failure 
undefined reference to `cir::CIRDataLayout::CIRDataLayout(mlir::ModuleOp)'
by breaking circular dependency caused by the fact CIRDataLayout was in CIR Codegen
=> [CIR][CIRDataLayout]moving CIRDataLayout to MLIRCIR

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/builtin-floating-point.c
This PR adds new ops, CIRGen, and LLVM lowering support for the following unary fp2int builtins and libc functions:
- `__builtin_lround` family of builtins and `lround` family of libc functions;
- `__builtin_llround` family of builtins and `llround` family of libc functions;
- `__builtin_lrint` family of builtins and `lrint` family of libc functions;
- `__builtin_llrint` family of builtins and `llrint` family of libc functions.
=> [CIR] Add support for unary fp2int builtins

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/CodeGen/CallingConv.h, clang/lib/CIR/CodeGen/TargetInfo.cpp, clang/lib/CIR/CodeGen/TargetInfo.h, clang/test/CIR/CodeGen/OpenCL/addrspace-alloca.cl, clang/test/CIR/CodeGen/OpenCL/spirv-target.cl
* SPIRV64 TargetInfo
* Calling convention `SPIR_KERNEL`
* Minimal ABI with Direct/Extend for arguments and Ignore for return
=> [CIR][CodeGen] Basic skeleton of SPIRV64 target support

clang/include/clang/CIR/Target/AArch64.h, clang/include/clang/CIR/Target/x86.h, clang/lib/CIR/CodeGen/TargetInfo.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepareCXXABI.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/TargetInfo.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/AArch64.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp, clang/lib/CIR/Lowering/DirectToLLVM/CMakeLists.txt, clang/lib/CIR/Lowering/ThroughMLIR/CMakeLists.txt, clang/test/CIR/Transforms/Target/aarch64/aarch64-call-conv-lowering-pass.cpp
This patch is a preparation for the AArch64 calling convention lowering. It adds the basic infrastructure to initialize the AArch64 ABI details and validates it against a trivial void return and argument call conv lowering.
=> [CIR][ABI][NFC] Prime AArch64 CC lowering

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Interfaces/CIROpInterfaces.h, clang/include/clang/CIR/Interfaces/CIROpInterfaces.td, clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Interfaces/CIROpInterfaces.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/array.cpp, clang/test/CIR/CodeGen/const-array.c, clang/test/CIR/CodeGen/coro-task.cpp, clang/test/CIR/CodeGen/globals.cpp, clang/test/CIR/CodeGen/hello.c, clang/test/CIR/CodeGen/lambda.cpp, clang/test/CIR/CodeGen/libcall.cpp, clang/test/CIR/CodeGen/linkage.c, clang/test/CIR/CodeGen/static-vars.c, clang/test/CIR/CodeGen/static-vars.cpp, clang/test/CIR/CodeGen/stmtexpr-init.c, clang/test/CIR/CodeGen/wide-string.cpp
as title. In this PR
1.   make setDSOLocal an interface function.
2.  implemented shouldAssumeDSOLocal function in CIRGenModule, using the same skeleton as shouldAssumeDSOLocal in OG's CodeGenModule.cpp.
3. added call sites of setDSOLocal within CIRGenModule, like what's in OG's CodeGenModule.
4.  fixed printing format 
5.  LLVM lowering
6. keep CIRGenModule::setDSOLocal(mlir::Operation *Op) wrapper at call sites, so if we make changes to interface, we don't have to touch call sites since there are many.
We don't have LLVM test for this PR yet, and it will be addressed by the next PR,:
**TODO in the next PR:**
1.  Implement setNonAliasAttributes in CIRGenModule.cpp, which should be called by CIRGenModule::buildGlobalFunctionDefinition. That way, we will set dso_local correctly for all …
=> [CIR][CIRGen] Add dsolocal attribute to GlobalOp and FuncOp

clang/include/clang/CIR/ABIArgInfo.h, clang/include/clang/CIR/Dialect/IR/CIRDialect.td, clang/include/clang/CIR/MissingFeatures.h, clang/include/clang/CIR/TypeEvaluationKind.h, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/Dialect/Transforms/CallConvLowering.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfo.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfo.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRToCIRArgMapping.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerCall.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/LoweringPrepareAArch64CXXABI.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp, clang/test/CIR/Transforms/Target/x86_64/x86_64-call-conv-lowering-pass.cpp
Adds the necessary bits to lower arguments and return values of type unsigned int for the x86_64 target. This includes adding logic for extend and direct argument-passing kinds.
=> [CIR][ABI] Add unsigned int CC lowering for x86_64

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/bf16-ops.c, clang/test/CIR/CodeGen/fp16-ops.c
This PR fixes a bug during the CIRGen of fp16 unary operations. Before this patch, for the expression `-x` where `x` is a fp16 value, CIRGen emits the code like the following:
```mlir
%0 = cir.cast float_to_float %x : !cir.f16 -> !cir.float
%1 = cir.cast float_to_float %0 : !cir.float -> !cir.f16
%2 = cir.unary minus %1 : !cir.fp16
```
The expected CIRGen should instead be:
```mlir
%0 = cir.cast float_to_float %x : !cir.f16 -> !cir.float
%1 = cir.unary minus %0 : !cir.float
%2 = cir.cast float_to_float %1 : !cir.float -> !cir.f16
```
This PR fixes this issue.
=> [CIR][NFC] Fix bug during fp16 unary op CIRGen

clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/AArch64.cpp, clang/lib/CodeGen/Targets/AArch64.cpp, clang/test/CIR/Transforms/Target/aarch64/aarch64-call-conv-lowering-pass.cpp
Adds the necessary bits to lower arguments and return values of type unsigned int for the x86_64 target.
=> [CIR][ABI] Add AArch64 unsigned int CC lowering

clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/test/CIR/CodeGen/func_dsolocal_pie.c, clang/test/CIR/driver.c
In this PR:
as title we added setNonAliasAttributes in the skeleton of OG's setNonAliasAttributes, and call this function in buildGlobalFunctionDefinition after code for FuncOP is generated. This is needed for CIR OG to know FuncOP is not declaration anymore, thus giving shouldAssumeDsoLocal another run to make dso_local right.
A couple of notes about test;
1. having to changed driver.c, because in terms of dso_local for func, masOS is different from other targets as even in OG, as [macOS is   !isOSBinFormatELF()](https://github.com/llvm/clangir/blob/f78f9a55e7cd6b9e350556e35097616676cf1f3e/clang/lib/CodeGen/CodeGenModule.cpp#L1599), thus even OG doesn't set dso_local for its functions. 
3. most of functions in existing tests still not getting dso_local in LLVM yet because they fall into …
=> [CIR][CIRGen] Add setNonAliasAttributes for GlobalOp and FuncOp

clang/lib/CIR/CodeGen/CIRGenCXXABI.h, clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/test/CIR/CodeGen/dynamic-cast-exact.cpp
This PR implements the last piece to make CIR catch up upstream CodeGen on `dynamic_cast` support. It ports an upstream optimization "exact cast" to CIR.
The basic idea of exact cast is when `dynamic_cast` to a final class, we don't have to call into the runtime -- we could just check if the dynamic type of the source object is exactly the destination type by quickly comparing the vtable pointers. To give a concrete example of this optimization:
```cpp
struct Base { virtual ~Base(); };
struct Derived final : Base {};
Derived *test(Base *src) { return dynamic_cast<Derived *>(src); }
```
Without the optimization, we have to call the runtime function `__dynamic_cast` to do the heavy and slow type check. After enabling the optimization, we could quickly carry out the runtime type check by …
=> [CIR][CIRGen] Add support for exact dynamic cast

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/float16-ops.c
This PR adds LLVM lowering support for `_Float16` type. The only change we need to make here is adding a new type converter to the LLVM lowering pass. The majority of this PR is tests that check the generated LLVM IR.
Later I'll add another separate PR that adds LLVM lowering support for the `__bf16` type. This PR is already big enough.
=> [CIR][LLVMLowering] Add LLVM lowering support for _Float16

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/bf16-ops.c
This PR adds LLVM lowering support for the `__bf16` type. To support its LLVM lowering, we just need to add a new type conversion rule to the LLVM lowering pass. The majority of this PR are the new LLVM IR checks in the tests.
=> [CIR][LLVMLowering] Add LLVM lowering for __bf16

clang/lib/CIR/CMakeLists.txt
Implements approach 2 in https://github.com/llvm/clangir/pull/703#issuecomment-2194665478, as discussed in the community call.
=> [CIR][NFC] Don't enforce deprecated API check on MSVC

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/global.cpp
This commit fixes GlobalOp lowering for floating without initial value. It implies to be initialized with zeros.
E.g. float f[100]; double d;
=> [CIR][ThroughMLIR] Fix floating GlobalOp lowering without initialized value

clang/lib/CIR/CodeGen/CIRGenAtomic.cpp, clang/test/CIR/CodeGen/atomic.cpp
ClangIR was failing on
```
__atomic_compare_exchange_n(&a, &old, 42, true, 5, 5);
```
The `true` was the problem.  It would work with a literal `0` or `1`, but not with a literal `true` or `false`.
The bug was in `isCstWeak` in CIRGenAtomic.cpp, which was only looking for an integral constant.  It didn't recognize a boolean constant and was falling back on the non-constant path, which isn't implemented yet.
Rewrite `isCstWeak` to check for both intergral and boolean constants.
=> [CIR] Fix for __atomic_compare_exchange weak arg

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/complex.c
This PR adds LLVM lowering for the following operations related to complex numbers: 
- `cir.complex.create`,
- `cir.complex.real_ptr`, and
- `cir.complex.imag_ptr`.
The LLVM IR generated for `cir.complex.create` is a bit ugly since it includes the `insertvalue` instruction, which typically is not generated in upstream CodeGen. Later we may need further CIR canonicalization passes to try folding `cir.complex.create`.
=> [CIR][LLVMLowering] Add LLVM lowering for complex operations

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/call.c
This PR fixes the bug described as in https://github.com/llvm/clangir/issues/727#issuecomment-2219515908. It should resolve the crash reported in #727 .
=> [CIR][NFC] Fix bug in MLIR lowering of cir.call

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/include/clang/CIR/Dialect/IR/CIROpenCLAttrs.td, clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp, clang/test/CIR/CodeGen/OpenCL/kernel-attributes.cl, clang/test/CIR/IR/invalid-opencl-vec-type-hint.cir, clang/test/CIR/IR/invalid.cir
This PR introduces a new attribute `OpenCLKernelMetadataAttr` to model the OpenCL kernel metadata structurally in CIR, with its corresponding implementations of CodeGen, Lowering and Translation.
The `"TypeAttr":$vec_type_hint` part is tricky because of the absence of the signless feature of LLVM IR, while SPIR-V requires it. According to the spec, the final LLVM IR should encode signedness with an extra `i32` boolean value.
In this PR, the droping logic from CIR's `TypeConverter` is still used to avoid code duplication when lowering to LLVM dialect. However, the signedness is then restored (still capsuled by a CIR attribute) and dropped again in the translation into LLVM IR.
=> [CIR][Dialect] Emit OpenCL kernel metadata

clang/lib/CIR/Dialect/Transforms/SCFPrepare.cpp, clang/test/CIR/Transforms/scf-prepare.cir
This commit extends the pass to support loop invariant BinOp hoisting as SCF forOp boundary.
E.g.
// (100 - 1) should be hoisted out of loop.
// So the boundary could be input operand to generate SCF forOp.
for (int i = 0; i < 100 - 1; ++i) {}
=> [CIR] Extend -cir-mlir-scf-prepare to support hoisting loop invariant BinOp

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/builtin-floating-point.c, clang/test/CIR/Lowering/builtin-binary-fp2fp.c
LLVM lowering for the following operations is introduced in #616 and #651: `cos`, `exp`, `exp2`, `log`, `log10`, `log2`, `sin`, `sqrt`, `fmod`, and `pow`. However, they are not lowered to their corresponding LLVM intrinsics; instead they are transformed to libc calls during lowering prepare. This does not match the upstream behavior.
This PR tries to correct this mistake. It makes all CIR FP intrinsic ops lower to their corresponding LLVM intrinsics (`fmod` is a special case and it is lowered to the `frem` LLVM instruction).
=> [CIR][Fix] FP builtins should lower directly to LLVM builtins

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/func-dsolocal-parser.cir
as title. document will be in another PR as it seems to be a different upstream branch
=> [CIR][IR] Fix parsing of dsolocal in cir.func

clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
In [this commit](https://github.com/llvm/clangir/commit/e5d840b72c1bdb3276094960e9746e413c6f4456), minimal support for Darwin aarch64 triples was added. But TargetLoweringInfo was not updated correspondingly.
This could lead to a failure of the test `driver.c` with CallConvLowering pass enabled (or `LowerModule` used in some other ways).
This PR fixes the inconsistency and adds an extra missing feature flag for it.
=> [CIR][ABI][NFC] AppleARM64 CXXABI handling in TargetLowering library

clang/lib/CIR/Dialect/Transforms/CallConvLowering.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.h
Although currently LowerModule is not ready for formal usage, we need it for target-specific lowering to LLVM. This PR temporarily public the symbol `createLowerModule` to reuse the logic of preparing a `LowerModule`, making it easier for future refactor (making `TargetLoweringInfo` available for most stages in CIR Lowering).
=> [CIR][ABI][NFC] Make `createLowerModule` public

clang/lib/CIR/CodeGen/CIRGenCXX.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/test/CIR/CodeGen/linkage.c, clang/test/CIR/CodeGen/static.cpp
In this PR, we 
1.  implement defaultVisibility as far as dsolocal is concerned, currently is either MLIR::Visibility isPublic() or isPrivate(). Now, we don't handle hiddenVisibility and protectedVisibility from AST. I put missFeature assert so that If in anyway we translate  hiddenVisibility or protectedVisibility into mlir::SymbolTable::Visibility::Private (hopefully not for it'd be confusing), then we need to revise this defaultVisibility setting.
2.  call setNonAliasAttributes on global op upon discovery of its initialization, thus we have globals dso_local correctly set.
Still missing is lots of function should have dso_local set, but the all depend on comDat implementation, which will come from next PR within the next few days.
=> [CIR][CIRGen] More on dsolocal: visibility improvements

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/test/CIR/IR/address-space.cir
This PR adds definitions of unified address space cases `offload_*` discussed in [this RFC thread](https://discourse.llvm.org/t/rfc-clangir-unified-address-space-design-in-clangir/79728).
It also refactors the `getValueFromLangAS` method in tablegen to a hand-written method, because it should be a non-trivial map for unified AS.
=> [CIR][Dialect] Add minimal definitions of unified address space `offload_*` cases

clang/lib/CIR/CodeGen/CIRGenAtomic.cpp, clang/test/CIR/CodeGen/atomic-runtime.cpp, clang/test/CIR/Lowering/atomic-runtime.cpp
Fix #731
Implement atomic built-in operations where the memory order argument is a runtime value rather than a compile-time constant.  This is necessary to support `std::atomic`.  The ClangIR atomic operations don't support runtime memory orders, so this is implemented during CodeGen by generating a switch statement that effectively converts the runtime memory order into a compile-time memory order.
A new file, atomic-runtime.cpp, was added to the ClangIR CodeGen tests to cover this situation.
=> [CIR] Atomic builtins with non-const memory order

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenValue.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/complex-arithmetic.c
This PR adds support for complex number binary arithmetic operations. Specifically, CIRGen for the following operations on complex numbers are added:
- Binary arithmetic operations: add, sub, mul, and div.
- ~Unary arithmetic operations: plus, minus, and conjugate.~
A new operation `cir.complex.binop` is added to represent binary operations on complex number operands. The new operation contains complex-number-specific attributes for correct lowering to LLVM IR.
~I'll add LLVM IR lowering in later PRs as this PR is already large enough.~ This PR also includes LLVM IR lowering support. It introduces two new operations `cir.complex.real` and `cir.complex.imag` to aid for LLVM IR lowering. These two new operations extract the real and imaginary part of a complex value, which is useful during …
=> [CIR] Add support for binary arithmetic operations on complex numbers

clang/lib/CIR/Dialect/Transforms/TargetLowering/CMakeLists.txt, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/TargetInfo.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/SPIR.cpp
This NFC PR adds the SPIR-V `TargetLoweringInfo` with ABI stuff unimplemented. It's useful for other target-specific information to land first.
=> [CIR][Transforms][TargetLowering][NFC] Add SPIR-V skeleton

clang/lib/CIR/Lowering/DirectToLLVM/CMakeLists.txt
TargetLowering should also serve for DirectToLLVM for target-specific information. The library is already linked against DirectToLLVM, but we have to write dirty includes like `#include "../../Dialect/Transforms/TargetLowering/LowerModule.h"`.
This PR adds a private include directory `clang/lib/CIR/Dialect/Transforms/TargetLowering` to the target DirectToLLVM. Then we can simplify the include directive above to `#include "LowerModule.h"`.
=> [CIR][DirectToLLVM][NFC] Add include of target lowering library to DirectToLLVM

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
After switching to a separate address space attribute in CIR, we need better helper methods in CIR builder.
This PR provides:
* two versions of `getPointerTo`, consuming `LangAS` or `AddressSpaceAttr`.
* an extra helper method `getAddrSpaceAttr(LangAS)` that is used by `getPointerTo(LangAS)` and other potential use cases (mainly about address space cast in the future).
Calls to `getPointerTo` without addrspace will invoke the version consuming `AddressSpaceAttr` and return a type with null addrspace attribute, which should be exactly what we expect for CIRBuilder.
=> [CIR][Builder][NFC] Refactor `getPointerTo` considering AddressSpaceAttr

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/TargetInfo.cpp, clang/lib/CIR/CodeGen/TargetInfo.h
Originally `TargetCodeGenInfo::performAddrSpaceCast` consumes two *unused* parameters typed `clang::LangAS`. This PR changes its type to `mlir::cir::AddressSpaceAttr` to better fit the need of CIRGen.
In [D32248: CodeGen: Cast alloca to expected address space](https://reviews.llvm.org/D32248), the author explained why these AS parameters are not used:
> This is just the default implementation. The idea is that targets that need to do something more complex on a particular conversion — e.g. to make sure that null pointers are translated correctly when they have different bit-patterns — can easily do so.
Further more, I'm confident that the CIR AS is also capable of providing custom behaviors like above for those targets.
=> [CIR][CodeGen][NFC] Refactor `performAddrSpaceCast` to consume CIR address space attributes

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/test/CIR/CodeGen/complex.c
This PR adds CIRGen for the following complex related intrinsics:
- `__builtin_complex`,
- `__builtin_creal`, and
- `__builtin_cimag`.
The generated CIR does not include any new ops so LLVM IR lowering is already done.
=> [CIR] Add support for complex related intrinsics

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/complex-arithmetic.c
This PR adds support for unary operations on complex numbers, namely plus(+), minus(-), and conjugate(~). This PR also adds support for the `__builtin_conj` builtin function which computes the conjugate of the input.
=> [CIR] Add support for unary complex operations

clang/lib/CIR/Dialect/Transforms/CallConvLowering.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.h
Currently `LowerModule` mimics `CodeGenModule` and uses many raw references. It cannot be moved or copied. Value semantic does not fit the need. For example, we cannot pass LowerModule around.
A better practice would be to use `unique_ptr` to encapsulate it. In the future, we hold its ownership in some long-lived contexts (it's `CodeGeneratorImpl` for `CodeGenModule`) and pass references to it around safely.
=> [CIR][Transforms][NFC] Use `unique_ptr` to encapsulate LowerModule

clang/include/clang/CIR/LoweringHelpers.h, clang/lib/CIR/Lowering/CMakeLists.txt, clang/lib/CIR/Lowering/DirectToLLVM/CMakeLists.txt, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/lib/CIR/Lowering/LoweringHelpers.cpp
This commit moves array initial value lowering relative helper functions from DirectToLLVM/LowerToLLVM.cpp to LoweringHelpers.cpp.
So ThroughMLIR/LowerCIRToMLIR.cpp can reuse the helper functions to enable array with initial value lowering in later patch.
This is a refactoring without functional changes.
=> [CIR][Lowering][NFC] Move helper functions to LoweringHelpers.cpp

clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfo.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfo.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp, clang/test/CIR/Transforms/Target/x86_64/x86_64-call-conv-lowering-pass.cpp
Implements calling convention lowering of float and double arguments and return values conventions for X86_64.
=> [CIR][ABI] Add X86_64 float and double CC lowering

clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/TargetLoweringInfo.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/AArch64.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/SPIR.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/OpenCL/addrspace-alloca.cl, clang/test/CIR/CodeGen/OpenCL/spirv-target.cl, clang/test/CIR/Lowering/address-space.cir
This PR implements `offload_*` cases discussed in [this thread](https://discourse.llvm.org/t/rfc-clangir-unified-address-space-design-in-clangir/79728).
* Integrate target-specific CIR-to-LLVM address space map into `TargetLoweringInfo`
* CIRGen: Implement these cases in `getValueFromLangAS`
* Lowering: Extend the state of type converter with `LowerModule`
When frontend provides a new LangAS like `opencl_generic`, it would be processed by CIRGenTypes and `Builder.getPointerTo()` and encoded as `offload_generic`.
When we lower CIR to LLVM, 
* For pointer types without address space attribute, it's mapped to `ptr addrspace(0)` directly
* For target cases `target<x>`, it's mapped to `ptr addrspace(x)`
* For other defined cases, query the target info with a new virtual method …
=> [CIR][CodeGen][LowerToLLVM] End-to-end implementation of `offload_*` cases for OpenCL with SPIR-V target

clang/include/clang/CIR/ABIArgInfo.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp, clang/test/CIR/Transforms/Target/aarch64/aarch64-call-conv-lowering-pass.cpp, clang/test/CIR/Transforms/Target/x86_64/x86_64-call-conv-lowering-pass.cpp
Implements calling convention lowering of bool arguments and return value calling conventions for X86_64 and AArch64.
For x86_64, this is a bit of an odd case. In the orignal codegen bools are represented as i8 everywhere, except for function arguments/return values. In CIR, we don't allow i1 types, so bools are still represented as `cir.bool` when in functions. However, when lowering to LLVM Dialect, we need to ensure bools will be converted to i1 when in function's argument/return values.
=> [CIR][ABI] Add X86_64 and AArch64 bool CC lowering

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/CIRGenTypeCache.h, clang/lib/CIR/CodeGen/TargetInfo.cpp, clang/lib/CIR/CodeGen/TargetInfo.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/OpenCL/addrspace-alloca.cl
`TargetCodeGenInfo::getASTAllocaAddressSpace` is a bad design because it requires the targets return `LangAS`, which enforce the targets to consider which languages could be their upstream and unnecessarily complicate the target info. Unified AS in CIR is a better abstraction level for this kind of target info.
Apart from that, the languages also has some requirements on the result address space of alloca.
```cpp
void func() {
int x;
// Here, the AS of pointer `&x` is the alloca AS defined by the language.
}
```
When we have inconsistency between the alloca AS defined by the language and the one from target info, we have to perform `addrspacecast` from the target one to the language one.
This PR includes
* New method `CGM.getLangTempAllocaAddressSpace` which explicitly specifies the …
=> [CIR][CodeGen][Lowering] Better handling of alloca address space with unified AS

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenCoroutine.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/coro-task.cpp
This PR adds CIRGen for scalar `co_yield` expressions.
=> [CIR][CIRGen] Add CIRGen for scalar co_yield expression

clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/builtin-bit-cast.cpp
This PR adds CIRGen support for the `__builtin_bit_cast` builtin. No new operations are added so the LLVM IR lowering is also added automatically.
=> [CIR] CIRGen for bit cast builtin

clang/lib/CIR/CodeGen/TargetInfo.cpp
This NFCI PR enhances the SPIR-V *CIRGen* ABI with Direct and Extend in both argument and return value, because some future test cases requires it.
* kernel argument metadata needs arguments of promotable integer types
* builtin functions like `get_global_id` returns `si64`, rather than void for all OpenCL kernels
Given that CallConvLowering will replace these bits and other targets is already doing the same, I think it's safe to enable it now.
=> [CIR][ABI][NFCI] Enable SPIR-V return value and argument ABI to use Direct and Extend

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp
Soon I would like to submit a patch emitting OpenCL module metadata in LowerToLLVM path, which requires to attach the metadata to LLVM module when `amendOperaion` is called for MLIR module op. This PR refactors the method to a dispatcher to make the future changes cleaner.
=> [CIR][LowerToLLVM][NFC] Refactor `amendOperation` to dispatch different ops

clang/include/clang/CIR/Dialect/IR/CIROpenCLAttrs.td, clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp, clang/test/CIR/CodeGen/OpenCL/kernel-arg-info-single-as.cl, clang/test/CIR/CodeGen/OpenCL/kernel-arg-info.cl, clang/test/CIR/CodeGen/OpenCL/kernel-arg-metadata.cl, clang/test/CIR/IR/invalid.cir
Similar to #705, this PR implements the remaining `genKernelArgMetadata()` logic.
The attribute `cir.cl.kernel_arg_metadata` is also intentionally placed in the `cir.func`'s `extra_attrs` rather than `cir.func`'s standard `arg_attrs` list. Also, the metadata is stored by `Array` with proper verification on it. See the tablegen doc string for details.
This is in order to
* keep it side-by-side with `cl.kernel_metadata`.
* still emit metadata when kernel has an *empty* arg list (see the test `kernel-arg-meatadata.cl`).
* avoid horrors of repeating the long name `cir.cl.kernel_arg_metadata` for `numArgs` times.
Because clangir doesn't support OpenCL built-in types and the `half` floating point type yet, their changes and test cases are not included. Corresponding missing feature flag is …
=> [CIR][Dialect] Emit OpenCL kernel argument metadata

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/IR/func-call-conv.cir, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/func-call-conv.cir
This PR simply adds the calling convention attribute to FuncOp with LLVM Lowering support.
The overall approach follows `GlobalLinkageKind`: Extend the ODS, parser, printer and lowering pass. When the call conv is C call conv, it's omitted in the output assembly.
=> [CIR][Dialect][Lowering] Add calling convention attribute to FuncOp

clang/lib/CIR/Lowering/LoweringHelpers.cpp, clang/lib/CIR/Lowering/ThroughMLIR/CMakeLists.txt, clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/global.cpp
This commit makes the changes as following.
1. Enable array type GlobalOp lowering with initial values
2. Add error message when array size is not equal to initial string value size
E.g. char big_string[10] = "abc";
=> [CIR][ThroughMLIR] Support array type GlobalOp lowering with initial values

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
There are two sources for the target allocation address space: one from `TargetCIRGenInfo::getCIRAllocaAddressSpace()` and another from `targetDataLayout.getAllocaMemorySpace()`. Since both are provided by the specific target, they should be consistent. This PR adds a check to ensure this consistency and avoid potential errors.
The ctor of `CIRAllocaLowering` pattern is updated to pass the data layout in.
=> [CIR][LowerToLLVM][NFC] Add data layout verification of alloca as

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/test/CIR/CodeGen/OpenCL/opencl-c-lang.cl
This PR adds OpenCL C language case to the enum `mlir::cir::SourceLanguage`, and maps `opts.OpenCL && !opts.OpenCLCPlusPlus` to it.
=> [CIR][Dialect] Add OpenCL C language in cir.lang

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/complex-cast.c
This PR adds support for complex cast operations. It adds the following new cast kind variants to the `cir.cast` operation:
- `float_to_complex`,
- `int_to_complex`,
- `float_complex_to_real`,
- `int_complex_to_real`,
- `float_complex_to_bool`,
- `int_complex_to_bool`,
- `float_complex`,
- `float_complex_to_int_complex`,
- `int_complex`, and
- `int_complex_to_float_complex`.
CIRGen and LLVM IR support for these new cast variants are also included.
=> [CIR] Add support for complex cast operations

clang/include/clang/CIR/Dialect/IR/CIROpenCLAttrs.td, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp, clang/test/CIR/CodeGen/OpenCL/opencl-version.cl
Similar to #767, this PR emit the module level OpenCL version metadata following the OG CodeGen skeleton.
We use a full qualified `cir.cl.version` attribute on the module op to store the info in CIR.
=> [CIR][CodeGen][LowerToLLVM] Emit OpenCL version metadata for SPIR-V target

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/include/clang/CIR/Dialect/IR/CIRDialect.td, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/CIRSimplify.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/complex.c, clang/test/CIR/Lowering/complex.cir, clang/test/CIR/Transforms/complex-fold.cir
This PR adds folders for `cir.complex.create`, `cir.complex.real`, and `cir.complex.imag`.
This PR adds a new attribute `#cir.complex` that represents a constant complex value. Besides, the CIR dialect does not have a constant materializer yet; this PR adds it.
Address #726 .
=> [CIR][Transforms] Add folders for complex operations

clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/CodeGen/TargetInfo.cpp, clang/lib/CIR/CodeGen/TargetInfo.h
This PR follows OG CodeGen to use SPIR ABI info whatever the target is when analysing the function info of SPIR-V kernels (identified by its calling convention).
For example, when compiling OpenCL kernels to x86-64 target, the kernel should still use SPIR-V's ABIInfo.
As we haven't implemented SPIR-V ABI handling for complex constructs, there should be no functional changes. There is a test for this logic in OG CodeGen: `clang/test/CodeGenOpenCL/kernels-have-spir-cc-by-default.cl`. It mainly involves structs, which is beyond the progress of CIR ABI stuff.
=> [CIR][CodeGen][NFCI] Target-independent ABI handling for SpirKernel call conv

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/IR/CIRTypes.h, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/IR/global.cir
This PR adds the CIR address space attribute to GlobalOp and starts to resolve the missing feature flag `addressSpaceInGlobalVar`.
The same asm format in pointer type is used:
```
cir.global external addrspace(offload_global) @addrspace1 = #cir.int<1> : !s32i
```
The parsing and printing helper is extracted into a common function to be reused by both `GlobalOp` and `PointerType` with two custom format proxy to it. That's because the signature of ODS generated method differs from the one for PointerType. 
Lowering to LLVM IR and CIRGen will come sequentially.
=> [CIR][Dialect] Add address space attribute to global op

clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/test/CIR/CodeGen/OpenCL/kernel-arg-metadata.cl, clang/test/CIR/CodeGen/OpenCL/kernel-attributes.cl, clang/test/CIR/CodeGen/OpenCL/spir-calling-conv.cl, clang/test/CIR/CodeGen/OpenCL/spirv-target.cl
This PR adds the counterparts of methods `SetFunctionAttributes` `SetLLVMFunctionAttributes` from OG CodeGen, in order to set proper calling conv for `cir.func` ops.
`spir-calling-conv.cl` is the dedicated test, while other OpenCL-related tests are also updated. It removes previous workaround of incorrect calling conv and better synchronizes with the original tests. (These changes are not musts).
=> [CIR][CodeGen] Set CIR function calling conventions

clang/include/clang/CIRFrontendAction/CIRGenAction.h, clang/lib/CIR/FrontendAction/CIRGenAction.cpp, clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp, clang/test/CIR/cc1.c, clang/test/CIR/driver.c
This PR enables ClangIR pipeline for LLVM bitcode output when it's specified properly, aligned with the behavior of text-form LLVM IR.
Some refactors about switch cases are also included to avoid too many dups.
=> [CIR][FrontendAction] Use ClangIR pipeline to emit LLVM bitcode

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/address-space.cir
This PR set a proper addrspace attribute for LLVM globals. For simplicity, a temporary pointer type is created and consumed by our LLVM type converter. The correct address space is then extracted from the converted pointer type of LLVM.
=> [CIR][LowerToLLVM] Support address space lowering for global ops

clang/include/clang/CIR/Dialect/IR/CIRDataLayout.h, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/Dialect/IR/CIRDataLayout.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfo.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfo.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRRecordLayout.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRRecordLayout.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.h, clang/lib/CIR/Dialect/Transforms/TargetLowering/RecordLayoutBuilder.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp, clang/test/CIR/Lowering/address-space.cir, clang/test/CIR/Transforms/Target/x86_64/x86_64-call-conv-lowering-pass.cpp
This patch adds the necessary bits for unraveling struct arguments and
return values for the x86_64 calling convention.
=> [CIR][ABI] Implement basic struct CC lowering for x86_64

clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/complex-cast.c
This PR adds CIRGen and LLVMIR codegen for those not-yet-covered complex casts, including explicit type cast expressions of complex types and complex value promotion.
All type conversion expressions involving complex types should now codegen.
=> [CIR][CIRGen] Support more complex value casts

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/invalid.cir
This PR verifies `cir.get_global` has its result type correctly annotated with address space of the referenced symbol. The documentation is also updated to clarify this constraint.
`GlobalOp` is the main consideration. It's worth noting that if the `cir.get_global` op references a function, we also (implicitly) checks that its result pointer type has no address space attribute.
=> [CIR][Dialect] Add verification of address space to `get_global`

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/TargetInfo.cpp, clang/lib/CIR/CodeGen/TargetInfo.h, clang/test/CIR/CodeGen/OpenCL/global.cl
This PR sets proper address space when creating `cir.global` and `cir.get_global`.
Different languages use different ways to encode the address space in AST constructs (i.e. VarDecl *). OpenCL and SYCL use an address space qualifier on the type of `VarDecl`, while CUDA uses separate AST attributes like `CUDASharedAttr`. Similarily, some targets may want to use special address space for global variables. So a per-language + per-target hook is needed to provide this customization point. In the LLVM CodeGen, it's the helper method `getGlobalVarAddressSpace` that takes on the role.
For OpenCL C + SPIR-V combination, OpenCL C converts the address space qualifier to corresponding LangAS, but SPIR-V does not require any action.
This PR implements `global` qualifier in OpenCL C, but does not …
=> [CIR][CodeGen] Set address space for OpenCL globals

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/unary-inc-dec.cir
Unary decrement expression on floating point operands was lowered to `fsub -1.0` by a typo. This PR fixes this bug.
=> [CIR] Fix wrong LLVMIR lowering of fp decrement

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/complex-arithmetic.c
This PR adds CIRGen and LLVMIR lowering for unary increment and decrement expressions of complex types.
Currently blocked by #789 .
=> [CIR][CIRGen] Complex unary increment and decrement operator

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/CodeGen/CIRGenOpenCLRuntime.cpp, clang/lib/CIR/CodeGen/CIRGenOpenCLRuntime.h, clang/lib/CIR/CodeGen/CMakeLists.txt, clang/test/CIR/CodeGen/OpenCL/global.cl, clang/test/CIR/CodeGen/OpenCL/static-vardecl.cl
In OpenCL, `local`-qualified variables are implicitly considered as static. In order to support it, this PR unblocks code paths related to OpenCL static declarations in `CIRGenDecl.cpp`.
Following the approach of LLVM CodeGen, a new class `CIRGenOpenCLRuntime` is added to handle the language hook of creating `local`-qualified variables. The default behavior of this hook is quite simple. It forwards the call to `CGF.buildStaticVarDecl`.
So in CIR, the OpenCL local memory representation is equivalent to the one defined by SPIR-LLVM convention: a `cir.global` with `addrspace(local)` and *without initializer*, which corresponds to LLVM `undef` initializer. See check lines in test for more details.
A `static global`-qualified variable is also added in the test to exercise the static code path …
=> [CIR][CodeGen] Set address space for OpenCL static and local-qualified variables

clang/include/clang/CIR/Dialect/IR/CIRDataLayout.h, clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/Dialect/IR/CIRDataLayout.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRRecordLayout.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerCall.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/RecordLayoutBuilder.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp, clang/test/CIR/Lowering/address-space.cir
This patch fixes a bunch of pending review comments in #784:
- Remove data layout attribute from address space testing
- Remove incoherent comment
- Rename abi_or_pref to abiOrPref
- Make comments impersonal
- Implement feature guard for ARM's CMSE secure call feature
- Track volatile return times feature in CC lowering
- Track missing features in the Itanium record builder
- Remove incoherent fix me
- Clarify comment regarding CIR record layout getter
- Track missing cache for record layout getter
- Remove unnecessary todo's
=> [CIR][ABI][NFC] Follow-up to struct unpacking

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenCXXABI.h, clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/lib/CIR/Dialect/IR/CIRAttrs.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/CodeGen/pointer-to-member-func.cpp
This PR adds the initial CIRGen support for pointer-to-member-functions. It contains the following new types, attributes, and operations:
- `!cir.method`, which represents the pointer-to-member-function type.
- `#cir.method`, which represents a literal pointer-to-member-function value that points to ~~non-virtual~~ member functions.
- ~~`#cir.virtual_method`, which represents a literal pointer-to-member-function value that points to virtual member functions.~~
- ~~`cir.get_method_callee`~~ `cir.get_method`, which resolves a pointer-to-member-function to a function pointer as the callee.
See the new test at `clang/test/CIR/CIRGen/pointer-to-member-func.cpp` for how these new CIR stuff works to support pointer-to-member-functions.
=> [CIR][CIRGen] Add CIRGen support for pointer-to-member-functions

clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp, clang/test/CIR/CodeGen/bitfield-union.c
Achieve union's bitfields additionally.
=> [CIR][CIRGen] Achieve union's bitfields additionally.

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/CIRSimplify.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/select.cir, clang/test/CIR/Transforms/select.cir
This PR adds a new `cir.select` operation. This operation won't be generated directly by CIRGen but it is useful during further CIR to CIR transformations.
This PR addresses #785 .
=> [CIR] Add select operation

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/Dialect/IR/CIRDataLayout.cpp, clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp, clang/test/CIR/CodeGen/cxx1z-inline-variables.cpp
There is an implementation for inline variables processing at CIR. The LIT test was taken from clang's cxx1z-inline-variables.cpp where the same functionality is tested for Clang Code generation. The test can be run as follows
```
bin/llvm-lit -v ../clang/test/CIR/CodeGen/cxx1z-inline-variables.cpp
```
Note: the pull request also contains a formatting change for two files:
- `clang/lib/CIR/Dialect/IR/CIRDataLayout.cpp`
- `clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp`
=> [CIR][clang] Inline variables processing

clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp, clang/test/CIR/CodeGen/complex-arithmetic.c, clang/test/CIR/CodeGen/complex-cast.c, clang/test/CIR/CodeGen/three-way-comparison.cpp
This PR refactors the LoweringPrepare pass and replaces various ternary ops generated by LoweringPrepare with semantically equivalent select ops.
=> [CIR][NFC] Replace ternary ops after lowering prepare to select ops

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Dialect/IR/CMakeLists.txt, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/builtin-floating-point.cir, clang/utils/TableGen/CIRLoweringEmitter.cpp, clang/utils/TableGen/CMakeLists.txt, clang/utils/TableGen/TableGen.cpp, clang/utils/TableGen/TableGenBackends.h
This PR is the continuation and refinement of PR #434 which is originally authored by @philnik777 . Does not update it in-place since I don't have commit access to Nikolas' repo.
This PR basically just rebases #434 onto the latest `main`. I also updated some naming used in the original PR to keep naming styles consistent.
=> [CIR][Lowering] Add the concept of simple lowering and use it for unary fp2fp operations

clang/lib/CIR/CodeGen/CIRGenCXXABI.h, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.h, clang/test/CIR/CodeGen/special-virtual-func.cpp
This is a straightforward adaption of existing CodeGen logic. While I'm
here, move block comments inside their blocks, so that they look nicer.
=> [CIR][CIRGen] Support pure and deleted virtual functions

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/attributes.c, clang/test/CIR/CodeGen/cxx1z-inline-variables.cpp, clang/test/CIR/CodeGen/globals-neg-index-array.c, clang/test/CIR/CodeGen/static.cpp, clang/test/CIR/Lowering/ThroughMLIR/vtable.cir, clang/test/CIR/Lowering/globals.cir, clang/test/CIR/Lowering/hello.cir
As title.
Add setAlignmentAttr for GlobalOps created from AST.
LLVM Lowering should have LLVM GlobalOp's alignment attribute inherited from CIR::GlobalOp.
This PR is definitely needed to fix issue https://github.com/llvm/clangir/issues/801#issuecomment-2305692250, but the issue doesn't have alignment and comdat attribute for CIR Ops to begin with, so I'll keep investigating and fix CIR problem in another PR.
=> [CIR][CIRGen][Lowering] Get alignment from frontend and pass it to LLVM

clang/lib/CIR/CodeGen/CIRGenBuilder.cpp, clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/CodeGen/OpenCL/array-decay.cl, clang/test/CIR/IR/invalid.cir
There are two occurrences of `cir.cast(array_to_ptrdecay, ...)` that drop address spaces unexpectedly for its result pointer type. This PR fixes them with the source address space.
```mlir
// Before
%1 = cir.cast(array_to_ptrdecay, %0 : !cir.ptr<!cir.array<!s32i x 32>, addrspace(offload_local)>), !cir.ptr<!s32i>
// After
%1 = cir.cast(array_to_ptrdecay, %0 : !cir.ptr<!cir.array<!s32i x 32>, addrspace(offload_local)>), !cir.ptr<!s32i, addrspace(offload_local)>
```
=> [CIR][CodeGen] Fix address space of result pointer type of array decay cast op

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/CIRSimplify.cpp, clang/test/CIR/Transforms/select.cir
As mentioned at https://github.com/llvm/clangir/pull/809#discussion_r1734972785 , this PR adds more simplify transformations for select op:
- `cir.select if %0 then x else x` -> `x`
- `cir.select if %0 then #true else #false` -> `%0`
- `cir.select if %0 then #false else #true` -> `cir.unary not %0`
=> [CIR][Transform] Add simplify transformation for select op

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/utils/TableGen/CIRLoweringEmitter.cpp
This PR makes simple lowering generate the result type lowering logic and make it suitable for unary fp2int operations and binary fp2fp operations.
=> [CIR][NFC] Extend simple lowering to unary fp2int ops and binary fp2fp ops

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/temporary-materialization.cpp
This PR adds initial support for temporary materialization of local temporaries with trivial cleanups.
Materialization of global temporaries and local temporaries with non-trivial cleanups is far more trickier that I initially thought and I decide to submit this easy part first.
=> [CIR][CIRGen] Add initial CIRGen support for local temporary materialization

clang/lib/CIR/CodeGen/CIRGenClass.cpp, clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/delegating-ctor.cpp
This is a straightforward adaption from CodeGen. I checked the uses of
the Delegating arg that's passed in various places, and it only appears
to be used by virtual inheritance, which should be handled by
https://github.com/llvm/clangir/pull/624.
=> [CIR][CIRGen] Implement delegating constructors

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/invalid.cir
Currently some bitcasts would silently change the address space of source pointer type, which hides some miscompilations of pointer type in CIR.
#812 is an example. The address space in result pointer type is dropped, but the bitcast later keep the type consistency no matter what the result type is. Such bitcast is commonly emitted in CodeGen.
CIR bitcasts are lowered to LLVM bitcasts, which also don't allow mismatch between address spaces. This PR adds this verification.
=> [CIR][Dialect] Verify bitcast does not contain address space conversion

clang/lib/Driver/ToolChains/Clang.cpp, clang/test/CIR/driver.c
Allow from the clang driver the use of lowering from CIR to MLIR standard dialect.
Update the test to match the real output when
`-fno-clangir-direct-lowering` is used, or with a combination of both `-fclangir-direct-lowering` and `-fno-clangir-direct-lowering`.
=> [CIR][driver] Forward -fno-clangir-direct-lowering option to cc1

clang/lib/CIR/Dialect/Transforms/CIRSimplify.cpp, clang/test/CIR/CodeGen/binop.cpp, clang/test/CIR/CodeGen/ternary.cpp, clang/test/CIR/Transforms/ternary-fold.cir, clang/test/CIR/Transforms/ternary-fold.cpp
This PR adds a new transformation that transform suitable ternary operations into select operations.
Currently the "suitable" ternary operations are those ternary operations whose both branches satisfy either one of the following criteria:
- The branch only contain a single `cir.yield` operation;
- The branch contains a `cir.const` followed by a `cir.yield` that yields the constant value produced by the `cir.const`.
- ~~The branch contains a `cir.load` followed by a `cir.yield` that yields the value loaded by the `cir.load`. The load operation cannot be volatile and must load from an alloca.~~
These criteria are hardcoded now so that simple C/C++ ternary expressions could be eventually lowered to a `cir.select` operation instead.
=> [CIR][Transform] Add ternary simplification

clang/lib/CIR/CodeGen/CIRGenClass.cpp, clang/test/CIR/CodeGen/defined-pure-virtual-func.cpp
This is permitted by the language, and IRGen emits traps for destructors
other than the base object destructor. Make CIRGen follow suit.
=> [CIR][CIRGen] Support a defined pure virtual destructor

clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h, clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/include/clang/CIR/Interfaces/CIROpInterfaces.td, clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/call-op-call-conv.cir
The first patch to fix #803 . This PR adds the calling convention attribute to CallOp directly, which is similar to LLVM, rather than adding the information to function type, which mimics Clang AST function type.
The syntax of it in CIR assembly is between the function type and extra attributes, as follows:
```mlir
%1 = cir.call %fnptr(%a) : (!fnptr, !s32i) -> !s32i cc(spir_kernel) extra(#fn_attr)
```
The verification of direct calls is not included. It will be included in the next patch extending CIRGen & Lowering.
---
For every builder method of Call Op, an optional parameter `callingConv` is inserted right before the parameter of extra attribute. However, apart from the parser / printer, this PR does not introduce any functional changes.
=> [CIR][Dialect] Add calling convention attribute to cir.call op

clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/test/CIR/CodeGen/delegating-ctor.cpp
Similar to #830 , this PR completes the `setCIRFunctionAttributes` part with the call to `constructAttributeList` method, so that func op and call op share the logic of handling these kinds of attributes, which is the design of OG CodeGen.
It also includes other refactors. The function `constructAttributeList` now use `mlir::NamedAttrList &` rather than immutable attribute `mlir::DictionaryAttr &` as the inout result parameter, which benefits the additive merging of attributes.
=> [CIR][CodeGen][NFCI] Unify attribute list handling of func / call by `constructAttributeList`

clang/lib/CIR/CodeGen/CIRGenCXX.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/test/CIR/CodeGen/attributes.c, clang/test/CIR/CodeGen/visibility-attribute.c
Previously the body of `setExtraAttributesForFunc` corresponds to `SetLLVMFunctionAttributesForDefinition`, but the callsite of it does not reside at the right position. This PR rename it and adjust the calls to it following OG CodeGen.
To be specific, `setExtraAttributesForFunc` is called right after the initialization of `FuncOp`. But in OG CodeGen, the list of attributes is constructed by several more functions: `SetLLVMFunctionAttributes` and `SetLLVMFunctionAttributesForDefinition`.
This results in diff in attributes of function declarations, which is reflected by the changes of test files. Apart from them, there is no functional change. In other words, the two code path calling `setCIRFunctionAttributesForDefinition` are tested by existing tests:
* Caller …
=> [CIR][CodeGen] Refactor `setExtraAttributesForFunc` to better align with OG

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/call.cir
The parser was looking for extra(...) before the return type while the pretty-printer put it after the return type.
This was breaking the LSP-server for example.
Change the parser behavior accordingly.
=> [CIR][Asm] Fix parsing of extra(...) attributes in cir.call

clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/OpenCL/spir-calling-conv.cl, clang/test/CIR/IR/invalid.cir, clang/test/CIR/Lowering/call-op-call-conv.cir
This PR implements the CIRGen and Lowering part of calling convention attribute of `cir.call`-like operations. Here we have **4 kinds of operations**: (direct or indirect) x (`call` or `try_call`).
According to our need and feasibility of constructing a test case, this PR includes:
* For CIRGen, only direct `call`. Until now, the only extra calling conventions are SPIR ones, which cannot be set from source code manually using attributes. Meanwhile, OpenCL C *does not allow* function pointers or exceptions, therefore the only case remaining is direct call.
* For Lowering, direct and indirect `call`, but not any `try_call`. Although it's possible to write all 4 kinds of calls with calling convention in ClangIR assembly, exceptions is quite hard to write and read. I prefer source-code-level …
=> [CIR][CodeGen][LowerToLLVM] Set calling convention for call ops

clang/lib/CIR/Lowering/LoweringHelpers.cpp, clang/test/CIR/Lowering/static-array.c
Consider the following code snippet `test.c`: 
```
int test(int x) {
static int arr[10] = {0, 1, 0, 0};
return arr[x];
}
```
When lowering from CIR to LLVM using `bin/clang test.c -Xclang -fclangir -Xclang -emit-llvm -S -o -` It produces: 
```
clangir/mlir/lib/IR/BuiltinAttributes.cpp:1015: static mlir::DenseElementsAttr mlir::DenseElementsAttr::get(mlir::ShapedType, llvm::ArrayRef<llvm::APInt>): Assertion `hasSameElementsOrSplat(type, values)' failed.
```
I traced the bug back to `Lowering/LoweringHelpers.cpp` where we fill trailing zeros, and I believe this PR does it the right way. I have also added a very simple test for verification.
=> [CIR][Lowering] Fix static array lowering

clang/test/CIR/IR/call-op-call-conv.cir, clang/test/CIR/IR/call.cir
There is a typo in `call.cir` that uses a wrong function argument type, leading to failure in the final LLVM IR translation.
CIR verification does not reject it, because it skips indirect calls at the beginning. It's `verifySymbolUses` after all.
https://github.com/llvm/clangir/blob/bde154cf1243cc4f938339c4dc15b1576d3025ab/clang/lib/CIR/Dialect/IR/CIRDialect.cpp#L2672-L2679
The typo was copied to another IR test. Here we fix them all.
=> [CIR][NFC] Fix mismatch of argument type in IR tests

clang/include/clang/CIR/Dialect/IR/CIRAttrs.td, clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp, clang/test/CIR/CodeGen/OpenCL/convergent.cl
Fix #805. This PR includes end-to-end implementation.
The `convergent` attribute is set depending on languages, which is wrapped as `langOpts.assumeFunctionsAreConvergent()`.
Therefore, in ClangIR, every `cir.func` under `#cir.lang<opencl_c>` is set to be convergent.
After lowering to LLVM IR, `PostOrderFunctionAttrs` pass will remove unnecessary `convergent` then. In other words, we will still see `convergent` on every function with `-O0`, but not with default optimization level.
The test taken from `CodeGenOpenCL/convergent.cl` is a bit complicated. However, the core of it is that `convergent` is set properly for `convfun()` `non_convfun()` `f()` and `g()`. Merge of two `if` is more or less a result of generating the same LLVM IR as OG.
=> [CIR][Dialect] Add `convergent` attribute to functions for SIMT languages

clang/include/clang/CIR/Interfaces/CIRLoopOpInterface.td, clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp
Per the operation walking documentation [1]:
> A callback on a block or operation is allowed to erase that block or
> operation if either:
>   * the walk is in post-order, or
>   * the walk is in pre-order and the walk is skipped after the erasure.
We were doing neither when erasing terminator operations and replacing
them with a branch, leading to a use after free and ASAN errors. This
fixes the following tests with ASAN:
```
Clang :: CIR/CodeGen/switch-gnurange.cpp
Clang :: CIR/Lowering/atomic-runtime.cpp
Clang :: CIR/Lowering/loop.cir
Clang :: CIR/Lowering/loops-with-break.cir
Clang :: CIR/Lowering/loops-with-continue.cir
Clang :: CIR/Lowering/switch.cir
Clang :: CIR/Transforms/Target/x86_64/x86_64-call-conv-lowering-pass.cpp
Clang :: CIR/Transforms/loop.cir
Clang :: …
```
=> [CIR][FlattenCFG] Fix use after free when flattening terminator

clang/include/clang/CIR/Dialect/IR/CIROpenCLAttrs.td, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp
Looks like certain names should not be used - I even could not build CIR on the Ubuntu with a relatively old glibc version.  
In this case `minor` and `major` are macroses and can not be used in this context.
You can take a look at the comments in the [mlir/test/lib/Dialect/Test/TestDialect.h](https://github.com/llvm/clangir/blob/main/mlir/test/lib/Dialect/Test/TestDialect.h#L70) reference as well
=> [CIR][Bugfix] renames minor/major parameters of the OpenCLVersionAttr

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/builtin-assume.cpp, clang/test/CIR/Transforms/builtin-assume.cir
This PR adds CIRGen support for the following 3 builtins related to compile- time assumptions:
- `__builtin_assume`
- `__builtin_assume_aligned`
- `__builtin_assume_separate_storage`
3 new operations are invented to represent the three builtins.
_LLVMIR lowering for these builtins cannot be implemented at this moment_ due to the lack of operand bundle support in LLVMIR dialect.
=> [CIR][CIRGen] add CIRGen support for assume builtins

clang/lib/CIR/FrontendAction/CIRGenAction.cpp
When the output file name is not specified via `-o`, the upstream clang uses `.ll` as the extension of the default output file name. This PR makes ClangIR follow this behavior.
=> [CIR][NFC] Change default LLVM output file extension

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/call.cir
Align parsing of cir.call with its pretty-printing.
=> [CIR][Asm] Parse extra attributes after calling convention

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
Directly erasing the op causes a use after free later on, presumably
because the lowering framework isn't aware of the op being deleted. This
fixes `clang/test/CIR/CodeGen/pointer-arith-ext.c` with ASAN.
=> [CIR][Lowering] Erase op through rewriter instead of directly

clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
The loop was erasing the user of a value while iterating on the value's
users, which results in a use after free. We're already assuming (and
asserting) that there's only one user, so we can just access it directly
instead. CIR/Transforms/Target/x86_64/x86_64-call-conv-lowering-pass.cpp
was failing with ASAN before this change. We're now ASAN-clean except
for https://github.com/llvm/clangir/issues/829 (which is also in
progress).
=> [CIR][ABI] Fix use after free from erasing while iterating

clang/include/clang/CIR/MissingFeatures.h, clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/arm-neon-directed-rounding.c
As title.
Also introduced buildAArch64NeonCall skeleton, which is partially the counterpart of OG's EmitNeonCall. And this could be use for many other neon intrinsics.
=> [CIR][CIRGen][Builtin][Neon] Lower __builtin_neon_vrndns_f32
