clang/lib/CIR/CodeGen/CIRGenTypes.cpp
=> [CIR][CodeGen][NFC] Group signed/unsigned Clang builtin types cases

clang/test/CIR/CodeGen/unary.cpp
Two simple tests for post inc/dec, plus one more that ensures a post-increment is used before it's incremented. LMK If you want more tests.
Tagging https://github.com/llvm/clangir/issues/7
=> add more tests for inc/dec

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/binop.cpp
Adds CIR codegen for logical binary ops using `cir.ternary`
=> [CIR][Dialect] Add logical binop

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/cast.cpp
* #106
* #105
* #104
* #102
* __->__ #101
* #100
=> [CIR][Lowering] Lower floating point extension cast

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/variadics.cir
* __->__ #95
* #94
* #93
Implement lowering steps for va_start, va_end, and va_copy. The va_arg
was not implemented because it requires ABI-specific lowering.
=> [CIR][Lowering] Partially lower variadic builtins

clang/lib/CIR/FrontendAction/CIRGenAction.cpp, clang/test/CIR/CodeGen/basic.c
Summary:
Previously CIR pipeline is only avaliable for EmitCIR mode. I'm moving it out and sharing it with all other emission modes.
=> [CIR] Share CIR pass pipeline for all emission modes.

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/globals.c, clang/test/CIR/Lowering/globals.cir
* __->__ #127
* #126
* #125
* #124
=> [CIR][Lowering] Lower float/double const array initializers

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/array.cpp
=> [CIR][CIRGen] Add basic multi-dim array access

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/binop-signed-int.cir
Adds lowering for signed division, remainder, and r-shift operations.
=> [CIR][Lowering] Lower remaining singed integer binops

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
* #147
* __->__ #146
* #145
* #144
Conditionally set the loop entry point depending on whether the loop is
of the `do-while` kind or not.
=> [CIR][Lowering] Lower structured do-while loops

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
* __->__ #157
* #156
* #155
* #154
=> [CIR][Lowering][NFC] Inline rewriteLoop method

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/expressions.cpp
=> [CIR][CIRGen] Build LValue parentheses expressions

clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/test/CIR/CodeGen/linkage.c
=> [CIR][CIRGen] Unblock available_externally linkage codegen path

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/test/CIR/CodeGen/struct.cpp
=> [CIR][CIRGen] Generate const struct array initialization

clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp, clang/test/CIR/mlirargs.c
Enabling MLIR asm printing options such as -mlir-print-op-generic
=> [CIR] Enable MLIR asm printer options

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/struct.c, clang/test/CIR/Lowering/struct.cir
* #203
* __->__ #202
* #201
* #200
* #199
Lowers the particular case where an array of structs is constant-initialized.
=> [CIR][Lowering] Lower constant arrays of structs

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/vbase.cpp
Lowering Vtable and RTTI globals. Also lowering AddressPoint.
based on https://github.com/llvm/clangir/pull/259
=> [CIR][Lowering] Lower vtable and type info

clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/fun-ptr.c
This PR adds a support of the function pointers in CIR.
From the implementation point of view, we emit an address of a function as a `GlobalViewAttr`.
=> [CIR][CIRGen][Lowering] supports functions pointers

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/CodeGen/CIRGenTypes.cpp, clang/test/CIR/CodeGen/array.c
Just a minor fix with for incomplete arrays + minor refactoring
=> [CIR][CodeGen] supports incomplete arrays 

clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp, clang/lib/CIR/CodeGen/CIRGenVTables.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/globals.c, clang/test/CIR/CodeGen/vbase.cpp, clang/test/CIR/CodeGen/vtable-rtti.cpp
This is a followup PR to comment https://github.com/llvm/clangir/pull/305#discussion_r1393023729 by @bcardosolopes
=> [CIR] Change GlobalViewAttr indices to use MLIR integers.

clang/CMakeLists.txt, llvm/CMakeLists.txt
=> [CIR] Remove LLVM_ENABLE_PROJECTS support

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/gnu-extension.c
Support \_\_extension\_\_ keyword in CIRGen
=> [CIR][CIRGen] Handle __extension__ keyword

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/test/CIR/CodeGen/bool.c
Support for BoolAttr in isNullValue
=> [CIR][CIRGen] Add missing case to 'isNullValue'

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/UnimplementedFeatureGuarding.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/attributes.c
This PR adds support for section("$name") attribute
=> [CIR][CIRGen] Support for section atttribute

clang/lib/CIR/CodeGen/CIRGenBuilder.h, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/CodeGen/globals.cpp, clang/test/CIR/Lowering/bool.cir
Support missing zero initialization of Bools
=> [CIR][CIRGen][Bugfix] Fix bool zero initialization

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/ternary.cpp
Support for ConditionalOperator inside the if condition stmt
=> [CIR][CIRGen] Handle ternary op inside if cond

clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/test/CIR/CodeGen/if-consteval.cpp
Emit the false-branch of the consteval if statement, if any.
=> [CIR][CIRGen] Implement "if consteval" code generation

clang/lib/CIR/CodeGen/CIRGenDecl.cpp, clang/test/CIR/CodeGen/typedef.c
The change is taken from original codegen.
=> [CIR][CIRGen] Add suppport for local typedefs

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Lowering/const.cir
This PR adds missing case to lowerCirAttrAsValue.
=> [CIR][Lowering] add lowering of bool attribute

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/cast.c
Change is taken from original llvm codegen
=> [CIR][CIRGen] Support for CStyleCastExprClass in buildCastLValue

clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/lib/CIR/CodeGen/CIRGenStmt.cpp, clang/test/CIR/CodeGen/switch.cpp
This PR adds handling of AttributedStmt to support fallthrough attribute.
=> [CIR][CIRGen] Support for __attribute__((fallthrough)) statement

clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/test/CIR/IR/invalid.cir
Fix  `CastOp::Verify` and invalid.cir error message. Let these error messages with consistent format. #318
=> [CIR][NFC] Improve verifier related error messages

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/cos.cir
Add left long double types lowering for cos operation #565
=> [CIR][Lowering] Add long double types for cos operation lowering

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/shift.cir
This pr adds cir.shift lowering to MLIR passes and test files.
=> [CIR][Lowering] Add MLIR lowering support for CIR shift operations

README.md
This link was broken on https://llvm.github.io/clangir/
=> Fix pdf link in README.md

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/test/CIR/CodeGen/call-via-class-member-funcptr.cpp
as title. OG's counterpart is [here](https://github.com/llvm/clangir/blob/b41d427cc72057adadbdbd2f5e54fdb46592a52a/clang/lib/CodeGen/CGExpr.cpp#L5607)
=> [CIR][CIRGen] Resolve more calls to member functions

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRLoopToSCF.cpp, clang/test/CIR/Lowering/ThroughMLIR/doWhile.c, clang/test/CIR/Lowering/ThroughMLIR/while.c
In this pr, I lowering cir.do to scf.while, fix cir.while nested loop bugs and add test cases.
=> [CIR][ThroughMLIR] Lowering cir.do to scf.while,and fix cir.while lowering bugs.

clang/lib/CIR/CodeGen/Address.h, clang/lib/CIR/CodeGen/CIRGenCstEmitter.h, clang/lib/CIR/CodeGen/CIRGenExprConst.cpp, clang/lib/CIR/CodeGen/CIRGenModule.cpp, clang/lib/CIR/CodeGen/CIRGenModule.h, clang/test/CIR/CodeGen/temporaries.cpp
Support expressions at the top level such as
const unsigned int n = 1234;
const int &r = (const int&)n;
=> [CIR][CodeGen] Support global temporaries

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/null-arithmatic-expression.c
=> [CIR][CIRGen] Implement Nullpointer arithmatic extension

clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/compound-literal-empty.c
=> [CIR][CIRGen] Generate CIR for empty compound literal

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/test/CIR/CodeGen/builtins-memory.c
This is just the usual adaption from CodeGen.
=> [CIR][CIRGen] Support __builtin___memcpy_chk

clang/include/clang/CIR/Dialect/IR/CIROps.td
=> [CIR][NFC] Expand doc on `cir.scope` terminators

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
This PR is a NFC as we just NYI every builtID of neon SISD. We will implement them in subsequent PRs.
=> [CIR][Builtin][Neon][NFC] Introduce skeleton of emitCommonNeonSISDBuiltinExpr

clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/test/CIR/CodeGen/new.cpp, clang/test/CIR/Lowering/new.cpp
Implement CIR code generation for array new in the case where the array size is represented by a variable.
=> [CIR] Implement array new handling for variable array size

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/CodeGen/CIRGenClass.cpp, clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp, clang/test/CIR/CodeGen/array-new-init.cpp, clang/test/CIR/Lowering/new.cpp
This adds support for array new expressions on objects with non-trivial constructors.
=> [CIR] Add support for array new with constructors

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon-arith.c
Lower `neon_vaddlv_s16` and `neon_vaddlv_u16`
=>  [CIR][CIRGen][Builtin][Neon] Lower neon_vaddlv s16 and u16

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/bf16-getset-intrinsics.c, clang/test/CIR/CodeGen/AArch64/v8.2a-neon-intrinsics-generic.c
Lower vget_lane_bf16, vduph_lane f16 and bf16
=> [CIR][CIRGen][Builtin][Neon] Lower vget_lane_bf16, vduph_lane f16 and bf16

clang/lib/CIR/CodeGen/CIRGenExpr.cpp, clang/lib/CIR/CodeGen/TargetInfo.cpp, clang/test/CIR/CodeGen/vectype-ext.cpp
This PR removes XFAIL test_vec3
=> [CIR][CIRGen] handle vectors of size 3 like size 4 for better performance

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower vrsrad_n u64 and s64

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
Lower builtin_neon_vqshld_n s64 and u64
=> [CIR][CIRGen][Builtin][Neon] Lower builtin_neon_vqshld_n s64 and u64

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/v8.5a-neon-frint3264-intrinsic.c
=> [CIR][CIRGen][Builtin][Neon] Lower neon_vrnd32x

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/v8.5a-neon-frint3264-intrinsic.c
=> [CIR][CIRGen][Builtin][Neon] Lower vrnd64x and vrnd64xq

GettingStarted/testing.md
I'm not sure when this was last updated, but a lot of progress has been made.
=> Update llvm-test-suite pass percentage

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower vcaged_f64

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower neon vaddlv_u32

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower neon vcages_f32

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower neon vmaxv_f32

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower neon vaddlv_s32

clang/lib/CIR/CodeGen/CIRGenBuiltinX86.cpp, clang/test/CIR/CodeGen/AArch64/neon.c, clang/test/CIR/CodeGen/X86/builtins-x86.c
I realized I committed a new file with CRLF before. Really sorry about that >_<
Related: https://github.com/llvm/clangir/issues/1404
=> [CIR][CIRGen][builtin][X86] handle _mm_lfence

clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp, clang/lib/CIR/CodeGen/CIRGenBuiltinNVPTX.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/CUDA/printf.cu
The choice of adding a separate file imitates that of OG.
=> [CIR][CUDA] Support device-side printf

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower neon vcaled_f64

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower vcales_f32

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/atan.cir
Adds implementation for ATanOp's lowering ThroughMLIR.
=> [CIR][ThroughMLIR] Add ATanOp Lowering 

clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp, clang/test/CIR/Lowering/ThroughMLIR/asin.cir
Adds implementation for ASinOp's lowering ThroughMLIR.
=> [CIR][ThroughMLIR] Add ASinOp Lowering 

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower vmaxv_u32

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
=> [CIR][CIRGen][Builtin][Neon] Lower vminv_s32

clang/include/clang/CIR/Dialect/IR/CIRTypes.td, clang/lib/CIR/Dialect/IR/CIRTypes.cpp, clang/test/CIR/IR/invalid-vector-zero-size.cir, clang/test/CIR/IR/invalid-vector.cir
Backport `VectorType::verify` implementation with test for invalid cases
=> [CIR] Backport VectorType verifier

clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp, clang/test/CIR/CodeGen/AArch64/neon.c
Lower vqaddd_s64 and vqaddd_u64
=> [CIR][CIRGen][Builtin][Neon] Lower vqaddd_s64 and vqaddd_u64

clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
Add mlir Vec support to elementTypeIfVector
=> [CIR] Backport add mlir Vec to elementTypeIfVector

GettingStarted/upstream.md, _data/upstream_progress.yml
In this PR, I have added the types and attributes to the `upstream_progress.yml` file.
In a following PR, I will mark the already upstreamed functions as `true`.
You can see how it looks so far here:
https://andres-salamanca.github.io/clangir/GettingStarted/upstream.html
=> Populate types and attributes data

clang/lib/CIR/Dialect/Transforms/CIRSimplify.cpp, clang/test/CIR/Transforms/vector-splat.cir
Backporting the VecSplatOp simplifier from the upstream
=> [CIR] Backport VecSplatOp simplifier

clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/test/CIR/CodeGen/complex-builtins.cpp
Implement ChooseExpr for ComplexType
=> [CIR] Implement ChooseExpr for ComplexType

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/CIRCanonicalize.cpp, clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp, clang/test/CIR/Transforms/vector-ternary-fold.cir
Backporting the VecTernaryOp folder
=> [CIR] Backport VecTernaryOp folder

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/CIRCanonicalize.cpp, clang/test/CIR/Transforms/vector-shuffle-dynamic-fold.cir
Backporting the VecShuffleDynamicOp folder
=> [CIR] Backport VecShuffleDynamicOp folder

clang/include/clang/CIR/Dialect/IR/CIROps.td, clang/lib/CIR/Dialect/IR/CIRDialect.cpp, clang/lib/CIR/Dialect/Transforms/CIRCanonicalize.cpp, clang/test/CIR/Transforms/vector-cmp-fold.cir
Backporting the VecCmpOp folder
=> [CIR] Backport VecCmpOp folder

clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/test/CIR/CodeGen/complex-arithmetic.c
Fix emitCompoundAssignLValue with promotion RHS type
Ref: https://github.com/llvm/llvm-project/pull/150759#discussion_r2243697990
=> [CIR] Fix emitCompoundAssignLValue with promotion rhs type

clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/lib/CIR/CodeGen/CIRGenFunction.h, clang/test/CIR/CodeGen/complex-compound-assignment.cpp
Implement CompoundAssignment from ComplexType to ScalarType
=> [CIR] CompoundAssignment ComplexType to ScalarType

clang/test/CIR/CodeGen/OpenCL/spir-calling-conv.cl, clang/test/CIR/Lowering/call-op-call-conv.cir
=> [CIR][Test][NFC] Fix invalid testcases involving kernel calls in OpenCL kernels

clang/lib/CIR/CodeGen/CIRGenCall.cpp, clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp, clang/test/CIR/CodeGen/complex.cpp
Implement support for __real__ operator on complex rvalue
Issue #1819
=> [CIR] Implement support for __real__ operator on complex rvalue

_data/upstream_progress.yml
Update upstreaming progress section on GH Pages.
@bcardosolopes:
There’s no script or automation for updating this section. The workflow is manual:
1. Update the corresponding `.yml` file.
2. The HTML include automatically reflects the changes by checking the `complete` field.
https://github.com/llvm/clangir/blob/3633e7b65fc9bd3411ca387b96e4448d3a6b15a7/_includes/progress_section.html#L41-L54
=> [CIR][DOCS] Update upstreaming-progress

clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp, clang/test/CIR/CodeGen/opaque.cpp
Backport fixes in VisitAbstractConditionalOperator to handle OpaqueValueExpr from the upstream https://github.com/llvm/llvm-project/pull/157331
=> [CIR] Backport VisitOpaqueValueExpr support for Complex

clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp, clang/test/CIR/CodeGen/struct.cpp
Backport DesignatedInitUpdateExpr for AggregateExpr from the upstream
=> [CIR] Backport DesignatedInitUpdateExpr for AggregateExpr
