llvm/clangir

- clang/lib/CIR/CodeGen/CIRGenFunction.h
These were uninitialized, which led to intermittent test failures from
the use of uninitialized variables. Initialize them to `nullptr` as is
done with other member variables that are pointers to fix this.
I did a quick spot-check and didn't find other uninitialized variables
in the main CGF class itself. Lots of subclasses have uninitialized
member variables, but those are presumably expected to be initialized at
all points of construction, so we can leave them alone until they cause
any issues.
`ninja check-clang-cir` now passes with ASan+UBSan and MSan.
Fixes https://github.com/llvm/clangir/issues/829
> [CIR][CIRGen] Initialize more CGF member variables to nullptr

- clang/include/clang/CIR/Dialect/IR/CIRDataLayout.h
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/lib/CIR/Dialect/IR/CIRDataLayout.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp
- clang/test/CIR/CodeGen/bitfields_be.c
This PR adds aarch64 big endian support.
Basically the support for aarch64_be itself is expressed only in two extra cases for the switch statement and changes in the `CIRDataLayout` are needed to prove that we really support big endian.  Hence the idea for the test - I think the best way for proof is something connected with bit-fields, so we compare the results of the original codegen and ours.
> [CIR][Codegen] supports aarch64_be

- clang/include/clang/CIR/CIRToCIRPasses.h
- clang/include/clang/CIR/Dialect/Passes.h
- clang/include/clang/CIR/Dialect/Passes.td
- clang/lib/CIR/CodeGen/CIRPasses.cpp
- clang/lib/CIR/Dialect/Transforms/CIRCanonicalize.cpp
- clang/lib/CIR/Dialect/Transforms/CIRSimplify.cpp
- clang/lib/CIR/Dialect/Transforms/CMakeLists.txt
- clang/lib/CIR/FrontendAction/CIRGenAction.cpp
- clang/test/CIR/CodeGen/binop.cpp
- clang/test/CIR/CodeGen/complex.c
- clang/test/CIR/CodeGen/ternary.cpp
- clang/test/CIR/Transforms/builtin-assume.cir
- clang/test/CIR/Transforms/merge-cleanups.cir
- clang/test/CIR/Transforms/select.cir
- clang/test/CIR/Transforms/simpl.c
- clang/test/CIR/Transforms/simpl.cir
- clang/test/CIR/Transforms/ternary-fold.cir
- clang/test/CIR/Transforms/ternary-fold.cpp
- clang/test/CIR/mlirprint.c
- clang/tools/cir-opt/cir-opt.cpp
This PR splits the old `cir-simplify` pass into two new passes, namely `cir-canonicalize` and `cir-simplify` (the new `cir-simplify`). The `cir-canonicalize` pass runs transformations that do not affect CIR-to-source fidelity much, such as operation folding and redundant operation elimination. On the other hand, the new `cir-simplify` pass runs transformations that may significantly change the code and break high-level code analysis passes, such as more aggresive code optimizations.
This PR also updates the CIR-to-CIR pipeline to fit these two new passes. The `cir-canonicalize` pass is moved to the very front of the pipeline, while the new `cir-simplify` pass is moved to the back of the pipeline (but still before lowering prepare of course). Additionally, the new `cir-simplify` now only …
> [CIR] Split cir-simplify into two passes

- clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp
- clang/test/CIR/CodeGen/union-init.c
Currently the C style cast is not implemented/supported for unions. 
This PR adds support for union casts as done in `CGExprAgg.cpp`. I have also added an extra test in `union-init.c`.
> [CIR][CodeGen] Implement union cast

- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/test/CIR/CodeGen/vectype-issized.c
As title, if element type of vector type is sized, then the vector type should be deemed sized.
This would enable us generate code for neon without triggering assertion
> [CIR][CIRGen] Correct isSized predicate for vector type

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/arm-neon-directed-rounding.c
as title. 
This also added NeonType support for Float32
> [CIR][CIRGen][Builtin][Neon] Lower builtin_neon_vrnda_v and builtin_neon_vrndaq_v

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/attribute-annotate-multiple.cpp
__attribute__((annotate()) was only accepting integer literals, preventing some meta-programming usage for example.
This should be extended to some other kinds of types.
> [CIR][CIRGen] Allow constant evaluation of int annotation

- clang/lib/CIR/CodeGen/CIRGenStmt.cpp
- clang/test/CIR/CodeGen/goto.cpp
Close https://github.com/llvm/clangir/issues/876
We've already considered the case that there are random stmt after a switch case:
```
for (auto *c : compoundStmt->body()) {
if (auto *switchCase = dyn_cast<SwitchCase>(c)) {
res = buildSwitchCase(*switchCase, condType, caseAttrs);
} else if (lastCaseBlock) {
// This means it's a random stmt following up a case, just
// emit it as part of previous known case.
mlir::OpBuilder::InsertionGuard guardCase(builder);
builder.setInsertionPointToEnd(lastCaseBlock);
res = buildStmt(c, /*useCurrentScope=*/!isa<CompoundStmt>(c));
} else {
llvm_unreachable("statement doesn't belong to any case region, NYI");
}
lastCaseBlock = builder.getBlock();
if (res.failed())
break;
}
```
However, maybe this is an oversight, in the branch of ` if (lastCaseBlock)`, …
> [CIR][CodeGen] Handling multiple stmt followed after a switch case

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/aarch64-neon-vset.c
As title. 
Notice that for those intrinsics, just like OG, we do not lower to llvm intrinsics, instead, do vector insert.
The test case is partially from OG [aarch64-neon-vget.c](https://github.com/llvm/clangir/blob/85bc6407f559221afebe08a60ed2b50bf1edf7fa/clang/test/CodeGen/aarch64-neon-vget.c)
But, I did not do all signed and unsigned int tests because unsigned and signed of the same width essentially just use the same intrinsic ID thus exactly same code path as far as this PR concerns. 
I chose name aarch64-neon-vset.c as I intend to separate tests of vget_lane and vgetq_lane intrinsics into a different file 
called aarch64-neon-vget.c( IMHO, it's better).
> [CIR][CIRGen] Generate CIR for vset_lane and vsetq_lane intrinsics

- clang/include/clang/CIR/Dialect/IR/CIROpenCLAttrs.td
- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/test/CIR/CodeGen/OpenCL/kernel-unit-attr.cl
We need a target-independent way to distinguish OpenCL kernels in ClangIR. This PR adds a unit attribute `OpenCLKernelAttr` similar to the one in Clang AST.
This attribute is attached to the extra attribute dictionary of `cir.func` operations only. (Not for `cir.call`.)
> [CIR][Dialect][CodeGen] Add a unit attribute for OpenCL kernels

- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/lib/CIR/CodeGen/CIRGenStmt.cpp
- clang/test/CIR/CodeGen/goto.cpp
Motivation example:
```
extern "C" void action1();
extern "C" void action2();
extern "C" void case_follow_label(int v) {
switch (v) {
case 1:
label:
case 2:
action1();
break;
default:
action2();
goto label;
}
}
```
When we compile it, we will meet:
```
case Stmt::CaseStmtClass:
case Stmt::DefaultStmtClass:
assert(0 &&
"Should not get here, currently handled directly from SwitchStmt");
break;
```
in `buildStmt`. The cause is clear. We call `buildStmt` when we build the label stmt. 
To solve this, I think we should be able to build case stmt in buildStmt. But the new problem is, we need to pass the information like caseAttr and condType. So I tried to add such informations in CIRGenFunction as data member.
> [CIR][CodeGen] Handle the case of 'case' after label statement after  'case'

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/aarch64-neon-vdup-lane.c
- clang/test/CIR/CodeGen/aarch64-neon-vget.c
as title. 
This PR has simliar test case organization as to [PR882](https://github.com/llvm/clangir/pull/882)
Notice that comparing to OG, this PR combines cases for some pairs of  intrinsics such as 
BI__builtin_neon_vget_lane_f32 and BI__builtin_neon_vdups_lane_f32. 
They have the same code generated in OG and CIRGen
OG separate them into different case handling because it passes mnemonics which are different. CIRGen doesn't pass that so why not combine them.
> [CIR][CIRGen] Generate CIR for neon_vget and neon_vdup lane intrinsics

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/ABIInfo.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/test/CIR/CodeGen/aarch64-neon-vqadd.c
as title. 
Also add function  buildCommonNeonBuiltinExpr just like OG's emitCommonNeonBuiltinExpr. This might help consolidate neon cases and share common code. 
Notice:
-  I pretty much keep the skeleton of OG's emitCommonNeonBuiltinExpr at the cost of that we didn't use a few variables they calculate. They might help in the future. 
- The purpose of having CommonNeonBuiltinExpr is to reduce implementation code duplication. So far, we only have one type implemented, and it's hard for CIR to be more generic. But we should see if in future we can have different types of intrinsics share more generic code path.
> [CIR][CIRGen][Builtin][Neon] Lower neon vqadd_v 

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtin-abort.c
As title. 
The test case used is abort(), but it is from the real code. 
Notice: Since CIR implementation for NoReturn Call is pending to implement, the generated llvm code is like:
`define dso_local void @test() #1  {
call void @abort(), !dbg !8
ret void
}`
which is not right, right code should be like, 
`
`define dso_local void @test() #1  {
call void @abort(), !dbg !8
unreachable
}`
`
Still send this PR as Noreturn implementation is a separate issue.
> [CIR][CIRGen][Builtin] Allow CIRGen for builtin calls with math errorno override

- clang/lib/CIR/CodeGen/CIRGenBuilder.cpp
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtins.c
as title. 
The test cases are from [clang codegen test case](https://github.com/llvm/clangir/blob/52323c17c6a3708b3eb72651465f7d4b82f057e7/clang/test/CodeGen/builtins.c#L37)
> [CIR][CIRGen] Support __builtin_huge_val for float type

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRPasses.cpp
- clang/lib/CIR/Dialect/Transforms/CallConvLowering.cpp
- clang/lib/CIR/Dialect/Transforms/GotoSolver.cpp
- clang/lib/CIR/FrontendAction/CIRGenAction.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
Then we can observe the time consumed in different part of CIR. This patch is not complete. But I think it is fine given we can always add them easily.
> [CIR][CIRGen] Add time trace to several CIRGen pieces

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.h
`CIRGenModule::buildGlobal` --[rename]--> `CIRGenModule::getOrCreateCIRGlobal`
We already have `CIRGenModule::buildGlobal` that corresponds to `CodeGenModule::EmitGlobal`. But there is an overload of `buildGlobal` used by `getAddrOfGlobalVar`. Since this name is confusing, this PR rename it to `getOrCreateCIRGlobal`.
Note that `getOrCreateCIRGlobal` already exists. It is intentional to make the renamed function an overload to it. The reason here is that the renamed function is basically a wrapper of the original `getOrCreateCIRGlobal` with more specific parameters:
`getOrCreateCIRGlobal(decl, type, isDef)` --[call]--> `getOrCreateCIRGlobal(getMangledName(decl), type, decl->getType()->getAS(), decl, isDef)`
> [CIR][CodeGen][NFC] Rename the confusing `buildGlobal` overload

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenCXX.cpp
- clang/lib/CIR/CodeGen/CIRGenDecl.cpp
The missing feature flag for OpenCL has very few occurrences now. This PR rearranges them into proper pieces to better track them.
> [CIR][CodeGen][NFC] Break the missing feature flag for OpenCL into smaller pieces

- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/test/CIR/CodeGen/OpenCL/convergent.cl
- clang/test/CIR/CodeGen/OpenCL/nothrow.cl
Heterogeneous languages do not support exceptions, which corresponds to `nothrow` in ClangIR and `nounwind` in LLVM IR.
This PR adds nothrow attributes for all functions for OpenCL languages in CIRGen. The Lowering for it is already supported previously.
> [CIR][CodeGen] Add `nothrow` for functions in OpenCL languages

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/OpenCL/global.cl
- clang/test/CIR/CodeGen/cxx1z-inline-variables.cpp
- clang/test/CIR/CodeGen/global-constant.c
- clang/test/CIR/CodeGen/globals.c
- clang/test/CIR/CodeGen/temporaries.cpp
Fix #801 (the remaining `constant` part). Actually the missing stage is CIRGen.
There are two places where `GV.setConstant` is called:
* `buildGlobalVarDefinition`
* `getOrCreateCIRGlobal`
Therefore, the primary test `global-constant.c` contains a global definition and a global declaration with use, which should be enough to cover the two paths.
A test for OpenCL `constant` qualified global is also added. Some existing testcases need tweaking to avoid failure of missing constant.
> [CIR][CodeGen] Set constant properly for global variables

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/global-ptr.c
Consider the following code snippet `tmp.c`: 
```
#define N 3200
struct S {
double a[N];
double b[N];
} s;
double *b = s.b;
void foo() {
double x = 0;
for (int i = 0; i < N; i++)
x += b[i];
}
int main() {
foo();
return 0;
}
```
Running `bin/clang tmp.c -fclangir -o tmp && ./tmp` causes a segmentation fault.
I compared the LLVM IR with and without CIR and noticed a difference which causes this: 
`@b = global ptr getelementptr inbounds (%struct.S, ptr @s, i32 0, i32 1)` // no CIR 
`@b = global ptr getelementptr inbounds (%struct.S, ptr @s, i32 1)` // with CIR 
It seems there is a missing index when creating global pointers from structs. I have updated `Lowering/DirectToLLVM/LowerToLLVM.cpp`, and added a few tests.
> [CIR][Lowering] Fix Global Attr Lowering

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/atomic.cpp
as title.
Notice this is not target specific nor neon intrinsics.
> [CIR][CIRGen][Builtin] Implement builtin __sync_fetch_and_sub

- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
as title. 
The current implementation of this PR is use cir::CastOP integral casting to implement vector type truncation. Thus, LLVM lowering code has been change to accommodate it.
In addition.
Added code into [CIRGenBuiltinAArch64.cpp](https://github.com/llvm/clangir/pull/909/files#diff-6f7700013aa60ed524eb6ddcbab90c4dd288c384f9434547b038357868334932)  to make it more similar to OG.
```
mlir::Type ty = vTy;
if (!ty)
```
Added test case into neon.c as the file already contains similar vector move test cases such as vmovl
> [CIR][CIRGen][Builtin][Neon] Lower BI__builtin_neon_vmovn_v

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-ldst.c
as title. 
Also changed [neon-ldst.c](https://github.com/llvm/clangir/compare/main...ghehg:clangir-llvm-ghehg:macM3?expand=1#diff-ea4814b6503bff2b7bc4afc6400565e6e89e5785bfcda587dc8401d8de5d3a22)
to make it have the same RUN options as OG [clang/test/CodeGen/aarch64-neon-intrinsics.c](https://github.com/llvm/clangir/blob/main/clang/test/CodeGen/aarch64-neon-intrinsics.c)
Those options help us to avoid checking load/store pairs thus make the test less verbose and easier to compare against OG.
> [CIR][CIRGen][Builtin][Neon] Lower neon vst1q_lane and vst1_lane

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/derived-to-base.cpp
- clang/test/CIR/CodeGen/multi-vtable.cpp
- clang/test/CIR/CodeGen/vtable-rtti.cpp
- clang/test/CIR/Lowering/derived-to-base.cpp
Implement derived-to-base address conversions for non-virtual base classes.  The code gen for this situation was only implemented when the offset was zero, and it simply created a `cir.base_class_addr` op for which no lowering or other transformation existed.
Conversion to a virtual base class is not yet implemented.
Two new fields are added to the `cir.base_class_addr` operation: the byte offset of the necessary adjustment, and a boolean flag indicating whether the source operand may be null.  The offset is easy to compute in the front end while the entire path of intermediate classes is still available.  It would be difficult for the back end to recompute the offset.  So it is best to store it in the operation.  The null-pointer check is best done late in the lowering process.  But …
> [CIR] Derived-to-base conversions

- clang/lib/CIR/Dialect/IR/CIRDataLayout.cpp
- clang/test/CIR/CodeGen/array.c
- clang/test/CIR/CodeGen/array.cpp
- clang/test/CIR/CodeGen/bool.c
- clang/test/CIR/CodeGen/c11atomic.c
- clang/test/CIR/CodeGen/evaluate-expr.c
- clang/test/CIR/CodeGen/globals-neg-index-array.c
- clang/test/CIR/CodeGen/globals.c
- clang/test/CIR/CodeGen/packed-structs.c
- clang/test/CIR/CodeGen/stmtexpr-init.c
- clang/test/CIR/CodeGen/string-literals.c
- clang/test/CIR/CodeGen/struct.c
- clang/test/CIR/CodeGen/struct.cpp
- clang/test/CIR/CodeGen/union-init.c
- clang/test/CIR/Lowering/struct-init.c
The ABI alignment and preferred alignment fields were swapped (per [1],
the ABI alignment should be 1 and the preferred alignment should be 8),
leading to incorrect struct size calculations.
Fixes https://github.com/llvm/clangir/issues/911
Fixes https://github.com/llvm/clangir/issues/915
Fixes https://github.com/llvm/clangir/issues/916
Fixes https://github.com/llvm/clangir/issues/917
Fixes https://github.com/llvm/clangir/issues/918
Fixes https://github.com/llvm/clangir/issues/919
Fixes https://github.com/llvm/clangir/issues/920
Fixes https://github.com/llvm/clangir/issues/921
Fixes https://github.com/llvm/clangir/issues/922
Fixes https://github.com/llvm/clangir/issues/925
Fixes https://github.com/llvm/clangir/issues/926
Fixes https://github.com/llvm/clangir/issues/929
Fixes …
> fixup! [CIR][ABI] Implement basic struct CC lowering for x86_64

- clang/include/clang/CIR/Dialect/IR/CIRTypes.h
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/test/CIR/IR/invalid.cir
After 7359a6b7996f92e6659418d3d2e5b57c44d65e37, we need to rename verify
to verifyInvariants.
Fixes https://github.com/llvm/clangir/issues/923
> fixup! [CIR][CIRGen] Support mutable and recursive named records

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/call.cir
- clang/test/CIR/Lowering/hello.cir
After 5da431008222e2653f618f3a112af58a94417251, the LLVM dialect
requires the variadic callee type to be present for variadic calls. The
op builders take care of this automatically if you pass the function
type, so change our lowering logic to do so. Add tests for this as well
as a missing test for indirect function call lowering.
Fixes https://github.com/llvm/clangir/issues/913
Fixes https://github.com/llvm/clangir/issues/933
> [Lowering][DirectToLLVM] Fix calling variadic functions

- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/test/CIR/CodeGen/function-to-pointer-decay.c
See the test for the reproducer. It would crash due the NYI.
See https://github.com/llvm/llvm-project/blob/327124ece7d59de56ca0f9faa2cd82af68c011b9/clang/lib/CodeGen/CGExpr.cpp#L1295-L1373, I found we've implemented all the cases in CGExpr.cpp. IIUC, I think we can remove the NYI.
> [CIR] [CodeGen] Remove NYI in buildPointerWithAlignment

- clang/include/clang/CIR/Dialect/Passes.h
- clang/include/clang/CIR/Dialect/Passes.td
- clang/lib/CIR/CodeGen/CIRPasses.cpp
- clang/lib/CIR/Dialect/Transforms/CMakeLists.txt
- clang/lib/CIR/Dialect/Transforms/HoistAllocas.cpp
- clang/test/CIR/CodeGen/AArch64/neon-ldst.c
- clang/test/CIR/CodeGen/AArch64/neon-misc.c
- clang/test/CIR/CodeGen/AArch64/neon.c
- clang/test/CIR/CodeGen/aarch64-neon-vdup-lane.c
- clang/test/CIR/CodeGen/builtin-bit-cast.cpp
- clang/test/CIR/CodeGen/initlist-ptr-ptr.cpp
- clang/test/CIR/CodeGen/initlist-ptr-unsigned.cpp
- clang/test/CIR/CodeGen/try-catch-dtors.cpp
- clang/test/CIR/Lowering/OpenMP/parallel.cir
- clang/test/CIR/Lowering/dot.cir
- clang/test/CIR/Lowering/goto-interscope.c
- clang/test/CIR/Lowering/scope.cir
Close https://github.com/llvm/clangir/issues/883. See the above issue for details
> [CIR][Lowering] Introduce HoistAllocasPass

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/no-pie.c
The title describes the purpose of the PR. 
The logic was gotten from the original CodeGen, and I added a test to check that `-fno-PIE` is indeed enabled.
> [CIR][CodeGen] Enable -fno-PIE

- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/test/CIR/CodeGen/fp16-ops.c
This PR adds support for the `__fp16` type. CIRGen and LLVM lowering is included.
Resolve #900 .
> [CIR][CIRGen] Add support for __fp16 type

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/atomic.cpp
as title. 
Actually just follow the way in `makeBinaryAtomicValue` in the same file which did the right thing by creating SInt or UInt based on first argument's signess.
> [CIR][CIRGen][Builtin] Support unsigned type for _sync_(bool/val)_compare_and_swap 

- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/test/CIR/CodeGen/kr-func-promote.c
I tried to run llvm-test-suite and turned out that there are many tests fail with segfault due to old C style (let's remember Kernighan and Ritchie) . This PR fix it by the usual copy-pasta from the original codegen :)
So let's take a look at the code:
```
void foo(x) short x; {}
int main() {
foo(4); 
return 0;
}
```
and CIR for `foo` function is:
```
cir.func  @foo(%arg0: !s32i) {
%0 = cir.alloca !s16i, !cir.ptr<!s16i>, ["x", init] 
%1 = cir.cast(bitcast, %0 : !cir.ptr<!s16i>), !cir.ptr<!s32i>
cir.store %arg0, %1 : !s32i, !cir.ptr<!s32i>
cir.return
}
```
We bitcast the **address** (!!!) and store a value of a bigger size there.
And now everything looks fine:
```
cir.func no_proto  @foo(%arg0: !s32i) {
%0 = cir.alloca !s16i, !cir.ptr<!s16i>, ["x", init] 
%1 = cir.cast(integral, %arg0 : …
```
> [CIR][CodeGen] kr-style for function arguments

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/test/CIR/CodeGen/assign-operator.cpp
- clang/test/CIR/CodeGen/basic.cpp
- clang/test/CIR/CodeGen/bitfields.cpp
- clang/test/CIR/CodeGen/cond.cpp
- clang/test/CIR/CodeGen/const-alloca.cpp
- clang/test/CIR/CodeGen/coro-task.cpp
- clang/test/CIR/CodeGen/ctor-member-lvalue-to-rvalue.cpp
- clang/test/CIR/CodeGen/derived-to-base.cpp
- clang/test/CIR/CodeGen/lvalue-refs.cpp
- clang/test/CIR/CodeGen/new.cpp
- clang/test/CIR/CodeGen/rangefor.cpp
- clang/test/CIR/CodeGen/return.cpp
- clang/test/CIR/CodeGen/temporary-materialization.cpp
This PR tries to give a simple initial implementation for eliminating redundant loads of constant objects, an idea originally posted by OfekShilon.
Specifically, this PR adds a new unit attribute `const` to the `cir.alloca` operation.  Presence of this attribute indicates that the alloca-ed object is declared `const` in the input source program. CIRGen is updated accordingly to start emitting this new attribute.
> [CIR][CIRGen] Add const attribute to alloca operations

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/vectype-ext.cpp
- clang/test/CIR/Lowering/vectype.cpp
They should use PoisonOp (which becomes PoisonValue in LLVMIR) as it is the OG's choice. 
Proof:
We generate VecCreateOp [here ](https://github.com/llvm/clangir/blob/2ca12fe5ec3a1e7279256f069010be2d68200585/clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp#L1975)
And it's OG counterpart is [here](https://github.com/llvm/clangir/blob/2ca12fe5ec3a1e7279256f069010be2d68200585/clang/lib/CodeGen/CGExprScalar.cpp#L2096)
OG uses PoisonValue. 
As to VecSplatOp, OG unconditionally [chooses PoisonValue ](https://github.com/llvm/clangir/blob/2ca12fe5ec3a1e7279256f069010be2d68200585/llvm/lib/IR/IRBuilder.cpp#L1204)
A even more solid proof for this case is that 
when we use OG to generate code for our test case I changed in this PR , its always using poison instead of undef as far as VecSplat and VecCreate …
> [CIR][Lowering] VecCreateOp and VecSplatOp lowering choose LLVM:PoisonOp

- clang/test/CIR/CodeGen/annotations-var.c
as title.
Base on my experience of [this type of test ](https://github.com/llvm/clangir/blob/a7ac2b4e2055e169d9f556abf5821a1ccab666cd/clang/test/CIR/CodeGen/attribute-annotate-multiple.cpp#L51),
The number of characters varies in this line as it's about full file path which changes during environment.
> [CIR][NFC][Testing] Fix test failure

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/ptrstride.cir
After recent rebases (likely as a result of [1]), the LLVMIR stride
operand can be generated by an unrealized_conversion_cast whereas the
CIR operand is coming directly from a block argument (and thus has no
defining op), so we need to separately check the CIR operand for the
existence of a defining op.
[1] https://github.com/llvm/llvm-project/commit/2d50029f986da1fdc9cb88cd8a1070aa086dc6b6
> fixup! [CIR][LowerToLLVM] Fix crash in PtrStrideOp lowering

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-misc.c
as title. 
The generated code is the same as Clang codeden except in a small discrepancy when GEP:
OG generates code like this: 
`%6 = getelementptr inbounds <4 x i16>, ptr %retval.i, i32 1`
CIR generates a bit differently:
`%6 = getelementptr <4 x i16>, ptr %retval.i, i64 1`
Ptr offest might be trivial because choosing i64 over i32 as index type seems to be LLVM Dialect's choice.
The lack of `inbounds` keyword might be an issue as `mlir::cir::PtrStrideOp` is currently not lowering to  LLVM:GEPOp with `inbounds` attribute as `mlir::cir::PtrStrideOp` itself has no `inbounds`. It's probably because there was no need for it though we do have an implementation of [`CIRGenFunction::buildCheckedInBoundsGEP` ](https://github.com/llvm/clangir/blob/10d6f4b94da7e0181a070f0265d079419d96cf78/clang/lib …
> [CIR][CIRGen][Builtin][Neon] Lower neon_vtrn and neon_vtrnq

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-ext-mov.c
as title. 
There are two highlights of the PR
1. The PR introduced a new test file to cover neon intrinsics that move data, which is a big category. This would the 5th neon test file. And we're committed to keep total number of neon test files within 6.  This file uses another opt option instcombine, which makes test LLVM code more concise, and our -fclangir generated LLVM code would be identical to OG with this. It looks like OG did some instcombine optimization.
2. `getIntFromMLIRValue` helper function could be substituted by [`mlir::cir::IntAttr getConstOpIntAttr` in CIRGenAtomic.cpp](https://github.com/llvm/clangir/blob/24b24557c98d1c031572a567b658cfb6254f8a89/clang/lib/CIR/CodeGen/CIRGenAtomic.cpp#L337). The function `mlir::cir::IntAttr getConstOpIntAttr` is doing more than …
> [CIR][CIRGen][Builtin][Neon] Lower neon_vext_v and neon_vextq_v

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
This PR also adds attribute 
> poison
to VecSplatOp. The reason is that Clang codegen creates initial value of vector to be splatted as poison value for the intrinsic vld1_dup and vld1q_dup. So when CIR lowers these intrinsics, we need to do the same.
> [CIR][CIRGen][Builtin][Neon] Lower vld1_dup and vld1q_dup

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-arith.c
as title. 
Other than functional change reflected in the title. This PR refactored Neon Built in code in clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp a bit to make it cleaner. 
Also changed RUNOption of test file clang/test/CIR/CodeGen/AArch64/neon-arith.c to make test more concise, and easy to compare against OG (to compare, just remove -fclangir from llvm gen part of RUN, and the test should still pass)
> [CIR][CIRGen][Builtin][Neon] Lower neon_vpadd_v and neon_vpaddq_v into llvm intrinsic

- _config.yml
This is a clone of the original rundocs/jekyll-rtd-theme, which got deleted. It should restore our previous look and feel while still allowing updates. https://smeenai.github.io/clangir/ shows what it looks like.
> [docs] Use clearpathrobotics/jekyll-rtd-theme

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.h
- clang/test/CIR/CodeGen/linkage.c
This is the usual copy-paste-modify from CodeGen, though I changed all
the variable names to conform to our new style. All these functions
should be pulled out as common helpers when we're upstream.
> [CIR][CIRGen] Implement CIRGenModule::shouldEmitFunction

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
https://github.com/llvm/llvm-project/commit/1d0bd8e51be2627f79bede54735c38b917ea04ee
moves a conditional from CodeGen to AST, and this follows suit for
consistency. (Our support for the Microsoft ABI is NYI anyway; this is
just to make things simpler to follow when matching up logic between
CodeGen and CIRGen.)
> [CIR][CIRGen] Port 1d0bd8e51be2627f79bede54735c38b917ea04ee

- clang/test/CIR/CodeGen/builtin-assume.cpp
- clang/test/CIR/CodeGen/builtin-bits.cpp
- clang/test/CIR/CodeGen/builtin-constant-evaluated.cpp
- clang/test/CIR/CodeGen/builtins-overflow.cpp
There is no change to testing functionality. This refacot let those files have the same Run options that is easier to maintain and extend.
> [CIR][CIRGen][NFC] Consolidate RUN lines for builtin tests

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/str.c
Close https://github.com/llvm/clangir/issues/975
See the attached test case for example
> [CIR] [Lowering] care trailing zero for lowering constant array

- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenTypeCache.h
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/test/CIR/CodeGen/int128.cpp
- clang/test/CIR/IR/invalid.cir
This PR adds initial support for the `__int128` type. The `!cir.int` type is extended to support 128-bit integer types.
This PR comes with a simple test that verifies the CIRGen and LLVM lowering of `!s128i` and `!u128i` work.
Resolve #953 .
> [CIR] Add support for __int128 type

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/visibility-attribute.c
LLVM's verifier enforces this, which was previously causing us to fail
verification. This is a bit of a band-aid; the overall linkage and
visibility setting flow needs some work to match the original.
> [CIR][CIRGen] Ensure default visibility for local linkage functions

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
- clang/test/CIR/CodeGen/vectype.cpp
- clang/test/CIR/IR/cir-ops.cir
- clang/test/CIR/IR/invalid.cir
- clang/test/CIR/Lowering/vectype.cpp
As title, but important step in this PR is to allow CIR ShiftOp to take vector of int type as input type. As result, I added a verifier to ShiftOp with 2 constraints
1. Input type either all vector or int type. This is consistent with LLVM::ShlOp, vector shift amount is expected.
2. In the spirit of C99 6.5.7.3, shift amount type must be the same as result type, the if vector type is used. (This is enforced in LLVM lowering for scalar int type).
> [CIR][CIRGen][Builtin][Neon] Lower neon_vshl_n_v and neon_vshlq_n_v

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/TargetInfo.h
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/builtin-isfpclass.c
- clang/test/CIR/Lowering/builtin-isfpclass.c
The llvm's intrinsic `llvm.is.fpclass` is used to support multiple float point builtins: https://clang.llvm.org/docs/LanguageExtensions.html#builtin-isfpclass
> The `__builtin_isfpclass()` builtin is a generalization of functions
> isnan, isinf, isfinite and some others defined by the C standard. It tests
> if the floating-point value, specified by the first argument, falls into
> any of data classes, specified by the second argument.
I meant to support this by creating IntrinsicCallOp directly. But I can't make it due to https://github.com/llvm/clangir/issues/480 since the return type of the intrinsic will mismatch. So I have to create a new Op for it. But I feel it might not be too bad. At least it is more explicit and more expressive.
> [CIR] [CodeGen] Introduce IsFPClassOp to support builtin_isfpclass

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/annotations-var.c
Now CIR supports annotations for both globals and locals. They all should just use the same set of annotation related globals including file name string, annotation name string, and arguments. This PR makes sure this is the case. 
FYI: for the test case we have, OG generates [ code ](https://godbolt.org/z/Ev5Ycoqj1), pretty much the same code except annotation variable names.
This would fix the crash like
> error: redefinition of symbol named '.str.annotation'
> fatal error: error in backend: The pass manager failed to lower CIR to LLVMIR dialect!
> [CIR][CIRGen][Lowering] Use same set of annotation-related global vars for source code global and local vars

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/globals-neg-index-array.c
Previously we didn't generate the index for array correct.
The previous test is incorrect already:  globals-neg-index-array.c
```
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -emit-cir %s -o %t.cir
// RUN: FileCheck --input-file=%t.cir %s
// RUN: %clang_cc1 -triple x86_64-unknown-linux-gnu -fclangir -emit-llvm %s -o %t.ll
// RUN: FileCheck --check-prefix=LLVM --input-file=%t.ll %s
// RUN: %clang_cc1 -x c++ -triple x86_64-unknown-linux-gnu -emit-cir %s -o %t.cir
// RUN: FileCheck --input-file=%t.cir %s
// RUN: %clang_cc1 -x c++ -triple x86_64-unknown-linux-gnu -fclangir -emit-llvm %s -o %t.ll
// RUN: FileCheck --check-prefix=LLVM --input-file=%t.ll %s
struct __attribute__((packed)) PackedStruct {
char a1;
char a2;
char a3;
};
struct PackedStruct packed[10];
char *packed_element = …
```
> [ClangIR][Lowering] Handle lowered array index

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/test/CIR/CodeGen/binassign.cpp
- clang/test/CIR/CodeGen/binop.cpp
- clang/test/CIR/CodeGen/vectype.cpp
The MLIR docs at https://mlir.llvm.org/docs/DefiningDialects/Operations/#literals specify that "An empty literal `` may be used to remove a space that is inserted implicitly after certain literal elements", so I inserted one before the `right` literal to remove the extra space that was being printed. Oddly, the bug is also fixed by inserting an empty literal _after_ the `left` literal, which leads me to believe that tablegen is inserting an implicit space after the `left` literal.
> [CIR][CIRGen] Removed extra space in "cir.shift( right)" (#997)

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenAtomic.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/lib/CIR/CodeGen/CIRGenStmt.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/CIRCanonicalize.cpp
- clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp
- clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp
- clang/test/CIR/CodeGen/atomic-runtime.cpp
- clang/test/CIR/CodeGen/goto.cpp
- clang/test/CIR/CodeGen/switch-gnurange.cpp
- clang/test/CIR/CodeGen/switch.cpp
- clang/test/CIR/IR/invalid.cir
- clang/test/CIR/IR/switch.cir
- clang/test/CIR/Lowering/nested-switch.cpp
- clang/test/CIR/Lowering/switch-while.c
- clang/test/CIR/Lowering/switch.cir
- clang/test/CIR/Transforms/merge-cleanups.cir
- clang/test/CIR/Transforms/switch.cir
Close https://github.com/llvm/clangir/issues/522
This solves the issue we can't handle `case` in nested scopes and we can't handle if the switch body is not a compound statement.
The core idea of the  patch is to introduce the `cir.case` operation to the language. Then we can get the cases by traversing the body of the `cir.switch` operation easily instead of counting the regions and the attributes.
Every `cir.case` operation has a region and now the `cir.switch` has only one region too. But to make the analysis and optimizations easier, I add a new concept `simple form` here. That a simple `cir.switch` operation is: all the `cir.case` operation owned by the `cir.switch` lives in the top level blocks of the `cir.switch` region and there is no other operations except the ending …
> [ClangIR][CIRGen] Introduce CaseOp and refactor SwitchOp

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
In this PR, also changed `buildNeonShiftVector` to allow it generates negative shift values. When the shift value is negative, the shift amount vector is not used in any ShiftOp of IR (as they don't need sign to know shift direction), instead, it is just input argument to shift intrinsic function call.
> [CIR][CIRGen][Builtin][Neon] Lower neon_vrshr_n and vrshrq_n to llvm intrinsics

- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/CodeGen/attribute-annotate-multiple.cpp
- clang/test/CIR/CodeGen/goto.cpp
- clang/test/CIR/CodeGen/temporaries.cpp
- clang/test/CIR/CodeGen/vtt.cpp
- clang/test/CIR/Lowering/loops-with-break.cir
- clang/test/CIR/Transforms/ternary-fold.cpp
This PR fixes the notorious double whitespaces introduced by visibility attribute, for `cir.func` only.
It uses "leading whitespace" for every print. And the printing of visibility attr is properly guarded by a check of `!isDefault()`.
Double whitespaces in test files are removed.
> [CIR][Dialect][NFC] Fix double whitespaces in `cir.func` assembly

- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/CodeGen/AArch64/neon-misc.c
In addition, this PR enables ZeroAttr of vector type so that CIR can generate a vector initialized with all zero values.
> [CIR][CIRGen][Builtin][Neon] Lower neon_vtst_v and neon_vtstq_v

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/libc.c
- clang/test/CIR/IR/invalid.cir
due to the issue described in https://github.com/llvm/clangir/issues/1018, 
the MLIR lowering for `memmove` has been excluded in this patch.
> [CIR][CIRGen] Add support for memmove

- clang/include/clang/CIR/ABIArgInfo.h
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfo.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfo.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRToCIRArgMapping.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerCall.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/AArch64.cpp
- clang/test/CIR/CallConvLowering/AArch64/aarch64-cc-structs.c
This PR adds a support for the return values of struct types > 128 bits in size.
As usually, lot's of copy-pasted lines from the original codegen, except the `AllocaOp`  replacement for the return value.
> [CIR][ABI][AArch64] support for return struct types greater than 128 bits

- clang/lib/CIR/Dialect/Transforms/CallConvLowering.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.h
- clang/test/CIR/CallConvLowering/x86_64/fptrs.c
This PR adds a support for calls by  function pointers.
@sitio-couto   I think would be great if you'll also take a look
> [CIR][ABI][Lowering] Supports call by function pointer in the calling convention lowering pass

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/test/CIR/CodeGen/new-null.cpp
The added test cases are from [OG's counterpart](https://github.com/llvm/clangir/blob/f9c5477ee10c9bc005ffbfe698691cc02193ea81/clang/test/CodeGenCXX/builtin-operator-new-delete.cpp#L7). I changed run option to -std=c++17 to support [std::align_val_t](https://en.cppreference.com/w/cpp/memory/new/align_val_t)
> [CIR][CIRGen][Builtin] Support BI__builtin_operator_new and BI__builtin_operator_delete

- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRToCIRArgMapping.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp
- clang/test/CIR/CallConvLowering/x86_64/int128.cpp
This PR adds calling convention lowering support for the int128 type on x86_64.
This is a follow up on #953 .
> [CIR][ABI][Lowering] Add CCLower support for int128 on x86_64

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Note in the test file, `test_vshrq_n_s32_32` and `test_vshr_n_u16_16` are addition to what traditional clang code gen already has. 
They tested the case where shift amount is the same as element size ( compiler errors if shift amount is greater than elem size). OG didn't test that case here, but [has somewhat tested elsewhere](https://github.com/llvm/clangir/blob/3d16a0f8499c43497a18a46d838313ab4deeadea/clang/test/CodeGen/aarch64-neon-shifts.c#L23)
> [CIR][CIRGen][Builtin][Neon] Lower neon_vshr_n_v and neon_vshrq_n_v

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/nested-union-array.c
- clang/test/CIR/CodeGen/union-init.c
Reproducer:
```
struct nested
{
union {
const char *single;
const char *const *multi;
} output;
};
static const char * const test[] = {
"test",
};
const struct nested data[] = 
{
{
{
.multi = test,
},
},
{
{
.single = "hello",
},
},
};
```
ClangIR now failed to recognize `data` as an array since it failed to recognize the initializer for union. This comes from a fundamental  difference between CIR and LLVM IR. In LLVM IR, the union is simply a struct with the largest member. So it is fine to have only one init element. But in CIR, the union has the information for all members. So if  we only pass a single init element, we may be in trouble. We solve the problem by appending placeholder attribute for the uninitialized fields.
> [ClangIR][CIRGen] Handle nested union in arrays of struct

- clang/include/clang/CIR/CIRGenerator.h
- clang/lib/CIR/CodeGen/CIRGenModule.h
- clang/lib/CIR/CodeGen/CIRGenVTables.cpp
- clang/lib/CIR/CodeGen/CIRGenerator.cpp
- clang/test/CIR/CodeGen/vtable-emission.cpp
We were missing an override for this previously and thus not emitting
vtables when key functions were defined.
> [CIR][CIRGen] Emit required vtables

- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/AArch64.cpp
- clang/test/CIR/CallConvLowering/AArch64/aarch64-cc-structs.c
This PR adds a support for some basic cases for struct types passed by value. 
The hardest part probably is `createCoercedStore` function, which I rewrote significantly in order to make it closer to the orignal codegen.
> [CIR][ABI][AArch64][Lowering] Initial support for passing struct types

- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/AArch64.cpp
- clang/test/CIR/CallConvLowering/AArch64/aarch64_be-cc-structs.c
This PR adds a support return struct as a value for one missed case for AArch64 big endian arch
> [CIR][ABI][AArch64] convers aarch64_be return struct case

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/builtins.cpp
This should fix NYI like `BI__builtin_char_memchr NYI UNREACHABLE executed at clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp:1402`
The test is from [OG](https://github.com/llvm/clangir/blob/3ef67c19917ad26ed8b19d4d13a43458a952fddb/clang/test/CodeGenCXX/builtins.cpp#L64) 
see builtin's prototype 
[char *__builtin_char_memchr(const char *haystack, int needle, size_t size); ](https://clang.llvm.org/docs/LanguageExtensions.html#string-builtins)
> [CIR][CIRGen][Builtin] Support __builtin_char_memchr

- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
fix https://github.com/llvm/clangir/issues/1057
> [CIR] fix getTypeSizeInBits with fp80 and fp128

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/array.cpp
- clang/test/CIR/CodeGen/globals.cpp
- clang/test/CIR/CodeGen/hello.c
- clang/test/CIR/CodeGen/initlist-ptr-ptr.cpp
- clang/test/CIR/CodeGen/wide-string.cpp
In OG CodeGen, string literals has `private` linkage as default (marked by `cir_private` in CIR assembly). But CIR uses `internal`, which is probably an ancient typo.
This PR keeps align with it and thus modifies the existing test files.
> [CIR][CodeGen] Fix the default linkage of string literals

- clang/include/clang/CIR/ABIArgInfo.h
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerCall.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/AArch64.cpp
- clang/test/CIR/CallConvLowering/AArch64/aarch64-cc-structs.c
This PR adds a partial support  for so-called indirect function arguments for struct types with size > 128 bits for aarch64.
The hard part is that it's not one-to-one copy from the original codegen, but the code is inspired by it of course.
In the original codegen there is no much job is done for the indirect arguments inside the loop in the `EmitFunctionProlog`, and  additional alloca is added in the end, in the call for `EmitParamDecl` function. 
In our case, for the indirect argument (which is a pointer) we replace the original alloca with a new one, and store the pointer in there. And replace all the uses of the old alloca with the load from the new one, i.e. in both cases users works with the pointer to a structure.
Also, I added several missed features in the …
> [CIR][ABI][AArch64][Lowering] support for passing struct types > 128 bits

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/dtors-scopes.cpp
- clang/test/CIR/CodeGen/globals.cpp
- clang/test/CIR/CodeGen/initlist-ptr-ptr.cpp
- clang/test/CIR/CodeGen/predefined.cpp
- clang/test/CIR/IR/global.cir
- clang/test/CIR/IR/invalid.cir
- clang/test/CIR/Lowering/globals.cir
This PR changes the naming format of string literals from `.str1` to `.str.1`, making it easier to reuse the existing testcases of OG CodeGen.
> [CIR][CodeGen] Use the same SSA name as OG's for string literals

- clang/include/clang/CIR/Target/x86.h
- clang/lib/CIR/CodeGen/TargetInfo.cpp
It's currently polluting the `cir` namespace with very generic symbols like `Integer` and `Memory`, which is pretty confusing. `X86_64ABIInfo` already has `Class` alias for `X86ArgClass`, so we can use that alias to qualify all uses.
> [CIR] Make X86ArgClass an `enum class`

- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
> Revert "[CIR] fix getTypeSizeInBits with fp80 and fp128"

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/lib/CIR/Dialect/IR/CIRAttrs.cpp
- clang/test/CIR/IR/attribute.cir
- clang/test/CIR/IR/float.cir
- clang/test/CIR/IR/invalid.cir
- clang/test/CIR/Lowering/class.cir
- clang/test/CIR/Lowering/struct.cir
This commit extends the support for floating point attributes parsing by using
the new `AsmParser::parseFloat(fltSemnatics, APFloat&)` interface.
As a drive-by, this commit also harmonizes the cir.fp print/parse namespace
usage, and adds the constraint of supporting only "CIRFPType"s for cir.fp in
tablegen instead of verifying it manually in the parsing logic.
---
This commit is based on top of a to-be-upstreamed commit which extends the upstream MLIR float type parsing. Upstream parsing of float type has full capability only through parsing the Builtin Dialect's `FloatAttr`. Thos commit exposes the same capabilities to downstream users.
---
This PR should resolve (at least) `GCC-C-execute-ieee-fp-cmp-2` and `GCC-C-execute-ieee-fp-cmp-4`, paving the way to other `GCC-C-execute-ieee-*` …
> [CIR] Extend support for floating point attributes

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-crypto.c
The test case is from [clang/test/CodeGen/neon-crypto.c](https://github.com/llvm/clangir/blob/dbf320e5c3db0410566ae561067c595308870bad/clang/test/CodeGen/neon-crypto.c#L28)
Need a dedicated test file as RunOptions has crypto related target features.
> [CIR][CIRGen][Builtin][Neon] Lower neon_vaesmcq_u8

- clang/lib/CIR/Dialect/Transforms/TargetLowering/RecordLayoutBuilder.cpp
- clang/test/CIR/CallConvLowering/AArch64/union.c
As the title says, this PR adds support for unions for AArch64 lowering. The idea is basically the same as the [original](https://github.com/llvm/clangir/blob/dbf320e5c3db0410566ae561067c595308870bad/clang/lib/AST/RecordLayoutBuilder.cpp#L2111) codegen, and I added a couple of tests.
> [CIR][ABI][AArch64][Lowering] Support unions 

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/OpenCL/printf.cl
- clang/test/CIR/CodeGen/OpenCL/str_literals.cl
This PR supports string literals in OpenCL end to end, making it possible to use `printf`. This involves two changes:
* In CIRGen, ensure we create the global symbol for string literals with correct `constant` address space.
* In LowerToLLVM, make the lowering of `GlobalViewAttr` aware of the upstream address space.
Other proper refactors are also applied.
Two test cases from OG CodeGen are reused. `str_literals.cl` is the primary test, while `printf.cl` is the bonus one.
> [CIR][CodeGen][LowerToLLVM] String literals for OpenCL

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/builtin-signbit.c
This patch adds support for the `__builtin_signbit` intrinsic. The intrinsic requires special handling for PowerPC; however, since ClangIR does not currently support PowerPC, this handling is omitted in this implementation.
> [CIR][CIRGen] support builtin signbit

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/builtins-memory.c
The test code is from [OG's clang/test/CodeGen/builtins-memcpy-inline.c](https://github.com/llvm/clangir/blob/5f1afad625f1292ffcf02c36402d292c46213c86/clang/test/CodeGen/builtins-memcpy-inline.c#L7)
Also, a little design choice when introducing MemCpyInlineOp, I chose to let it inherit CIR_MemCpyOp, so in future when we optimize MemCpy like Ops, we'd have cleaner and more unified code. 
However, the cost is that during LLVM lowering I'd have to convert the length from ConstOp into IntegerAttr as that's [what LLVM dialect is expecting](https://mlir.llvm.org/docs/Dialects/LLVM/#llvmintrmemcpyinline-llvmmemcpyinlineop)
> [CIR][CIRGen][Builtin] Support __builtin_memcpy_inline

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenDecl.cpp
- clang/test/CIR/CodeGen/stmtexpr-init.c
When emitting initializers for static declarations, it's essential to ensure that the `cir.global` operation aligns its type with that of the initializer.
The original approach creates a new global op and copies every attribute from the old one. But just `setSymType` should work well.
This also removes missing feature flags there.
> [CIR][CodeGen][NFC] Simplify replacing initializer of static decls

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/CallConvLowering/AArch64/struct.c
- clang/test/CIR/CodeGen/AArch64/neon-arith.c
- clang/test/CIR/CodeGen/annotations-var.c
- clang/test/CIR/CodeGen/array-init.c
- clang/test/CIR/CodeGen/attribute-annotate-multiple.cpp
- clang/test/CIR/CodeGen/cxx1z-inline-variables.cpp
- clang/test/CIR/CodeGen/global-new.cpp
- clang/test/CIR/CodeGen/globals-neg-index-array.c
- clang/test/CIR/CodeGen/kr-func-promote.c
- clang/test/CIR/CodeGen/member-init-struct.cpp
- clang/test/CIR/CodeGen/no-pie.c
- clang/test/CIR/CodeGen/paren-list-init.cpp
- clang/test/CIR/CodeGen/static-vars.cpp
- clang/test/CIR/CodeGen/temporaries.cpp
- clang/test/CIR/CodeGen/tempref.cpp
- clang/test/CIR/CodeGen/unary-deref.cpp
- clang/test/CIR/CodeGen/union-init.c
- clang/test/CIR/CodeGen/visibility-attribute.c
- clang/test/CIR/IR/annotations.cir
- clang/test/CIR/IR/invalid-annotations.cir
- clang/test/CIR/Lowering/brcond.cir
- clang/test/CIR/Lowering/store-memcpy.cpp
Following #1009 and #1028, this PR removes the double white spaces in the assembly format of `cir.global` op.
It's basically some `mlir-tablegen`-builtin magic: With `constBuilderCall` specified, we can apply `DefaultValuedAttr` with any default value we can construct from constant values. Then we can easily omit the default in assembly. Hence, we don't need to compromise anything for the wrapper attribute `cir::VisibilityAttr`.
Similarly to #1009, an empty literal ``` `` ``` is used to omit the leading space emitted by inner attribute.
The test case `visibility-attribute.c` is modified to save the intermediate CIR to disk and reflect the effects.
Double whitespaces in other test files are removed.
> [CIR][Dialect][NFC] Fix double white spaces in `cir.global` assembly

- clang/include/clang/CIR/Dialect/IR/CIRDialect.td
This got misaligned after the namespace changes.
> [CIR][NFC] Fix formatting

- clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp
- clang/test/CIR/CodeGen/abstract-cond.c
- clang/test/CIR/Lowering/if.cir
- clang/test/CIR/Transforms/if.cir
- clang/test/CIR/Transforms/mem2reg.c
Before the commit, when flattening if/else clauses - the else body came before the "then" body, as opposed to clang's output order.
This commit reverses this and hopefully allows easier comparisson between clang's output and cir's.
> [CIR][NFC] Conform if/else lowering order to match clang's output

- clang/include/clang/CIR/ABIArgInfo.h
- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepareCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CMakeLists.txt
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/LoweringPrepareX86CXXABI.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86_64ABIInfo.h
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/var-arg-x86_64.c
This patch implements transformations for VAArg in X86_64 ABI **in shape**.  `In shape` means it can't work properly due to the dependent X86_64 ABI is not robust. e.g., when we want to use VAArg with `long double`, we need https://github.com/llvm/clangir/pull/1087.
This patch literally implement https://github.com/llvm/llvm-project/blob/d233fedfb0de882353c348cd1ac57dab619efa6d/clang/lib/CodeGen/Targets/X86.cpp#L3015-L3240 in CIR. 
There some differences due to the traditional pipeline are converting AST to LLVM and we're transforming CIR to CIR. And also to get the ABI Info, I moved `X86_64ABIInfo` to the header.
> [CIR] [Lowering] [X86_64] Support VAArg in shape

- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/LoweringPrepareX86CXXABI.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86_64ABIInfo.h
- clang/test/CIR/Lowering/var-arg-x86_64.c
This is the following of https://github.com/llvm/clangir/pull/1100.
After https://github.com/llvm/clangir/pull/1100, when we want to use LongDouble for VAArg, we will be in trouble due to details in X86_64's ABI and this patch tries to address this.
The practical impact the patch is, after this patch, with https://github.com/llvm/clangir/pull/1088 and a small following up fix, we can build and run all C's benchmark in SpecCPU 2017. I think it is a milestone.
> [CIR] [Lowering] [X86_64] Support VAArg for LongDouble

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/test/CIR/CallConvLowering/AArch64/aarch64-cc-structs.c
This PR adds a support for one more case of passing structs by value, with `memcpy` emitted. 
First of all, don't worry - despite the PR seems big, it's basically consist of helpers + refactoring.  Also, there is a minor change in the `CIRBaseBuilder` - I made static the `getBestAllocaInsertPoint` method  in order to call it from lowering - we discussed once - and I here we just need it (or copy-paste the code, which doesn't seem good).
I will add several comments in order to simplify review.
> [CIR][ABI][AArch64] Support struct passing with coercion through memory 

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/builtin-signbit.c
follow https://github.com/llvm/clangir/pull/1033
handle `LongDoubleType` with `FP80Type`.
> [CIR][CIRGen] Support __builtin_signbitl

- clang/include/clang/CIR/Dialect/IR/CIRDialect.td
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenOpenCL.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerCall.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
As title, this patch refactors raw string literals for (module) attribute names into static methods of `CIRDialect`, following the convention of MLIR.
> [CIR][Dialect][NFC] Refactor hardcoded attribute name strings

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
We are still seeing crash message like `NYI UNREACHABLE executed at clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp:3304`, which is not convenient for triaging as our code base changes so fast, line number doesn't help much.
So, here we replaced most of `llvm_unreachable("NYI")` with more informative message.
> [CIR][Builtin][NFC] More informative llvm_unreachable message in CIRGenBuiltinAArch64.cpp

- clang/lib/CIR/FrontendAction/CIRGenAction.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Tools/cir-translate-triple.cir
Currently, the final `target triple` in LLVM IR is set in `CIRGenAction`, which is not executed by cir tools like `cir-translate`. This PR delay its assignment to LLVM lowering, enabling sharing the emitting of `target triple` between different invoking paths.
> [CIR][LowerToLLVM] Lowering triple from `cir.triple` attribute

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.h
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/test/CIR/CodeGen/builtins-elementwise.c
Extend AbsOp to take vector of int input. With it, we can support  __builtin_elementwise_abs. 
We should in the next PR extend FpUnaryOps to support vector type input so we won't have blocker to implement all elementwise builtins completely. Now just temporarily have missingFeature `fpUnaryOPsSupportVectorType`.  
Currently, int type UnaryOp support vector type. 
FYI:
[clang's documentation about elementwise builtins](https://clang.llvm.org/docs/LanguageExtensions.html#vector-builtins)
> [CIR][CIRGen][Builtin] Support __builtin_elementwise_abs and extend AbsOp to take vector input

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/utils/TableGen/CIRLoweringEmitter.cpp
This is a NFC patch that moves declaration from  LowerToLLVM.cpp.
The motivation of the patch is, we hope we can use the abilities from MLIR's standard dialects without lowering **ALL** clangir operation to MLIR's standard dialects. For example, currently we have 86 operations in LowerToLLVM.cpp but only 45 operations under though MLIR. It won't be easy to add proper lowering for all operation to **different** dialects.
I think the solution may be to allow **mixed** IR. So that we can lowering CIR to MLIR's standard dialects partially and we can use some existing analysis and optimizations in MLIR and then we can lower all of them (the MLIR dialects and unlowered clangir) to LLVM IR. The hybrid IR is one of the goals of MLIR as far as I know.
NOTE: I completely understand that the …
> [ClangIR][Lowering][NFC] Split LowerToLLVM.h from LowerToLLVM.cpp

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/test/CIR/CodeGen/bf16-ops.c
- clang/test/CIR/CodeGen/float16-ops.c
- clang/test/CIR/CodeGen/fp16-ops.c
- clang/test/CIR/IR/invalid.cir
- clang/test/CIR/Lowering/ThroughMLIR/doWhile.c
- clang/test/CIR/Lowering/ThroughMLIR/if.c
- clang/test/CIR/Lowering/ThroughMLIR/while.c
- clang/test/CIR/Lowering/dot.cir
- clang/test/CIR/Lowering/goto.cir
- clang/test/CIR/Lowering/loops-with-break.cir
- clang/test/CIR/Lowering/loops-with-continue.cir
- clang/test/CIR/Lowering/switch.cir
- clang/test/CIR/Transforms/mem2reg.c
- clang/test/CIR/Transforms/scf-prepare.cir
- clang/test/CIR/Transforms/simpl.c
- clang/test/CIR/Transforms/switch.cir
It was always the intention for `cir.cmp` operations to return bool result. Due
to missing constraints, a bug in codegen has slipped in which created `cir.cmp`
operations with result type that matches the original AST expression type. In
C, as opposed to C++, boolean expression types are "int". This resulted with
extra operations being codegened around boolean expressions and their usage.
This commit both enforces `cir.cmp` in the op definition and fixes the
mentioned bug.
> [CIR] Force cir.cmp to always return bool

- mlir/include/mlir/Dialect/LLVMIR/LLVMIntrinsicOps.td
- mlir/lib/Dialect/LLVMIR/IR/LLVMInterfaces.cpp
- mlir/lib/Dialect/LLVMIR/IR/LLVMMemorySlot.cpp
- mlir/test/Dialect/LLVMIR/mem2reg-intrinsics.mlir
- mlir/test/Dialect/LLVMIR/sroa-intrinsics.mlir
- mlir/test/Target/LLVMIR/Import/intrinsic.ll
- mlir/test/Target/LLVMIR/llvmir-intrinsics.mlir
support `llvm.intr.memset.inline` in llvm-project repo before we add support for `__builtin_memset_inline` in clangir
cc @bcardosolopes
(cherry picked from commit 30753afc2a3171e962e261622781852a01fbec72)
> [cherry-pick][mlir][llvm] Add support for memset.inline (#115711)

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenAtomic.cpp
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/lib/CIR/CodeGen/CIRGenDecl.cpp
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp
- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.h
- clang/lib/CIR/CodeGen/CIRGenTBAA.cpp
- clang/lib/CIR/CodeGen/CIRGenTBAA.h
- clang/lib/CIR/CodeGen/CIRGenValue.h
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/IR/CIRMemorySlot.cpp
- clang/test/CIR/CodeGen/tbaa.c
This is the first patch to support TBAA, following the discussion at https://github.com/llvm/clangir/pull/1076#discussion_r1835031415
- add skeleton for CIRGen, utilizing `decorateOperationWithTBAA`
- add empty implementation in `CIRGenTBAA`
- introduce `CIR_TBAAAttr` with empty body
- attach `CIR_TBAAAttr` to `LoadOp` and `StoreOp`
- no handling of vtable pointer
- no LLVM lowering
> [CIR][CIRGen][TBAA] Initial TBAA support

- clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp
- clang/test/CIR/CodeGen/fullexpr.cpp
This PR implements NYI in CIRScopeOpFlattening. It seems to me the best way is to let results of ScopeOp forwarded as block arguments of the last block split from the cir.scope block.
> [CIR][FlattenCFG] Let results of CIR ScopeOp forwarded during FlattenCFG

- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp
With [llvm-project#116090](https://github.com/llvm/llvm-project/pull/116090) merged, we can get rid of `#include "../../../../Basic/Targets.h"` now.
> [CIR][Transforms][NFC] Fix undesirable include of clang's private header

- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/Lowering/data-member.cir
This PR moves the lowering code for data member pointers from the conversion patterns to the implementation of CXXABI because this part should be ABI-specific.
> [CIR][NFC] move data member pointer lowering to CXXABI

- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/test/CIR/CallConvLowering/AArch64/aarch64-cc-structs.c
This PR adds support for the lowering of AArch64 calls with structs having sizes greater than 64 and less than 128. 
The idea is from the original [CodeGen](https://github.com/llvm/clangir/blob/da601b374deea6665f710f7e432dfa82f457059e/clang/lib/CodeGen/CGCall.cpp#L1329), where we perform a coercion through memory for these type of calls. 
I have added a test for this.
> [CIR][ABI][AArch64][Lowering] support for calling struct types in range (64, 128)

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
They are rounding shift of vectors, and shift amount is from the least significant byte of the corresponding element of the second input vector.  Thus, it is implemented in [its own ASM ](https://godbolt.org/z/v65sbeKaW). These make them not suitable to be lowered to CIR ShiftOp though it supports vector type now.
> [CIR][CIRGen][Builtin][Neon] Lower neon_vrshl_v and neon_vrshlq_v

- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
Caught by ASAN. We were creating a reference to an object going out of
scope. Incidentally, this feels like the sort of issue the lifetime
checker will be great for detecting :)
> [CIR][CIRGen] Fix a stack-use-after-free

- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
Based on https://mlir.llvm.org/docs/Tutorials/UnderstandingTheIRStructure/#traversing-the-def-use-chains,
the users of an op are linked together in a doubly-linked list, so
replacing a user while iterating the users causes a use-after-free.
Store the users in a worklist and process them afterwards instead to
avoid this.
> [CIR][TargetLowering] Fix use iteration

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-arith.c
Now implement the same as [OG](https://github.com/llvm/clangir/blob/7619b20d7461b2d46c17a3154ec4b2f12ca35ea5/clang/lib/CodeGen/CGBuiltin.cpp#L7886), which is to call  llvm aarch64 intrinsic which would eventually become [an ARM64 instruction](https://developer.arm.com/documentation/ddi0596/2021-03/SIMD-FP-Instructions/ABS--Absolute-value--vector--?lang=en).
However, clearly there is an alternative, which is to extend CIR::AbsOp and CIR::FAbsOp to support vector type and only lower it  at LLVM Lowering stage to either  [LLVM::FAbsOP ](https://mlir.llvm.org/docs/Dialects/LLVM/#llvmintrfabs-llvmfabsop) or  [[LLVM::AbsOP ]](https://mlir.llvm.org/docs/Dialects/LLVM/#llvmintrabs-llvmabsop), provided LLVM dialect could do the right thing of TargetLowering by translating to llvm aarch64 intrinsic …
> [CIR][CIRGen][Builtin][Neon] Lower neon_vabs_v and neon_vabsq_v

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtins.cpp
Without using flag `-fstrict-vtable-pointers`,  `__builtin_launder` is a noop. This PR implements that, and leave implementation for the case of  `-fstrict-vtable-pointers` to future where there is a need.
This PR also adapted most of test cases from [OG test case](https://github.com/llvm/clangir/blob/3aed38cf52e72cb51a907fad9dd53802f6505b81/clang/test/CodeGenCXX/builtin-launder.cpp#L1).
I didn't use test cases in the namespace [pessimizing_cases](https://github.com/llvm/clangir/blob/3aed38cf52e72cb51a907fad9dd53802f6505b81/clang/test/CodeGenCXX/builtin-launder.cpp#L269), as they have no difference even when `-fstrict-vtable-pointers` is on.
> [CIR][CIRGen][Builtin] Support __builtin_launder except in the case of -fstrict-vtable-pointers

- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/test/CIR/CodeGen/copy-constructor.cpp
If a record type contains an array of non-record types, we can generate
a copy for it inside the copy constructor, as CodeGen does. CodeGen does
so for arrays of record types where applicable as well, but we'll want
to represent the construction of those explicitly, as outlined in
https://github.com/llvm/clangir/issues/1055.
> [CIR][CIRGen] Support copy constructors with non-record arrays

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/test/CIR/CodeGen/initlist-ptr-ptr.cpp
- clang/test/CIR/CodeGen/initlist-ptr-unsigned.cpp
- clang/test/CIR/IR/invalid.cir
I don't finish all work about `cir.initlist`. But I want to get some feedback about the cir design to make sure I am in correct way.
Fixed: #777
> [CIR][Dialect] Introduce StdInitializerListOp to represent high-level semantics of C++ initializer list

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
This PR also changed implementation of BI__builtin_neon_vshlq_v into using CIR ShiftOp
> [CIR][CIRGen][Builtin][Neon] Lower __builtin_neon_vshl_v

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.cpp
After I rebased, I found these problems with Spec2017. I was surprised why it doesn't have problems. Maybe some updates in LLVM part.
> [CIR] Correct signedness for createSignedInt

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/test/CIR/CodeGen/ternary.c
The requirement for the size of then-else part of cir.ternary operation seems to be too conservative. Like the example shows, it is possible the regions got expanded during the transformation.
> [CIR] Relax the requirement for ternary operation

- clang/test/CIR/CodeGen/lambda.cpp
Added a few FIXMEs. There are 2 types of FIXMEs;
1. Most of them are missing func call and parameter attributes. I didn't add for all missing sites for this type as it would have been just copy pastes.
2. FIXME in lambda __invoke(): OG simply returns but CIR generates call to llvm.trap. This is just temporary and we will fix in in near future. But I feel I should still list those IRs so once we fix problem with codegen of invoke, we'd get test failure on this one and fix it. Actually, this way, this test file would be a natural test case for implementation of invoke.
> [CIR][NFC][Test] Add llvm ir test for lambdas

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtins-elementwise.c
[PR1132](https://github.com/llvm/clangir/pull/1132) implements missing feature `fpUnaryOPsSupportVectorType`, so revisit this code.
One another thing changed is that I stopped using `cir::isAnyFloatingPointType` as it contains types like long double and FP80 which are not supported by the [builtin's signature](https://clang.llvm.org/docs/LanguageExtensions.html#vector-builtins)
> [CIR][CIRGen][Builtin] Support __builtin_elementwise_abs with vector of floating type

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
[OG's implementation ](https://github.com/llvm/clangir/blob/aaf38b30d31251f3411790820c5e1bf914393ddc/clang/lib/CodeGen/CGBuiltin.cpp#L7527) provides one common code to handle all neon SISD intrinsics. But IMHO, it entangles different things together which hurts readability.
Here, We start with simple easy-to-understand approach with specific case. And in the future, as we handle more intrinsics, we may come up with a few simple common patterns.
> [CIR][CIRGen][Builtin][Neon] Lower SISD neon_vqrdmulhs_s32

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-arith.c
[OG's implementation here](https://github.com/llvm/clangir/blob/1b052dac90f8d070aafc2034e13ae3e88552d58a/clang/lib/CodeGen/CGBuiltin.cpp#L13432)
[OG's test here](https://github.com/llvm/clangir/blob/1b052dac90f8d070aafc2034e13ae3e88552d58a/clang/test/CodeGen/AArch64/neon-across.c#L41)
> [CIR][CIRGen][Builtin][Neon] Lower neon_vaddlvq_u16

- Files/launch.json
* Change `-fclangir-enable` to `-fclangir`.
* Remove some trailing commas that are techincally invalid in JSON (I
guess VSCode accepts them but may as well be strict).
* Remove `clangir-disable-emit-cxx-default` since I plan to remove it
soon.
Fixes https://github.com/llvm/clangir/issues/1182
> [gh-pages] Clean up launch.json

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIRDialect.td
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/Dialect/IR/CIRAttrs.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.h
- clang/test/CIR/CodeGen/optimization-attr.cpp
This PR adds `clang::CodeGenOptions` to the lowering context. Similar to `clang::LangOptions`, the code generation options are currently set to the default values when initializing the lowering context.
Besides, this PR also adds a new attribute `#cir.opt_level`. The attribute is a module-level attribute and it holds the optimization level (e.g. -O1, -Oz, etc.). The attribute is consumed when initializing the lowering context to populate the `OptimizationLevel` and the `OptimizeSize` field in the code generation options. CIRGen is updated to attach this attribute to the module op.
> [CIR] Add code generation options to lowering context

- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/test/CIR/CodeGen/variadic-ctor.cpp
Removes some NYIs. But left assert(false) due to missing tests. It looks better since it is not so scaring as NYI.
> [CIR] [CodeGen] Handle arrangeCXXStructorDeclaration

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/CodeGen/pointer-to-data-member-cast.cpp
This PR adds support for base-to-derived and derived-to-base casts on pointer-to-data-member values.
Related to #973.
> [CIR] Add support for casting pointer-to-data-member values

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/vectype-ext.cpp
- clang/test/CIR/Lowering/unary-not.cir
- clang/test/CIR/Lowering/vectype.cpp
Basically, for int type, the order of Ops is not the same as OG in the emitted LLVM IR. OG has constant as the second op position. See [OG's order ](https://godbolt.org/z/584jrWeYn).
> [CIR][CodeGen][LowerToLLVM] Fix llvm lowering of CIR `UnaryOpKind_Not`

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/test/CIR/CodeGen/assign-operator.cpp
Default assignment operator generation was failing because of memcpy
generation for fields being unsupported. Implement it following
CodeGen's example, as usual. Follow-ups will avoid emitting memcpys for
fields of trivial class types, and extend this to copy constructors as
well.
Fixes https://github.com/llvm/clangir/issues/1128
> [CIR][CIRGen] Support emitting memcpys for fields

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/test/CIR/CodeGen/assign-operator.cpp
Our previous logic here was matching CodeGen, which folds trivial
assignment operator calls into memcpys, but we want to avoid that. Note
that we still end up emitting memcpys for arrays of classes with trivial
assignment operators; https://github.com/llvm/clangir/issues/1177 tracks
fixing that.
> [CIR][CIRGen] Call trivial assignment operators in more cases

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/test/CIR/CodeGen/assign-operator.cpp
- clang/test/CIR/CodeGen/copy-constructor.cpp
CodeGen does so for trivial record types as well as non-record types; we
only do it for non-record types.
> [CIR][CIRGen] Emit memcpys for copy constructors

- clang/lib/CIR/Dialect/Transforms/HoistAllocas.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/CodeGen/const-alloca.cpp
This PR updates the LLVM lowering part of load and stores to const allocas and makes use of the !invariant.group metadata in the result LLVM IR.
The HoistAlloca pass is also updated. The const flag on a hoisted alloca is removed for now since their uses are not always invariants. Will update in later PRs to teach their invariants.
> [CIR] Make use of !invariant.group metadata for const allocas

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/lib/CIR/CodeGen/CIRGenStmt.cpp
- clang/test/CIR/CodeGen/builtin-assume.cpp
This PR adds CIRGen support for C++23 `[[assume(expr)]]` statement.
> [CIR][CIRGen] Add CIRGen support for assume statement

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
There's a lot that was missing here. Add NYIs and MissingFeatures as
appropriate, so that we can start work on matching CodeGen.
> [CIR][CIRGen] Flesh out CIRGenModule::Release skeleton

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
- clang/test/CIR/IR/invalid.cir
- clang/test/CIR/Lowering/binop-signed-int.cir
- clang/test/CIR/Lowering/binop-unsigned-int.cir
This can't be simply implemented by our CIR Add via LLVM::AddOp, as i[t's saturated add.](https://godbolt.org/z/MxqGrj6fP)
> [CIR][CIRGen][Builtin][Neon] Lower neon_vqadds_s32

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenCXX.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.h
- clang/test/CIR/CodeGen/dtor-alias.cpp
This removes some NYI in CIRGenModule::tryEmitBaseDestructorAsAlias and similar to https://github.com/llvm/clangir/pull/1179, use `assert(false)` to tell devs to add test.
It is slightly verbose due to the difference between LLVM and CIR's type system. LLVM's pointer are opaque types while CIR's pointer are typed. So we need to handle these pointers when transforming the generated cir.
> [CIR][CIRGen] Handle NYI in CIRGenModule::tryEmitBaseDestructorAsAlias

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/binop-signed-int.cir
- clang/test/CIR/Lowering/binop-unsigned-int.cir
This would facilitate implementation of neon intrinsic `neon_vmax_v` and `__builtin_elementwise_max`, and potentially future optimizations. CIR BinOp supports vector type.
Floating point has already been supported by FMaxOp.
> [CIR][Dialect] Add BinOpKind_Max

- clang/lib/CIR/Dialect/Transforms/TargetLowering/CMakeLists.txt
- clang/tools/cir-opt/CMakeLists.txt
- clang/tools/cir-translate/CMakeLists.txt
This option creates and links all tools against a single libLLVM shared
library (and the corresponding CLANG_LINK_CLANG_DYLIB option also gets
turned on by default). In order for this to work, we need to use
LINK_COMPONENTS instead of LINK_LIBS for all LLVM dependencies, and
clang_target_link_libraries for all Clang dependencies, so that they get
rewritten to use the dylib. Remove llvm_update_compile_flags while I'm
here, since the build macros handle that internally. Before this change,
we'd link against certain LLVM libraries both statically and
dynamically, leading to test failures from duplicate singletons.
The way this works for MLIR is fragile right now: MLIR can create its
own dylib as well but doesn't have build system support for linking
against that dylib. We end up folding the …
> [CIR] Fix tests with LLVM_LINK_LLVM_DYLIB

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.cpp
- clang/test/CIR/IR/being_and_nothingness.cir
- mlir/include/mlir/IR/OpImplementation.h
- mlir/include/mlir/Interfaces/FunctionImplementation.h
- mlir/lib/AsmParser/AsmParserImpl.h
- mlir/lib/Interfaces/FunctionImplementation.cpp
C/C++ functions returning void had an explicit !cir.void return type while not having any returned value, which was breaking a lot of MLIR invariants when the CIR dialect is used in a greater context, for example with the inliner. Now, a C/C++ function returning void has not return type and no return values, which does not break the MLIR invariant about the same number of return types and returned values.
This change keeps the same parsing/pretty-printed syntax as before for compatibility.
> [CIR] Remove the !cir.void return type for functions returning void

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
References:
[OG's implementation](https://github.com/llvm/clangir/blob/2b1a638ea07ca10c5727ea835bfbe17b881175cc/clang/lib/CodeGen/CGBuiltin.cpp#L13509)
[Builtin's definition ](https://developer.arm.com/architectures/instruction-sets/intrinsics/#f:@navigationhierarchiessimdisa=[Neon]&q=vrsra_n_)
> [CIR][CIRGen][Builtin][Neon] Lower neon_vrsraq_n_v and neon_vrsra_n_v

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIRDialect.td
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp
- clang/test/CIR/CodeGen/uwtable.cpp
The module-level uwtable attribute controls the unwind tables for any
synthesized functions, and the function-level attribute controls them
for those functions. I'll add support for this attribute to the LLVM
dialect as well, but translate it from CIR directly for now to avoid
waiting on the MLIR addition and a subsequent rebase.
> [CIR][CIRGen] Add uwtable attribute

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
Match `CodeGenModule::SetLLVMFunctionAttributesForDefinition` so that we
can see what's missing and have a good base to build upon.
> [CIR][CIRGen] Match skeleton for setCIRFunctionAttributesForDefinition

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepareCXXABI.h
- clang/lib/CIR/Dialect/Transforms/LoweringPrepareItaniumCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/test/CIR/CodeGen/delete-array.cpp
I am working on a clangir based solution to improve C++'s safety (https://discourse.llvm.org/t/rfc-a-clangir-based-safe-c/83245). This is similar with the previous analysis only approach I proposed, where we may not care about the lowered code. And this is what I described as layering problems in https://discourse.llvm.org/t/rfc-a-clangir-based-safe-c/83245
This is similar with the other issue proposed https://github.com/llvm/clangir/issues/1128. We'd better to emit the higher level operations and lowering/optimizing it later.
This is also inspired our handling method for VAArg, where we use ABI information to lower things during the passes. It gives me more confidence that I am doing things right.
> [CIR][CIRGen] Introduce cir.delete.array op

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/test/CIR/CodeGen/lambda.cpp
The PR should help us to get rid of NYI 
`NYI UNREACHABLE executed at clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp:899`
[Relevant OG code here](https://github.com/llvm/clangir/blob/7fb608d4d1b72c25a1739a1bd66c9024208819cb/clang/lib/CodeGen/CGExpr.cpp#L4767): 
I put `HasExplicitObjectParameter` support as a missing feature, which is a new C++23 feature.
> [CIR][CIRGen] Support Lambda capturing `this` object

- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/test/CIR/CodeGen/try-catch-dtors.cpp
Let's take a look at the following code:
```
struct A {
~A() {}
};
int foo() { return 42; }
void bar() {
A a;
int b = foo(); 
}
```
The call to `foo` guarded by the synthetic `tryOp` looks approximately like the following:
```
cir.try synthetic cleanup {
%2 = cir.call exception @_Z3foov() : () -> !s32i cleanup {
cir.call @_ZN1AD1Ev(%0) : (!cir.ptr<!ty_A>) -> () extra(#fn_attr1)   // call to destructor of 'A'
cir.yield
} 
cir.yield
} catch [#cir.unwind {
cir.resume 
}] 
cir.store %2, %1: !s32i, !cir.ptr<!s32i>  // CIR verification error
```
The result of the `foo` call is in the `try` region - and is not accessible from the outside, so the code generation fails with 
`operand #0 does not dominate its use` .
So we have several options how to handle this properly. 
1. We may intpoduce a new …
> [CIR][CIRGen] Fixes function calls with return values and cleanup stage

- clang/lib/CIR/CodeGen/CIRGenStmt.cpp
- clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp
- clang/test/CIR/CodeGen/goto.cpp
- clang/test/CIR/CodeGen/loop-scope.cpp
- clang/test/CIR/CodeGen/loop.cpp
- clang/test/CIR/Lowering/ThroughMLIR/doWhile.c
- clang/test/CIR/Lowering/ThroughMLIR/while.c
- clang/test/CIR/Transforms/lifetime-loop.cpp
This PR puts for-loop body, while-loop body, and do-while-loop body in nested scopes. Allocas in the loop body are now push down to the nested scope.
Resolve #1218 .
> [CIR] Put loop body in nested scopes

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtin-floating-point.c
- clang/test/CIR/Lowering/builtin-floating-point.cir
There are two sets of intrinsics regarding Min and Max operations for floating points
[Maximum](https://mlir.llvm.org/docs/Dialects/LLVM/#llvmintrmaximum-llvmmaximumop) vs [Maxnum](https://mlir.llvm.org/docs/Dialects/LLVM/#llvmintrmaxnum-llvmmaxnumop)
[Minimum](https://mlir.llvm.org/docs/Dialects/LLVM/#llvmintrminimum-llvmminimumop)  vs [Minnum](https://mlir.llvm.org/docs/Dialects/LLVM/#llvmintrminnum-llvmminnumop)
[The difference is whether NaN should be propagated when one of the inputs is NaN](https://llvm.org/docs/LangRef.html#llvm-maximumnum-intrinsic)
Maxnum and  Minnum would return number if one of inputs is NaN, and the other is a number,
But 
Maximum and Minimum would return NaN (propagation of NaN)
And they are resolved to different ASM such as …
> [CIR][Dialect] Add FMaximumOp and FMinimumOp

- clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp
Use iterator to visit std::initializer_list field reduce the readability
> [CIR][CodeGen][NFC] centralized split `std::initializer_list` field

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
This implementation is different from OG in the sense we chose to use CIR op which eventually lowers to generic LLVM intrinsics instead of llvm.aarch64.neon intrinsics
But down to the ASM level, [they are identical ](https://godbolt.org/z/Gbbos9z6Y).
> [CIR][CIRGen][Builtin][Neon] Lower neon_vmax_v and neon_vmaxq_v

- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/include/clang/CIR/Dialect/IR/CMakeLists.txt
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/utils/TableGen/CIRLoweringEmitter.cpp
- clang/utils/TableGen/TableGen.cpp
- clang/utils/TableGen/TableGenBackends.h
This patch follows https://github.com/llvm/clangir/pull/1220#discussion_r1882808223 by augmenting `CIR_Type` with a new field, `tbaaName`. Specifically, it enables TableGen support for the `-gen-cir-tbaa-name-lowering` option, allowing for the generation of `getTBAAName` functions based on the `tbaaName`. This enhancement enables us to replace the hardcoded TBAA names in the `getTypeName` function with the newly generated `getTBAAName`.
> [CIR][CIRGen][TBAA] Replace hardcoded TBAA names with getTBAAName

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/bitfields.c
This PR adds a bitcast when we rewrite globals type. Previously we just set a new type and it worked. 
But recently I started to test ClangIR with CSmith in order to find some run time bugs and faced with the next problem.
```
int x : 15;   
uint8_t y;
} S;
S g = { -12, 254};
int main() {    
printf("%d\n", g.y);
return 0;
}
```
The output for this program is  ... 127 but not 254!
The reason is that first global var is created with the type of struct `S`, then `get_member` operation is generated with index `1` 
and then after, the type of the global is rewritten - I assume because of the anon struct created on the right side in the initialization.
But the `get_member` operation still wants to access to the field at index `1` and get a wrong byte. 
If we change the `y` …
> [CIR][CodeGen] fixes access to globals with bitfields

- clang/test/CIR/crashes/copy-on-catch.cpp
We figure it would be nice to have a common place with all our known
crashes that is tracked by git and is actively verified whether or not
we can now support the crashes by lit. It can act as our source of truth
for known failures and also being potential good first tasks for new
developers.
Add a simple test case of a known crash that involves copying a struct
in a catch.
> [CIR] Introduce a new dir in tests for known crashes to fix

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-misc.c
Lowering Neon `vsetq_lane_f64`
References:
[Clang CGBuiltin Implementation](https://github.com/llvm/clangir/blob/2b1a638ea07ca10c5727ea835bfbe17b881175cc/clang/lib/CodeGen/CGBuiltin.cpp#L12348)
[Builtin definition](https://developer.arm.com/architectures/instruction-sets/intrinsics/vsetq_lane_f64)
> [CIR][CIRGen][Builtin][Neon] Lower neon_vsetq_lane_f64

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Lowering Neon `vaddd_s64` and `vaddd_u64`
- [Clang CGBuiltin Implementation](https://github.com/llvm/clangir/blob/2b1a638ea07ca10c5727ea835bfbe17b881175cc/clang/lib/CodeGen/CGBuiltin.cpp#L12460-L12462)
- [vaddd_s64 Builtin definition](https://developer.arm.com/architectures/instruction-sets/intrinsics/vaddd_s64)
- [vaddd_u64 Builtin definition](https://developer.arm.com/architectures/instruction-sets/intrinsics/vaddd_u64)
> [CIR][CIRGen][Builtin][Neon] Lower `neon_vaddd_s64` and `neon_vaddd_u64`

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Lowering `neon_vsubd_s64` and `neon_vsubd_u64`
- [Clang CGBuiltin Implementation](https://github.com/llvm/clangir/blob/2b1a638ea07ca10c5727ea835bfbe17b881175cc/clang/lib/CodeGen/CGBuiltin.cpp#L12463-L12465)
- [vaddd_s64 Builtin definition](https://developer.arm.com/architectures/instruction-sets/intrinsics/vsubd_s64)
- [vaddd_u64 Builtin definition](https://developer.arm.com/architectures/instruction-sets/intrinsics/vsubd_u64)
> [CIR][CIRGen][Builtin][Neon] Lower `neon_vsubd_s64` and `neon_vsubd_u64`

- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-fp16.c
Lowering:
- `vaddh_f16`
- `vsubh_f16`
- `vmulh_f16`
- `vdivh_f16`
> [CIR][CIRGen][Builtin][Neon] Lower `vaddh_f16`, `vsubh_f16`, `vmulh_f16` and `vdivh_f16`

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Lowering `vshld_n_s64` and `vshld_n_u64`
> [CIR][CIRGen][Builtin][Neon] Lower vshld_n_s64 and vshld_n_u64

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower vshrd_n_s64

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-misc.c
Lowering Neon `vset_lane_f64`
References:
[Clang CGBuiltin Implementation](https://github.com/llvm/clangir/blob/2b1a638ea07ca10c5727ea835bfbe17b881175cc/clang/lib/CodeGen/CGBuiltin.cpp#L12342)
[Builtin definition](https://developer.arm.com/architectures/instruction-sets/intrinsics/vset_lane_f64)
> [CIR][CIRGen][Builtin][Neon] Lower neon_vset_lane_f64

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-fp16.c
Lower `vabsh_f16`
CG: https://github.com/llvm/clangir/blob/25b269e5fed544e1da37b72bc32315c0ae0c5aa6/clang/lib/CodeGen/CGBuiltin.cpp#L11975-L11977
> [CIR][CIRGen][Builtin][Neon] Lower vabsh_f16

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Interfaces/CIROpInterfaces.td
- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.h
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/CodeGen/call-side-effect.cpp
- clang/test/CIR/IR/side-effect.cir
- clang/test/CIR/Lowering/call.cir
This patch adds support for the following GCC function attributes:
- `__attribute__((const))`
- `__attribute__((pure))`
The side effect information is attached to the call operations during CIRGen. During LLVM lowering, these information is consumed to further emit appropriate LLVM metadata on LLVM call instructions.
> [CIR] Add support for GCC function attribute "const" and "pure"

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerTypes.cpp
- clang/test/CIR/CodeGen/fun-ptr.c
- clang/test/CIR/CodeGen/gnu-extension.c
- clang/test/CIR/CodeGen/member-init-struct.cpp
- clang/test/CIR/CodeGen/multi-vtable.cpp
- clang/test/CIR/CodeGen/no-proto-fun-ptr.c
- clang/test/CIR/CodeGen/pointer-arith-ext.c
- clang/test/CIR/CodeGen/pointer-to-member-func.cpp
- clang/test/CIR/CodeGen/static.cpp
- clang/test/CIR/IR/being_and_nothingness.cir
C/C++ functions returning void had an explicit !cir.void return type while not
having any returned value, which was breaking a lot of MLIR invariants when the
CIR dialect is used in a greater context, for example with the inliner.
Now, a C/C++ function returning void has no return type and no return values,
which does not break the MLIR invariant about the same number of return types
and returned values.
This change does not keeps the same parsing/pretty-printed syntax as before for
compatibility like in https://github.com/llvm/clangir/pull/1203 because it
requires some new features from the MLIR parser infrastructure itself, which is
not great.
This uses an optional type for function return type.
The default MLIR parser for optional parameters requires an optional anchor we
do not have …
> [CIR] Remove return !cir.void from IR and textual representation

- clang/include/clang/CIR/Dialect/Passes.td
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerMLIRToLLVM.cpp
Some passes not declared with TableGen did not have descriptions.
> [CIR][Doc][NFC] Add a description for all the passes

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
- clang/test/CIR/CodeGen/vtable-emission.cpp
Corresponding [OG code](https://github.com/llvm/clangir/blob/ef20d053b3d78c9d4c135e2811b303b7e5016d30/clang/lib/CodeGen/CGExprConstant.cpp#L846).
[OG generated code here](https://godbolt.org/z/x6q333dMn),  one notable diff is we're missing `inrange` which is reported in [issue 886 ](https://github.com/llvm/clangir/issues/886). 
For now, I'm still using GlobalViewAttr to implement it so we can move things fast. 
But it might be worth considering approach [Comments in issue 258](https://github.com/llvm/clangir/issues/258), especially we could incoporate [inrange info](https://github.com/llvm/clangir/issues/886) to the attribute suggested there.
> [CIR][CIRGen] virtual table pointer initialization without ctor

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/CodeGen/pointer-to-data-member-cast.cpp
- clang/test/CIR/CodeGen/pointer-to-data-member-cmp.cpp
This PR adds CIRGen and LLVM lowering support for the following language features related to pointers to data members:
- Comparisons between pointers to data members.
- Casting from pointers to data members to boolean.
- Reinterpret casts between pointers to data members.
> [CIR] Data member pointer comparison and casts

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/globals.cir
This PR updates the `#cir.global_view` attribute and make it accept integer types as its result type.
> [CIR] Add integer result type for cir.global_view

- clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp
- clang/test/CIR/CodeGen/array-init.c
Resolves #1266
After change:
```llvm
%1 = alloca ptr, i64 1, align 8
store i32 1, ptr @g_arr, align 4
store i32 2, ptr getelementptr (i32, ptr @g_arr, i64 1), align 4
store i32 3, ptr getelementptr (i32, ptr @g_arr, i64 2), align 4
%2 = load i32, ptr @g, align 4
store i32 %2, ptr getelementptr (i32, ptr @g_arr, i64 3), align 4
store ptr getelementptr (i32, ptr getelementptr (i32, ptr @g_arr, i64 3), i64 1), ptr %1, align 8
```
> [CIR][CIRGen] Simplify LLVM IR array initialization for clang CIR

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
- clang/lib/CIR/CodeGen/CIRGenValue.h
- clang/lib/CIR/CodeGen/ConstantInitBuilder.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp
- clang/test/CodeGenOpenCL/printf.cl
- After abba01adad5dfc54f781357d924c8021c9306615, 'is' and 'get' interfaces are deprecated even though not removed yet. However, it causes warnings and triggers build failures if that warnings are treated as errors.
> [CIR] Fix build due to deprecated interfaces

- clang/lib/CIR/Dialect/Transforms/CIRCanonicalize.cpp
- clang/test/CIR/Transforms/merge-cleanups.cir
Cleanup cir scope if it contains only yield operation
Fixes: #455
> [CIR] Cleanup cir.scopes with a single cir.yield operation

- clang/lib/CIR/CodeGen/CIRGenCXXABI.cpp
- clang/lib/CIR/CodeGen/CIRGenCXXABI.h
- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenTypeCache.h
- clang/test/CIR/CodeGen/new.cpp
- clang/test/CIR/Lowering/new.cpp
This patch adds the minimal support for array cookies needed to enable ClangIR generation for an array new expression that requires cookies but does not require an explicit initializer.
This only provides the cookie support for the base Itanium CXXABI. Different cookie calculations are required for AppleARM64, which will be added in a subsequent patch.
> [CIR] Add initial support for array cookies

- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
Change `parseVisibilityAttr` to use enum parser helper `parseOptionalCIRKeyword`
Fixes: #770
> [CIR][NFC] Teach op parsers to use enum keyword parsing helpers

- clang/include/clang/CIR/Dialect/IR/CIRTypes.h
- clang/include/clang/CIR/Dialect/IR/CIRTypesDetails.h
- clang/lib/CIR/CodeGen/CIRAsm.cpp
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
- clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp
- clang/lib/CIR/Dialect/IR/CIRDataLayout.cpp
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/LoweringPrepareX86CXXABI.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/agg-init2.cpp
- clang/test/CIR/CodeGen/call-via-class-member-funcptr.cpp
- clang/test/CIR/CodeGen/conditional-cleanup.cpp
- clang/test/CIR/CodeGen/coro-task.cpp
- clang/test/CIR/CodeGen/global-new.cpp
- clang/test/CIR/CodeGen/lambda.cpp
- clang/test/CIR/CodeGen/move.cpp
- clang/test/CIR/CodeGen/new-null.cpp
- clang/test/CIR/CodeGen/packed-structs.c
- clang/test/CIR/CodeGen/paren-list-init.cpp
- clang/test/CIR/CodeGen/struct.c
- clang/test/CIR/CodeGen/try-catch-dtors.cpp
- clang/test/CIR/CodeGen/union-padding.c
This PR adds padding for union type, which is necessary in some cases (e.g. proper offset computation for an element of an array).
The previous discussion is here #1281 
The idea is to add a notion about padding in the `StructType`  in the same fashion as it's done for packed structures - as a bool argument in the constructor.
Now we can compute the proper union type size as a size of the largest element + size of padding type.
There are some downsides though - I had to add this `padded` word in many places.  So take a look please!
There are many tests fixed and one new - `union-padding`
> [CIR][CIRGen] Add padding to unions

- clang/test/CIR/Lowering/ptrstride.cir
Fixing Lit test after rebasing
`CIRToLLVMPtrStrideOpLowering` will not emit casting in this case because the width is equal to *layoutWidth
https://github.com/llvm/clangir/blob/d329c96a56b41ad99ddffe7bd037ac4ab7476ce6/clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp#L967-L999
Fixes: #1295
> [CIR] Fix Lowering/ptrstride.cir xfailed after rebasing

- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/test/CIR/CodeGen/new.cpp
- clang/test/CIR/Lowering/new.cpp
This handles initialization of array new allocations in the simple case
where the entire allocated memory block can be initialized with a memset
to zero.
> Implement support for zero-initialized builtin type allocation

- clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp
- clang/test/CIR/CodeGen/applearm64-array-cookies.cpp
- clang/test/CIR/Lowering/applearm64-new.cpp
This change introduces CIRGenCXXABI subclasses for ARM and AppleARM64 and implements ARM CXXABI handling for array cookies.
> [CIR][CIRGen] Implement array cookie ABI for AppleARM64 targets

- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/test/CIR/CodeGen/new.cpp
- clang/test/CIR/Lowering/new.cpp
This implements CIR generation for the case where an array is allocated with array new and a partial initialization list is provided.
> [CIR] Implement partial initialization for array new

- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/test/CIR/CallConvLowering/AArch64/aarch64-cc-structs.c
This PR fixes two run time bugs in the calling convention pass. These bugs were found with `csmith`.
Case #1.  Return value from a function. 
Before this PR the returned value were stored in a bit casted memory location.
But  for the next example it's not  safe: the size of a memory slot is less than the size of return value. And the store operation cause a segfault!
```
#pragma pack(push)
#pragma pack(1)
int f0 : 18;
int f1 : 31;
int f2 : 5;
int f3 : 29;
int f4 : 24;
} PackedS;
#pragma pack(pop)
```
CIR type for this struct is `!ty_PackedS1_ = !cir.struct<struct "PackedS1" {!cir.array<!u8i x 14>}>`,  i.e. it occupies 14 bytes.
Before this PR the next code 
```
PackedS foo(void) {
PackedS s;
return s;
}
void check(void) {     
PackedS y = foo();    
}
```
produced the …
> [CIR][ABI][Lowering] Fixes calling convention 

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/test/CIR/CodeGen/CUDA/simple.cu
- clang/test/CIR/CodeGen/Inputs/cuda.h
Adds support for `__host__` and `__device__` functions when compiling for CUDA host.
The conditions I checked against is taken from OG.
> [CIR][CUDA] Initial support for host compilation

- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/test/CIR/CodeGen/CUDA/simple-device.cu
This allows a simple CUDA file to compile with `-fcuda-is-device`.
> [CIR][CUDA] Initial support for device compilation

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/binop-bool.cir
Add !cir.bool to the list of types accepted by the binop rewriter. Although we don't generate boolean binops from logical operations on C++ boolean values, there will be cases where such operations are useful while generating conditions for other operations, such as the overflow checks needed for array new handling.
> [CIR] Enable cir.bool binops

- clang/include/clang/CIR/Dialect/IR/CIRAttrVisitor.h
- clang/include/clang/CIR/Dialect/IR/CMakeLists.txt
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- mlir/test/mlir-tblgen/attrdefs.td
- mlir/tools/mlir-tblgen/AttrOrTypeDefGen.cpp
This adds a new mlir-tablegen option to generate a .inc file with the complete set of attrdefs defined in a .td file and uses the file generated for CIR attrdefs to create an attr visitor. This visitor is used in the lowering of global variables directly to LLVM IR.
The purpose of this change is to align the incubator lowering implementation with the recent upstream changes to make future upstreaming easier, while also fulfilling the upstream request to have the visitor be based on a tablegen created file.
The new mlir-tablegen feature will be upstreamed after it is established here.
No observable change is intended in the CIR code.
> [CIR] Add attribute visitor for lowering globals

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/test/CIR/CodeGen/HIP/simple.cpp
Adds support for `__host__` and `__device__` functions when compiling for CUDA host.
The PR follows the structure of #1309
> [CIR][HIP] Compile host code

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-misc.c
Lowering `builtin_neon_vuzp_v` and `builtin_neon_vuzpq_v`
[Clang CGBuiltin Implementation](https://github.com/llvm/clangir/blob/2b1a638ea07ca10c5727ea835bfbe17b881175cc/clang/lib/CodeGen/CGBuiltin.cpp#L8606-L8622)
> [CIR][CIRGen][Builtin][Neon] Lower neon_vuzp_v and neon_vuzpq_v

- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/test/CIR/CodeGen/HIP/simple-device.cpp
> [CIR][HIP] Compile HIP device code

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/atomic.cpp
This addresses https://github.com/llvm/clangir/issues/1273.
`Nand` is missing here, as i didn't intuitively know how to implement it initially. 
I think I have figured it out and will push in an upcoming commit.
> [CIR][CIRGen] Handle __sync_{and,or,xor}_and_fetch

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-misc.c
Lowering `builtin_neon_vzip_v` and `builtin_neon_vzipq_v`
[Clang CGBuiltin Implementation](https://github.com/llvm/clangir/blob/2b1a638ea07ca10c5727ea835bfbe17b881175cc/clang/lib/CodeGen/CGBuiltin.cpp#L8628-L8644)
> [CIR][CIRGen][Builtin][Neon] Lower neon_vzip_v and neon_vzipq_v

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Clang CGBuiltin Implementation: https://github.com/llvm/clangir/blob/a7383c9d05165d16edba857ddc86e5d29d94d2cc/clang/lib/CodeGen/CGBuiltin.cpp#L9562-L9566
Similar commit: https://github.com/llvm/clangir/commit/f9dee671d97b6184261358ab8815603327a2c229
Closes: https://github.com/llvm/clangir/issues/1325
> [CIR][CIRGen][Builtin][Neon] Lower neon_vsra_n_v and neon_vsraq_n_v

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
This change refactors the CIRToLLVMGlobalOpLowering handling to align with changes that were requested upstream. The upstream changes didn't entirely fit with the full incubator implementation but these changes fit the goals of the upstream refactoring into the current implementation.
No observable changes are intended for this change.
> [CIR][NFC] Refactor GlobalOpLowering to align with upstream

- clang/lib/CIR/CodeGen/CIRGenCUDARuntime.cpp
- clang/lib/CIR/CodeGen/CIRGenCUDARuntime.h
- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.h
- clang/lib/CIR/CodeGen/CMakeLists.txt
- clang/test/CIR/CodeGen/CUDA/simple.cu
Now we're able to generate device stubs.
A simple explanation:
We first store function arguments inside a `void* args[]`, which shall be passed into `cudaLaunchKernel`.
Then we retrieve configuration using `__cudaPopCallConfiguration`, popping the config pushed by callsite. (We can't generate calls to kernels currently.)
Now we have enough arguments. Invoke `cudaLaunchKernel` and we're OK.
> [CIR][CUDA] Generate device stubs

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/CodeGen/atomic-thread-fence.c
Fix https://github.com/llvm/clangir/issues/1274
Implements atomic thread fence synchronization primitive corresponding to `atomic.thread_fence` CIR.
> [CIR][CIRGen] Support for builtin `__atomic_thread_fence`

- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/test/CIR/CallConvLowering/AArch64/aarch64-cc-structs.c
In [PR#1074](https://github.com/llvm/clangir/pull/1074) we introduced calls for struct types > 128 bits, but there's is an issue here. 
[This](https://github.com/llvm/clangir/blob/3e17e7b9404e1a28bf33bdd5943f4a208134d479/clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp#L1169) is meant to be a `memcpy` of the alloca instead of directly passing the alloca, just like in the [OG](https://github.com/llvm/clangir/blob/3e17e7b9404e1a28bf33bdd5943f4a208134d479/clang/lib/CodeGen/CGCall.cpp#L5323). The PR was meant to use a `memcpy` and later handle cases where we don't need the `memcpy`.
For example, running the following code snippet `tmp.c` using `bin/clang tmp.c -o tmp -Xclang -fclangir -Xclang -fclangir-call-conv-lowering --target=aarch64-none-linux-gnu`: 
```
#include …
```
> [CIR][ABI][AArch64][Lowering] Fix calls for struct types > 128 bits

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/lib/CIR/CodeGen/TargetInfo.h
This is only a skeleton following OG, and shouldn't have changed any visible behaviour.
> [CIR][CUDA][NFC] Skeleton of  `setCUDAKernelCallingConvention`

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-ldst.c
Lower `neon_vstl1_lane_s64` and `vstl1q_lane_s64`
> [CIR][CIRGen][Builtin][Neon] Lower neon_vstl1_lane_s64 and vstl1q_lane_s64

- clang/lib/CIR/CodeGen/CIRGenCUDARuntime.cpp
- clang/lib/CIR/CodeGen/CIRGenCUDARuntime.h
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/test/CIR/CodeGen/CUDA/simple.cu
Now we could generate calls to `__global__` functions.
Most work is already done in AST. It rewrites `fn<<<2, 2>>>()` to something like `__cudaPushCallConfiguration(dim3(2, 1, 1), dim3(2, 1, 1), 0, nullptr)`, which returns a bool. We calls the device stub as a normal function when the call returns true.
> [CIR][CUDA] Generate kernel calls

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/Dialect/Transforms/HoistAllocas.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/CodeGen/const-alloca.cpp
This PR adds support for lowering local constants in nested scopes, including those in nested loops.
For those constant allocas in non-loop inner scopes, this PR keeps their constant flags during alloca hoisting. LLVM lowering would correctly emit necessary invariant metadata for those allocas.
For those constant allocas in a loop, this PR introduces a new operation `cir.invariant_group` that marks the beginning of the lifetime of the constant objects. This operation is put at the location of the alloca operation before hoisting them. This PR updates LLVM lowering to emit the necessary invariant metadata when loading and storing through such pointers.
This PR takes care of the special case where the constant alloca represents a variable declared in the condition part of a while loop. In …
> [CIR] Lower nested local constant alloca

- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-ldst.c
Lower `neon_vldap1_lane_s64` and `vldap1q_lane_s64`
To add atomic `MemOrder` I changed the return type of builder to return LoadOp similar to our builders for StoreOp.
> [CIR][CIRGen][Builtin][Neon] Lower neon_vldap1_lane_s64 and vldap1q_lane_s64

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower neon_vsrad_n_s64

- clang/lib/CIR/CodeGen/CIRGenAtomic.cpp
- clang/test/CIR/CodeGen/atomic.cpp
Traditional Clang implementation: https://github.com/llvm/clangir/blob/a0091e38f1027e35d17819e02ee1ae257a12d296/clang/lib/CodeGen/CGAtomic.cpp#L545-L550
> [CIR][CIRGen] Atomics: handle atomic_compare_exchange_weak

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/test/CIR/CodeGen/builtins-elementwise.c
Traditional Clang implementation: https://github.com/llvm/clangir/blob/a0091e38f1027e35d17819e02ee1ae257a12d296/clang/lib/CodeGen/CGBuiltin.cpp#L4116-L4118
I use the first argument type as the return type. It is OK for `__builtin_elementwise_acos`, however, I'm not sure it is OK for other builtin functions.
Resolves: https://github.com/llvm/clangir/issues/1361
> [CIR][CIRGen] handle `__builtin_elementwise_acos`

- clang/lib/CIR/CodeGen/CIRGenDecl.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/Dialect/IR/CIRAttrs.cpp
- clang/test/CIR/CodeGen/CUDA/address-spaces.cu
CUDA shared variables are device-only, accessible from all threads in a block of some kernel. It's similar to `local` variables in OpenCL which all threads in a work-group can access. Hence they are realized as `static` variables in addrspace(local).
On the other hand, the local variables inside a kernel (without special attributes) are just regular variables, typically emitted by `CreateTempAlloca`. They are in the default address space.
OG checks if the expected address space, denoted by the type, is the same as the actual address space indicated by attributes. If they aren't the same, a `addrspacecast` is emitted when a global variable is accessed. In CIR however, `cir.get_global` alreadys carries that information in `!cir.ptr` type, so we don't need  a cast.
> [CIR][CUDA] Handle shared and local variables

- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/test/CIR/CodeGen/new.cpp
- clang/test/CIR/Lowering/new.cpp
Add an implementation for array new initialization of multidimension arrays. This is able to leverage existing array element initialization with just a few changes to update the pointer types.
> [CIR] Add handling for initializing multi-dimension arrays

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower neon_vshrd_n_u64

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower neon_vsrad_n_u64

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/globals-ref-globals.c
This PR fixes a case with global vars replacement when an array element is neither a`GlobalView` nor `ConstArray` but just a null pointer . Previously we  just skip such element. 
Basically, the case in question is `static S* global[] = {0, &another_global}`
> [CIR][Bugfix] fixes global array of pointers

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/bf16-getset-intrinsics.c
- clang/test/CIR/CodeGen/AArch64/v8.2a-neon-intrinsics-generic.c
Lower vgetq_lane_bf16, vduph f16 and fb16
> [CIR][CIRGen][Builtin][Neon] Lower vgetq_lane_bf16, vduph f16 and fb16

- clang/include/clang/CIR/Dialect/IR/CIRTBAAAttrs.td
- clang/lib/CIR/CodeGen/CIRGenTBAA.cpp
- clang/lib/CIR/CodeGen/CIRGenTBAA.h
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/CodeGen/tbaa-struct.cpp
This patch introduces `CIR_TBAAStructAttr`, which encodes the type and offset of each field in a struct, although it may lead to some duplication in `CIR`. If we manage `cir::TBAAStructAttr` by adding a new method to `ASTRecordDeclInterface`, it will also introduce duplication between `CIRGen` and LLVM lowering.
> [CIR][CIRGen][TBAA] add CIR_TBAAStructAttr

- clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp
- clang/test/CIR/CodeGen/try-catch.cpp
Currently, trying to generate CIR for the following code snippet `yield.cpp` fails. Using `bin/clang++ yield.cpp -Xclang -fclangir -Xclang -emit-cir -S -o -`: 
``` 
struct S {
S() {};
int a;
};
void foo() {
try {
S s;
} catch (...) {
foo();
}
}
```
The error: 
```
loc("yield.cpp":6:6): error: 'cir.yield' op must be the last operation in the parent block
```
There is an extra YieldOp! The CIR dump before verification looks something like:
```
"cir.scope"() ({
%0 = "cir.alloca"() <{alignment = 4 : i64, allocaType = !cir.struct<struct "S" {!cir.int<s, 32>} #cir.record.decl.ast>, ast = #cir.var.decl.ast, init, name = "s"}> : () -> !cir.ptr<!cir.struct<struct "S" {!cir.int<s, 32>} #cir.record.decl.ast>>
"cir.try"() <{catch_types = [#cir.all]}> ({
"cir.call"(%0) <{callee = @_ZN1SC1Ev, …
```
> [CIR][CodeGen] Fix extra Yieldop case during try-catch generation

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtins-elementwise.c
Original Clang's implementation: 
https://github.com/llvm/clangir/blob/2df2022c90e00c0eac542eba4078e79306155c7b/clang/lib/CodeGen/CGBuiltin.cpp#L4131-L4133
https://github.com/llvm/clangir/blob/2df2022c90e00c0eac542eba4078e79306155c7b/clang/lib/CodeGen/CGBuiltin.cpp#L762-L776
Compared with non-elementwise exp
https://github.com/llvm/clangir/blob/2df2022c90e00c0eac542eba4078e79306155c7b/clang/lib/CodeGen/CGBuiltin.cpp#L3006-L3016
https://github.com/llvm/clangir/blob/2df2022c90e00c0eac542eba4078e79306155c7b/clang/lib/CodeGen/CGBuiltin.cpp#L669-L685
elementwise version doesn't handle constrained situation. I'm not sure whether it is intended.
For renaming, it is to match original clang's implementation closely.
Resolves: https://github.com/llvm/clangir/issues/1375
> [CIR][CIRGen] handle `__builtin_elementwise_exp`

- clang/lib/CIR/CodeGen/Address.h
- clang/lib/CIR/CodeGen/CIRAsm.cpp
- clang/lib/CIR/CodeGen/CIRGenAtomic.cpp
- clang/lib/CIR/CodeGen/CIRGenBuilder.cpp
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/lib/CIR/CodeGen/CIRGenCXX.cpp
- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/lib/CIR/CodeGen/CIRGenDecl.cpp
- clang/lib/CIR/CodeGen/CIRGenException.cpp
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp
- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp
- clang/test/CIR/CodeGen/atomic-thread-fence.c
- clang/test/CIR/CodeGen/atomic-xchg-field.c
- clang/test/CIR/CodeGen/atomic.cpp
- clang/test/CIR/CodeGen/union-init.c
There were problems with the pointer type and element type of the Address class getting out of sync. In the traditional codegen the pointer has no type, so it was sufficient for the Address class to simply track the type it was supposed to be pointing to. Since ClangIR pointer values are typed, the Address::withType function wasn't really doing what it was supposed to. It returned an object with the same pointer that the original object had, but with a mismatched element type.
This change updates the Address::withType function to perform a bitcast to get the expected pointer type before creating a new Address object. It also adds assertions in the Address class to verify that pointer type and element type are consistent and updates many places that were causing those assertions to fire. …
> [CIR] Fix Address element type problems

- clang/lib/CIR/Dialect/Transforms/TargetLowering/CMakeLists.txt
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/TargetInfo.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/NVPTX.cpp
- clang/test/CIR/CodeGen/CUDA/simple.cu
Added a skeleton of NVPTX target lowering info.
This enables lowering of `simple.cu` (as it hardly tests device side functionalities), so a test of LLVM IR is also added onto it.
> [CIR][CUDA] Skeleton of NVPTX target lowering info

- clang/include/clang/CIR/Dialect/IR/CIRCUDAAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIRDialect.td
- clang/lib/CIR/CodeGen/CIRGenCUDARuntime.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/CUDA/registration.cu
- clang/test/CIR/CodeGen/CUDA/simple.cu
- clang/test/CIR/CodeGen/HIP/simple.cpp
This is a preparation of generating registration functions in LoweringPrepare.
CUDA compilation works as follows (irrelevant arguments omitted):
```sh
clang++ test.cu -fcuda-is-device -o device.s
ptxas device.s --output-file device.o
fatbin --create device.fatbin --image=profile=sm_52,file=device.o
clang++ test.cu -fcuda-include-gpubinary device.fatbin -cuid="some unique id"
```
And from the name of GPU binary, we can obtain a handle for registration. So we add an attribute to ModuleOp, recording that name.
If that `-fcuda-include-gpubinary` is not specified (like in the test `simple.cu`), OG will not generate any registration function. We do the same here by not generating the attribute.
> [CIR][CUDA] Add attribute for CUDA fat binary name

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Lower neon_vrshrd_n for s64 and u64
> [CIR][CIRGen][Builtin][Neon] Lower neon_vrshrd_n for s64 and u64

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/CodeGen/pointer-to-member-func.cpp
- clang/test/CIR/Lowering/struct.cir
This PR adds support for LLVM lowering of pointers to member functions. The lowering is ABI-specific and this patch only considers Itanium ABI.
Itanium ABI lowers pointers to member functions to a struct with two fields of type `ptrdiff_t`. To extract fields from such aggregate values, this PR includes a new operation `cir.extract_member` to accomplish this.
> [CIR] LLVM lowering support for pointers to member functions

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Lower builtin_neon_vqshlud_n_s64
> [CIR][CIRGen][Builtin][Neon] Lower builtin_neon_vqshlud_n_s64

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtin-bitreverse.c
This PR adds CIRGen and LLVM lowering support for the `__builtin_bitreverse` family of builtin functions.
> [CIR] Add support for __builtin_bitreverse

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp
- clang/test/CIR/CallConvLowering/x86_64/basic.cpp
This deals with some x86 aggregate types for CallConvLowering pass.
Suppose we have a simple struct like this.
```cpp
struct dim3 { int x, y, z; };
```
It can be coerced into
```cpp
struct dim3_ { uint64_t xy; int z; };
```
And for a function that receives it as an argument, OG does the following transformation for x86:
```cpp
void f(dim3 arg) { /* Before */ }
void f(uint64_t xy, int z) { /* After */ }
```
Now this transformation is implemented in the CallConvLowering pass of CIR.
> [CIR] CallConvLowering for X86 aggregate

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/v8.5a-neon-frint3264-intrinsic.c
> [CIR][CIRGen][Builtin][Neon] Lower vrnd32z and vrnd32zq

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/test/CIR/CodeGen/try-catch.cpp
This PR adds support for returns inside of a TryOp, for example: 
```
void foo() {
int r = 1;
try {
return;
++r;
} catch (...) {
}
}
```
Currently, it fails during the CodeGen with: 
```
error: 'cir.return' op expects parent op to be one of 'cir.func, cir.scope, cir.if, cir.switch, cir.do, cir.while, cir.for, cir.case'
```
were TryOp's omitted on purpose?
> [CIR][CodeGen] Support return in TryOp

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/CUDA/mangling.cu
Includes function name while mangling C functions to avoid link errors. [This is the same way OG handles it](https://github.com/llvm/clangir/blob/c301b4a0d3d2d79b26c9c809c11b8a1137c0a9ec/clang/lib/CodeGen/CodeGenModule.cpp#L1896).
> [CIR][CUDA] Fix CUDA CIR mangling bug

- clang/lib/CIR/.clang-tidy
- clang/lib/CIR/FrontendAction/.clang-tidy
Commit the .clang-tidy files for ClangIR.  The biggest different between these and the Clang files is the capitalization of variable names.  Most ClangIR code follows the MLIR conventions instead of the Clang conventions.
> [CIR] ClangIR specific .clang-tidy files

- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/pointer-to-member-func.cpp
The CIRGen support is already there. This PR adds LLVM lowering support for comparisons between pointers to member functions. Note that pointers to member functions could only be compared for equality.
> [CIR] Add support for comparisons between pointers to member functions

- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
Run clang-tidy on `CIRGenFunction.cpp` and fix all the issues that were identified.  The vast majority of issues were the case of parameter and variable names.  Some of the issues that didn't have to do with names had to be resolved manually.
There should be no behavior changes.
> [CIR] clang-tidy CIRGenFunction.cpp

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIRDialect.td
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/attribute-annotate-multiple.cpp
- clang/test/CIR/CodeGen/dlti.c
- clang/test/CIR/CodeGen/sourcelocation.cpp
To give LoweringPrepare type information from `CIRGenTypeCache`, this PR adds two attributes to ModuleOp:
```mlir
module attributes {
cir.int_size = #cir.int_size<32>,
cir.size_type_size = #cir.size_type_size<64>,
...
} {}
```
The `CIRDataLayout` class is also extended to have `getPtrDiffTy` and so on.
Some tests that only expects `cir.lang` and `cir.sob` are also changed to take this into account.
> [CIR] Track size_t and int size with module attributes

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
If type of operand is not integer, it can be handled like what I do in `__builtin_elementwise_exp`.
> [CIR][CIRGen] Simplify __builtin_elementwise_abs

- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/pointer-to-member-func.cpp
This patch adds support for simple cast operations on pointers to member functions, including: 1) casting pointers to member function values to boolean values; 2) reinterpret casts between pointers to member functions.
> [CIR] Simple casts on pointers to member functions

- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/test/CIR/IR/invalid.cir
This uses the assembly format for the optional return type and keeps a custom printer/parser only for function parameters, which still require a custom form for ellipses.
> [CIR] Simplify FuncType printer/parser

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/v8.5a-neon-frint3264-intrinsic.c
> [CIR][CIRGen][Builtin][Neon] Lower vrnd64z and vrnd64zq

- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
- clang/test/CIR/Lowering/ThroughMLIR/array.c
- clang/test/CIR/Lowering/ThroughMLIR/array.cir
for example, lower 
`cir.alloca !cir.array<!s32i x N>, !cir.ptr<!cir.array<!s32i x N>>` 
to `memref.alloca() : memref<Nxi32>`
see https://github.com/llvm/clangir/issues/1405
> [CIR][ThroughMLIR] remove nested memref wrapper for array types

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/IR/invalid.cir
Get rid of the function `FuncOp::verifyType`.  The function performed three checks:
1. Check that `isa<cir::FuncType>(getFunctionType())`.  This is a tautology that is always true, since the return type of `getFunctionType()` is already `cir::FuncType`.
2. Report an error if `type.isVarArg() && type.getNumInputs() == 0`, i.e. when a variadic function has no named parameters.  That check is incorrect.  In C++, variadic functions don't need to have any named parameters.  `void f(...) { }` is legal in C++ and ClangIR needs to be able to compile it.
3. Report an error when the return type is `void`.  This check is correct (`void` return is represented as no return in MLIR), but it is redundant.  This is already checked in `FuncType::verify`.
Since `FuncOp::verifyType` serves no useful …
> [CIR] Delete `FuncOp::verifyType`

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
Run clang-tidy on `clang/lib/CIR/CodeGen/CIRGenModule.cpp`.  Accept all of the recommended fixes, except for one suggestion to use `std::any_of`.  The vast majority of the changes had to do with the case of identifiers, changing variables and parameters from `VarName` to `varName`.
> [CIR] clang-tidy CIRGenModule.cpp

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenAtomic.cpp
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/atomic-runtime.cpp
- clang/test/CIR/CodeGen/atomic-xchg-field.c
- clang/test/CIR/CodeGen/atomic.cpp
- clang/test/CIR/Lowering/syncscope.cir
I noticed that `AtomicFenceOp` doesn't use `OptionalAttr` like mlir llvmir. As a result, `getLLVMSyncScope` does't return `std::optional`. Should I use `Arg` instead?
> [CIR] Add syncscope to AtomicCmpXchgOp

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Interfaces/CIROpInterfaces.td
- clang/lib/CIR/Interfaces/CIROpInterfaces.cpp
Cleans up default linkage query implementations. Removes duplicities from `extraClassDeclaration` that are now introduced through `CIRGlobalValueInterface`. This makes it more consistent with the `llvm::GlobalValue` methods.
> [CIR] Clean up and complete CIRGlobalValueInterface methods

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRCXXABI.h
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/CodeGen/pointer-to-member-func.cpp
This PR adds CIRGen and LLVM lowering support for base-to-derived and derived-to-base cast operations on pointers to member functions.
This PR includes a new operation `cir.update_member` to help the LLVM lowering procedure of such cast operations.
Resolve #973 .
> [CIR] Base-to-derived and derived-to-base casts on pointers to member functions

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/test/CIR/CodeGen/CUDA/destructor.cu
CIR didn't work on structs with destructor but without constructor. Now it is fixed.
Moreover, CUDA kernels must be emitted if it was referred to in the destructor of a non-device variable. It seems already working, so I just unblocked the code path.
> [CIR][CUDA] Fix destructor behaviour

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.h
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/lib/CIR/CodeGen/TargetInfo.h
Makes it consistent with C++ conventions and [OG](https://github.com/advay168/clangir/blob/436c635af6c7ec3d184a1f7e92a624acdf856991/clang/lib/CodeGen/CodeGenModule.cpp#L108).
> [CIR][CIRGen] Move CIRGenModule::getTargetCIRGenInfo() to CIRGenModule.cpp

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/atomic-thread-fence.c
This PR make CIR's AtomicFenceOp similar to MLIR LLVMIR's FenceOp.
MLIR LLVMIR FenceOp:
https://github.com/llvm/clangir/blob/0bedc285dc6fbd8486877887939c742c2ddaecfa/mlir/include/mlir/Dialect/LLVMIR/LLVMOps.td#L1925-L1947
> [CIR] Change AtomicFenceOp's syncscope to OptionalAttr

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerModule.cpp
- clang/test/CIR/CodeGen/CUDA/simple-nvptx-triple.cu
Similar to [OG](https://github.com/llvm/clangir/blob/8746bd4bbe777352c2935e9937449637a8943767/clang/lib/CodeGen/CodeGenModule.cpp#L219)
> [CIR][CUDA] Treat nvptx triple as alias for nvptx64

- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/test/CIR/CodeGen/ofstream.cpp
Currently, the following code snippet fails during CodeGen, using `clang++ tmp.cpp -fclangir -Xclang -emit-cir -S`:
```
#include <fstream>
void foo(const char *path) {
std::ofstream fout1(path);
fout1 << path;
std::ofstream fout2(path);
fout2 << path;
}
```
It fails with: 
```
error: 'cir.yield' op expects parent op to be one of 'cir.if, cir.scope, cir.switch, cir.while, cir.for, cir.await, cir.ternary, cir.global, cir.do, cir.try, cir.array.ctor, cir.array.dtor, cir.call, cir.case'
```
The relevant part of the CIR dump before verification looks like: 
```
"cir.br"()[^bb1] : () -> ()
^bb1:  // pred: ^bb0
"cir.yield"() : () -> ()
"cir.return"() : () -> ()
}) : () -> ()
```
Two things are wrong: the YieldOp has `cir.func` as a parent and there is a `cir.return` too. These come right after …
> [CIR][CodeGen] Fix std::ofstream fail during CodeGen

- clang/include/clang/CIR/Dialect/IR/CIRCUDAAttrs.td
- clang/lib/CIR/CodeGen/CIRGenCUDARuntime.cpp
- clang/lib/CIR/CodeGen/CIRGenCUDARuntime.h
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/CUDA/global-vars.cu
Currently `__shared__` and `__constant__` variables are ignored by CodeGen. This patch fixes this.
(It is also fixed in #1436 .)
Device and constant variables should be marked as `externally_initialized`, as they might be initialized by host, rather than on device. We can't identify which variables are device ones at lowering stage, so this patch adds a new attribute for it in CodeGen.
Similar to `__global__` functions, global variables on device corresponds to "shadow" variables on host, and they must be registered to their counterpart. I added a `CUDAShadowNameAttr` in this patch for later use, but I didn't insert code to actually generate it.
> [CIR][CUDA] Lowering device and shared variables

- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/test/CIR/CodeGen/CUDA/registration.cu
The generation is quite complicated so I plan to separate it into several parts.
The registration function should be like:
```cpp
const char *__cuda_fatbin_str = /* Raw content of file in -fcuda-include-gpubinary */;
struct {
int magicNum, version;
void *binaryData, *unused;
} __cuda_fatbin_wrapper = { /*CUDA Magic Num*/, 1, __cuda_fatbin_str, nullptr };
void __cuda_module_ctor() {
handle = __cudaRegisterFatBinary(&wrapper);
__cuda_register_globals();
}
```
In this PR, we generate everything except the `__cuda_register_globals` function.
OG doesn't give a name to `__cuda_fatbin_str`, which isn't allowed for cir::GlobalOp, so I invented a name for it. Other names are kept consistent with OG.
> [CIR][CUDA] Generate registration function (Part 1)

- clang/include/clang/CIR/FrontendAction/CIRGenAction.h
- clang/include/clang/CIR/LowerToLLVM.h
- clang/include/clang/CIR/LowerToMLIR.h
- clang/include/clang/Driver/Options.td
- clang/include/clang/Driver/Types.def
- clang/include/clang/Frontend/FrontendOptions.h
- clang/lib/CIR/CodeGen/CIRPasses.cpp
- clang/lib/CIR/FrontendAction/CIRGenAction.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
- clang/lib/Driver/Driver.cpp
- clang/lib/Driver/ToolChains/Clang.cpp
- clang/lib/Frontend/CompilerInvocation.cpp
- clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp
- clang/test/CIR/Lowering/ThroughMLIR/binop.cpp
- clang/test/CIR/Lowering/ThroughMLIR/bit.c
- clang/test/CIR/Lowering/ThroughMLIR/call.c
- clang/test/CIR/Lowering/ThroughMLIR/cmp.cpp
- clang/test/CIR/Lowering/ThroughMLIR/doWhile.c
- clang/test/CIR/Lowering/ThroughMLIR/for.cpp
- clang/test/CIR/Lowering/ThroughMLIR/global.cpp
- clang/test/CIR/Lowering/ThroughMLIR/if.c
- clang/test/CIR/Lowering/ThroughMLIR/vectype.cpp
- clang/test/CIR/Lowering/ThroughMLIR/while.c
- clang/test/CIR/cc1.c
- clang/test/CIR/emit-mlir.c
- clang/test/CIR/mlirprint.c
This PR adds the flag `-emit-mlir-llvm` to allow emitting of MLIR in the LLVM dialect (cc @xlauko who asked me to do this).
I'm not sure if the naming of the flag is the best and maybe someone will have a better idea.
Another solution would be to make the `-emit-mlir` flag have a value, that specifies the target dialect (CIR/MLIR std dialects/LLVM Dialect).
> [CIR] Add option to emit MLIR in LLVM dialect.

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/Lowering/attribute-lowering.cir
> [CIR] Fix attributes lowering for GlobalOp

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower vcagtd_f64

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-misc.c
> [CIR][CIRGen][Builtin][Neon] Lower neon vaddlvq_s32

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-arith.c
Similar PR: https://github.com/llvm/clangir/pull/1434
> [CIR][CIRGen][Neon] Make vrnda emit RoundOp directly

- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/NVPTX.cpp
- clang/test/CIR/CodeGen/CUDA/addrspace-lowering.cu
Based on https://github.com/llvm/clangir/blob/7f66a204c4ba1f674cfe0e16e2c9c6b65ca70bc8/clang/lib/Basic/Targets/NVPTX.h#L27, the current address space values are incorrect. This PR fixes these values.
> [CIR][CUDA] Fix address space values for NVPTX

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/MissingFeatures.h
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/lib/CIR/CodeGen/TargetInfo.h
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/CUDA/simple.cu
This implements the missing feature `cir::setTargetAttributes`.
Although other targets might also need attributes, this PR focuses on the CUDA-specific ones. For CUDA kernels (on device side, not stubs), they must have a calling convention of `ptx_kernel`. It is added here.
CUDA kernels, as well as global variables, also involves lots of NVVM metadata, which is intended to be dealt with at the same place. It's marked with a new missing feature here.
> [CIR][CUDA] Add target-specific attributes

- clang/include/clang/CIR/Dialect/IR/CIRDataLayout.h
- clang/lib/CIR/Dialect/IR/CIRDataLayout.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/test/CIR/CodeGen/CUDA/registration.cu
This is part 2 of CUDA lowering. Still more to come!
This PR generates `__cuda_register_globals` for functions only, without touching variables.
It also fixes two discrepancies mentioned in Part 1, namely:
- Now CIR will not generate registration code if there's nothing to register;
- `__cuda_fatbin_wrapper` now becomes a constant.
> [CIR][CUDA] Register __global__ functions

- clang/lib/CIR/CodeGen/CIRGenCUDARuntime.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/X86.cpp
- clang/test/CIR/CodeGen/CUDA/simple.cu
This PR deals with several issues currently present in CUDA CodeGen. Each of them requires only a few lines to fix, so they're combined in a single PR.
**Bug 1.**
Suppose we write
```cpp
__global__ void kernel(int a, int b);
```
Then when we call this kernel with `cudaLaunchKernel`, the 4th argument to that function is something of the form `void *kernel_args[2] = {&a, &b}`. OG allocates the space of it with `alloca ptr, i32 2`, but that doesn't seem to be feasible in CIR, so we allocated `alloca [2 x ptr], i32 1`. This means there must be an extra GEP as compared to OG.
In CIR, it means we must add an `array_to_ptrdecay` cast before trying to accessing the array elements. I missed that out in #1332 .
**Bug 2.**
We missed a load instruction for 6th argument to `cudaLaunchKernel`. It's …
> [CIR][CUDA] Miscellanous bugfixes

- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/test/CIR/CodeGen/CUDA/registration.cu
This is Part 3 of registration function generation.
This generates `__cuda_module_dtor`. It cannot be placed in global dtors list, as treating it as a normal destructor will result in double-free in recent CUDA versions (see comments in OG). Rather, the function is passed as callback of `atexit`, which is called at the end of `__cuda_module_ctor`.
> [CIR][CUDA] Generate CUDA destructor

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/lib/CIR/CodeGen/TargetInfo.h
- clang/test/CIR/CodeGen/CUDA/texture.cu
I have now fixed the test. Earlier I made some commits with other changes because we were testing something on my fork. This should be resolved now
> [CIR][CUDA] Support for inbuilt texture types

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/attribute-lowering.cir
CIR is currently ignoring the `signext` and `zeroext` for function arguments and return types produced by CallConvLowering.
This PR lowers them to LLVM IR.
> [CIR] Lower `signext` and `zeroext` attributes

- clang/include/clang/CIR/Dialect/IR/CIRTypes.h
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/NVPTX.cpp
- clang/test/CIR/CallConvLowering/NVPTX/basic.cpp
There are some subtleties here.
This is the code in OG:
```cpp
// note: this is different from default ABI
if (!RetTy->isScalarType())
return ABIArgInfo::getDirect();
```
which says we should return structs directly. It's correct, has have the same behaviour as `nvcc`, and it obeys the PTX ABI as well.
The comment dates back to 2013 (see [this commit](https://github.com/llvm/llvm-project/commit/f9329ff650fa252606c65977405189dc46e5d66f) -- it didn't provide any explanation either), so I believe it's outdated. I didn't include this comment in the PR.
> [CIR][CUDA] CallConvLowering for basic types in NVPTX

- clang/test/CIR/CodeGen/CUDA/cuda-builtin-vars.cu
The pattern `call {{.*}} i32` mismatches `call i32` due to double spaces surrounding `{{.*}}`. This patch removes the first space to fix the failure.
> [CIR][NFC] Fix test failures caused by double spaces in check line

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/IR/invalid.cir
Implements `::verify` for operations cir.atomic.xchg and cir.atomic.cmp_xchg
I believe the existing regression tests don't get to the CIR level type check failure and I was not able to implement a case that does.
Most attempts of reproducing cir.atomic.xchg type check failure were along the lines of:
```
int a;
long long b,c;
__atomic_exchange(&a, &b, &c, memory_order_seq_cst);
```
And they seem to never trigger the failure on `::verify` because they fail earlier in function parameter checking:
```
exmp.cpp:7:27: error: cannot initialize a parameter of type 'int *' with an rvalue of type 'long long *'
7 |     __atomic_exchange(&a, &b, &c, memory_order_seq_cst);
|                           ^~
```
Closes #1378 .
> [CIR] Implement ::verify for cir.atomic.xchg and cir.atomic.cmp_xchg

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenAtomic.cpp
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/lib/CIR/CodeGen/CIRGenValue.h
- clang/lib/CIR/Dialect/IR/CIRMemorySlot.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ItaniumCXXABI.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/builtin-nontemporal.cpp
This PR adds a new boolean flag to the `cir.load` and the `cir.store` operation that distinguishes nontemporal loads and stores. Besides, this PR also adds support for the `__builtin_nontemporal_load` and the `__builtin_nontemporal_store` intrinsic function.
> [CIR] Add support for nontemporal loads and stores

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/bitfields.c
- clang/test/CIR/CodeGen/int128.cpp
- clang/test/CIR/CodeGen/static-vars.c
- clang/test/CIR/CodeGen/static-vars.cpp
- clang/test/CIR/CodeGen/throw.cpp
- clang/test/CIR/CodeGen/try-catch.cpp
- clang/test/CIR/CodeGen/unary.cpp
- clang/test/CIR/Lowering/switch-while.c
- clang/test/CIR/Transforms/mem2reg.c
> [CIR] Emit nsw flag for unary integer operations

- clang/lib/CIR/CodeGen/CIRGenException.cpp
- clang/test/CIR/CodeGen/try-catch.cpp
This PR adds an insertion guard for the try body scope for try-catch. Currently, the following code snippet fails during CodeGen: 
```
void foo() {
int r = 1;
try {
++r;
return;
} catch (...) {
}
}
```
The insertion point doesn't get reset properly and the cleanup is being ran for a wrong/deleted block causing a segmentation fault. I also added a test.
> [CIR][CodeGen] Add InsertionGuard for tryBodyScope

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRStdOps.td
- clang/lib/CIR/Dialect/Transforms/IdiomRecognizer.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/test/CIR/Transforms/idiom-recognizer.cpp
The comments suggested that we should use TableGen to generate the recognizing functions. However, I think templates might be more suitable for generating them -- and I can't find any existing TableGen backends that let us generate arbitrary functions.
My choice of design is to offer a template to match standard library functions:
```cpp
// matches std::find with 3 arguments, and raise it into StdFindOp
StdRecognizer<3, StdFindOp, StdFuncsID::Find>
```
I have to use a TableGen'd enum to map names to IDs, as we can't pass string literals to template arguments easily in C++17.
This also constraints design of future `StdXXXOp`s: they must take operands the same way of StdFindOp, where the first one is the original function, and the rest are function arguments.
I'm not sure if this approach …
> [CIR][NFC] Generalize IdiomRecognizer

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower neon vcaltd_f64

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/builtins-memory.c
- clang/test/CIR/CodeGen/builtins.cpp
- clang/test/CIR/CodeGen/libcall.cpp
- clang/test/CIR/Lowering/builtin-binary-fp2fp.c
Ref: https://github.com/llvm/clangir/commit/cd269fee05a0f78fb53b65f701b4e06e9ddab424
Related: https://github.com/llvm/clangir/issues/1497
> [CIR] Backport clang commit to unxfail some builtin call

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtins-elementwise.c
Sub-issue of https://github.com/llvm/clangir/issues/1192. Adds CIR_ASinOp and support for __builtin_elementwise_asin.
> [CIR][CodeGen] Support for `__builtin_elementwise_asin`

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtins-elementwise.c
Sub-issue of https://github.com/llvm/clangir/issues/1192. Adds CIR_ATanOp and support for __builtin_elementwise_atan.
> [CIR][CodeGen] Support for `__builtin_elementwise_atan`

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenBuiltinNVPTX.cpp
- clang/test/CIR/CodeGen/CUDA/builtin-functions.cu
Clang relies on `llvm::Intrinsic::getOrInsertDeclaration` to handle functions marked as `ClangBuiltin` in TableGen. That function receives a `CodeGenModule*` so CIR can't use that. We need to re-implement parts of it.
> [CIR][CUDA] Handle clang builtin functions

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- Part of #70
This is not very useful now, as both branches of interest are NYI. I will try to implement the real features in subsequent patches.
> [CIR][CIRGen][NFC] Handle `PragmaComment` in `emitTopLevelDecl`

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
As noted in [this comment](https://github.com/llvm/clangir/issues/1442#issuecomment-2702327007), the nested if-arms in `GlobalOpLowering` are somewhat confusing and error-prone. This PR simplifies the logic into more straightforward components.
Since LLVM's GlobalOp accepts two types of initializers (either an initializer value or an initializer region), we've extracted the decision logic into a separate function called `lowerInitializer`. This function takes two inout arguments: `mlir::Attribute &init` (for the attribute value) and `bool useInitializerRegion` (as the decision indicator). All code paths then converge at a common epilogue that handles the operation rewriting.
The previous implementation for lowering `DataMemberAttr` initializers relied on recursion between MLIR rewrite …
> [CIR][LowerToLLVM][NFC] Refactor GlobalOpLowering for better readability and maintainability

- clang/lib/CIR/CodeGen/CIRGenTypes.h
Fix #1371.
Not sure about whether we could remove `convertTypeForMem` completely. Let's fix the doc first.
> [CIR][NFC] Rectify the documentation of convertTypeForMem

- clang/lib/CIR/CodeGen/CIRGenFunction.h
This change moves all declarations of emit* functions in CIRGenFunction.h into a common location and sorts them alphabetically. The goal of this change is to make it easier to keep upstream and incubator code in a consistent location, making functions easier to find for upstreaming and minimizing conflicts in the incubator when rebasing.
I did most of this sort manually, and I've probably been inconsistent in how I treat sorting of uppercase versus lowercase. I made no attempt to provide a rule for ordering different declarations of functions with the same name. We can improve on that over time if anyone feels the need.
I tried very hard not to drop comments (one of the reasons I had to do this manually), but I may have lost a few.
This change loses the grouping of some declarations that …
> [CIR][NFC] Sort emit functions in CIRGenFunction.h

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Lower `vabds_f32` and `vabdd_f64`
> [CIR][CIRGen][Builtin][Neon] Lower vabds_f32 and vabdd_f64

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower vmaxv_s32

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower vmaxvq_f64

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/test/CIR/Lowering/linker-options.cir
> [CIR][LowerToLLVM] Support for LinkerOptions lowering

- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
In the review for upstreaming unary operation support (https://github.com/llvm/llvm-project/pull/131369), it was suggested that the VisitPlus and VisitMinus functions should be combined. This is a backport of that refactoring.
> [CIR][NFC] Backport refactoring of unary plus/minus handling

- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerMLIRToLLVM.cpp
- clang/test/CIR/Lowering/ThroughMLIR/unreachable.cir
This also removes some unused `#include`s.
I choose to allow lowering to LLVM dialect when we're lowering CIR to MLIR core dialects, because some operations don't have their counterparts in these dialects (for example, `UnreachableOp -> llvm.unreachable` and `LLVMIntrinsicCallOp -> cir.llvm.intr.xxx`). I don't think we can delay them to the MLIR->LLVM pass as it seems we assume all CIR operations have been lowered after CIR->MLIR conversion.
> [CIR][ThroughMLIR] Lower UnreachableOp

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtins-elementwise.c
> [CIR][CIRGen][Builtin] Add `__builtin_elementwise_{log, log2, log10}`

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower vmaxnmv_f32

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/test/CIR/global-var-simple.cpp
Update getZeroInitAttr to cover more FP types, Backport from (https://github.com/llvm/llvm-project/pull/133100)
> [CIR] Backport support zero init attr for all FP types

- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
- clang/test/CIR/Lowering/ThroughMLIR/tan.cir
Adds implementation for TanOp's lowering via ThroughMLIR.
> [CIR][ThroughMLIR] Add TanOp Lowering

- clang/test/CIR/CodeGen/call-side-effect.cpp
Upstream commit changed behavior https://github.com/llvm/llvm-project/commit/ff585feacf58b384d7525d2b1368298435132fb4
I tested in original clang and it produced the same IR with clangir.
Related: https://github.com/llvm/clangir/issues/1497
> [CIR] Unxfail memory effect attribute test

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
ower vminnmv_f32, vminnmvq_f64 and vminnmvq_f32
> [CIR][CIRGen][Builtin][Neon] Lower vminnmv_f32, vminnmvq_f64 and vminnmvq_f32

- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/test/CIR/CodeGen/nullptr-init.cpp
When a pointer variable is initialized with a null pointer, the AST contains a NullToPointer cast. If we just emit a null pointer of the correct type, we will miss any side effects that occur in the initializer. This change adds code to emit the initializer expression if it is not a simple constant.
This results in an extra null pointer constant being emitted when the expression has side effects, but the constant emitted while visiting the expression does not have the correct type, so the alternative would be to capture the emitted constant and bitcast it to the correct type. An extra constant seems less intrusive than an unnecessary bitcast.
> [CIR] Fix for missing side effects during null pointer initialization

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
> [CIR][CIRGen][Builtin][Neon] Lower vminv_u32

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
These entries exist in OG but are not present in CIR codegen.
> [CIR][CIRGen][Builtin] Add skeleton for missing builtin entries. (NFC)

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtins-elementwise.c
Added:
- `cos`
- `floor`
- `round`
- `rint`
- `nearbyint`
- `sin`
- `sqrt`
- `tan`
- `trunc`
> [CIR][CIRGen][Builtin] Add several elementwise FP builtins

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Lower vminvq_f32 and vminvq_f64
> [CIR][CIRGen][Builtin][Neon] Lower vminvq_f32 and vminvq_f64

- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
During review of a patch for upstreaming the cir.struct type support, Erich Keane observed that the code we use for creating our type name for structures with templates was likely to be error prone. He recommended using getNameForDiagnostic instead.
After some experimentation, I found that with a couple of changes to the printing policy, I could get the same strings we currently produce by calling getNameForDiagnostic. This change does that.
Erich also pointed out that RecordDecls always have a DeclContext so a few other lines could be eliminated where that was checked.
> [CIR][NFC] Simplify struct type name creation

- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
A lot of the unary math op lowerings follow the same template -- we can templatize this to remove redundant code and make things a little more neater. (Similar to what we do [here](https://github.com/llvm/clangir/blob/e4b8a48fb4d9a72a85e38f5439bcfb0673b4bea2/clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp#L502))
I've checked all existing LIT tests via `ninja clang-check-cir` and they seem to be passing fine.
> [CIR][ThroughMLIR] Templatize unary math op lowerings.

- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/include/clang/CIR/Dialect/IR/CIRTypesDetails.h
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
This change reverse the polarity of the cir::RecordType incomplete attribute, making the attribute name "complete" and reversing all checks in the code accordingly. The asm layout still prints "incomplete" for records that are not complete and treats the absence of this text as meaning that the definition provided is complete.
No functional change is intended.
> [CIR][NFC] Reverse the polarity of RecordType complete/incomplete

- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/IR/getmember.cir
When we create a `cir.record` type, we track the `RecordKind` according to whether the source code declared the type using `struct` or `class` even though these are semantically equivalent. The distinction is used in naming the type when we lower to the LLVM dialect.
This change updates the code to remove the last place where we were handling class and struct records differently.
> [CIR] Treat cir.record class and struct types equivalently.

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/shift.cir
Negative shift amounts are undefined behavior in C and C++. Because of that we can always zero-extend the shift amount which is slightly faster on certain architectures (e. g. x86). This also matches the behavior of the original clang Codegen.
Backported from https://github.com/llvm/llvm-project/pull/133405
> [CIR] Always zero-extend shift amounts

- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
- clang/test/CIR/Lowering/ThroughMLIR/unreachable.cir
`cir.trap` corresponds to two operations, `call @llvm.trap` and `unreachable`. See the test case `Lowering/intrinsics.cir`.
> [CIR][ThroughMLIR] Lower TrapOp

- clang/lib/CIR/CodeGen/CIRGenCleanup.cpp
- clang/test/CIR/CodeGen/try-catch-dtors.cpp
Currently, the following code snippet fails with a crash during CodeGen
```
class C {
public:
~C();
void operator=(C);
};
void d() {
C a, b;
a = b;
}
```
with error: 
```
mlir::Block* clang::CIRGen::CIRGenFunction::getEHResumeBlock(bool, cir::TryOp): Assertion `tryOp && "expected available cir.try"' failed.
```
in CIRGenCleanup [these lines](https://github.com/llvm/clangir/blob/204c03efbe898c9f64e477937d869767fdfb1310/clang/lib/CIR/CodeGen/CIRGenCleanup.cpp#L615C1-L617C6) don't check if there is a TryOp when at the end of the scope chain before [getEHResumeBlock](https://github.com/llvm/clangir/blob/204c03efbe898c9f64e477937d869767fdfb1310/clang/lib/CIR/CodeGen/CIRGenException.cpp#L764) is called causing the crash, because it contains an assertion. 
This PR fixes this and adds a simple …
> [CIR][CodeGen] Fix crash during exception cleanup

- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/test/CIR/CodeGen/union-array.c
This is a just small fix that cover the case when the global union is declared with `static` keyword and one of the its users is an array
> [CIR][CodeGen] Supports const array user in the globals replacement

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/lib/CIR/CodeGen/CIRGenCUDANV.cpp
- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/lib/CIR/CodeGen/CIRGenVTables.cpp
- clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp
- clang/lib/CIR/CodeGen/ConstantInitBuilder.cpp
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/AArch64.cpp
Add `TypeBuilderWithInferredContext` to each CIR type that supports MLIR context inference from its parameters.
> [CIR] Infer MLIR context in type builders when possible

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/Dialect/IR/CIRAttrs.cpp
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
We have been using RecordLayoutAttr to "cache" data layout information calculated for records. Unfortunately, it wasn't actually caching the information, and because each call was calculating more information than it needed, it was doing extra work.
This replaces the previous implementation with a set of functions that compute only the information needed. Ideally, we would like to have a mechanism to properly cache this information, but until such a mechanism is implemented, these new functions should be a small step forward.
> [CIR] Replace RecordType data layout calculations

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/test/CIR/CodeGen/vectype-ext.cpp
- clang/test/CIR/CodeGen/vectype.cpp
Backport support for zero init Vector type
> [CIR] Backport support zero init for VectorType

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon.c
Lower vqsubd_s64 and vqadds_u32
> [CIR][CIRGen][Builtin][Neon] Lower vqsubd_s64 and vqadds_u32

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
Introduce common base class for attributes with single type parameter.
> [CIR] Create CIR_TypedAttr common class

- clang/include/clang/CIR/Dialect/IR/CIROps.td
This is a backport from https://github.com/llvm/llvm-project/pull/137184
> [CIR] Reorder YieldOp parents lexicographically

- clang/include/clang/CIR/Dialect/IR/CIROpenCLAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/CodeGen/CIRGenBuilder.cpp
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/CIRLowerContext.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/LoweringHelpers.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
> [CIR] Backport Standardize element type name in Array and Vector Types

- clang/include/clang/CIR/LoweringHelpers.h
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/lib/CIR/Lowering/LoweringHelpers.cpp
- clang/test/CIR/CodeGen/vectype-ext.cpp
- clang/test/CIR/CodeGen/vectype.cpp
In this PR I extended the incubator implementation to support global init for VectorType
> [CIR] Backport global initialization for VectorType

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
Use VectorType::get instead of the `getFixedVectorType` function because it's already removed PR https://github.com/llvm/llvm-project/pull/135051
> [CIR] Backport replacing removed getFixedVectorType with vectortype get

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRTypeConstraints.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.h
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/test/CIR/IR/invalid.cir
This refactors cir floating point type constraints, and fixes long double verifier to use constraints directly.
> [CIR] Refactor floating point type constraints

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRTypeConstraints.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp
- clang/lib/CIR/Dialect/IR/CIRAttrs.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/IR/CIRTypes.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/IR/invalid.cir
Apply `CIR_AnyIntOrFloatType` type constraint on element type and rename `elementTy` to `elementType`.
> [CIR] Refactor complex type

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/include/clang/CIR/Dialect/IR/CIRTypeConstraints.td
- clang/include/clang/CIR/Dialect/IR/CIRTypes.td
- Rename `PrimitiveIntOrFPPtr` to `CIR_PtrToIntOrFloatType` and broaden it to accept any floating-point type.
- Fix incorrect constraint name from `PrimitiveInt` to any `Int`; prior constraint already allowed arbitrary bitwidths, so the name was misleading.
- Rename `ComplexPtr` to `CIR_PtrToComplexType` for clarity.
> [CIR] Refactor constraints for integers, floats, and complex pointees

- clang/lib/CIR/CodeGen/ABIInfo.h
- clang/lib/CIR/CodeGen/CIRAsm.cpp
- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h
- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/lib/CIR/CodeGen/TargetInfo.h
Remove all the code the manages ABI info for arguments and return values in the initial CIR codegen. We prefer for the CIR to represent the types as they appear in the source code, with ABI handling being deferred until the lowering phase or calling convention transform.
The ABI handling being removed here was brought over from the classic codegen, but none of the effects being computed made it into the CIR so this change is effectively NFC.
This change leaves the `CIRGenFunctionInfoArgInfo` with just one member. That can be cleaned up in a later patch.
> [CIR] Remove ABI handling from CIRGen call handling

- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
- clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp
- clang/test/CIR/CodeGen/nonzeroinit-struct.cpp
There are some cases where we're currently using the zero attribute to initialize global variables for records that aren't properly zero-initializable. We weren't checking for that, and we also weren't properly calculating zero-initializability for records. This patch addresses both of these issues.
This doesn't actually handle the case where the record isn't zero-initializable. It just reports it as NYI. It does add a comment about what needs to be done.
> [CIR] Add code to detect non-zero-initializable records

- GettingStarted/upstream.md
- _data/upstream_progress.yml
- _includes/progress_section.html
This PR adds a new section to the `gh-pages` branch to track the progress of upstreaming CIR to the main LLVM repository.
Preview the page: [Upstream Progress Tracker](https://andres-salamanca.github.io/clangir/GettingStarted/upstream.html)
The page is generated using a Jekyll HTML template and dynamically populated from `_data/upstream_progress.yml`. It uses progress bars and dropdown menus to display the status of upstreaming for each feature, categorized into **Ops**, **Tys**, and **Passes** ... etc. Each item can be marked as completed once it’s upstreamed.
In this PR, I’ve included the list of operations (Ops). Other components like types and attributes will be added in a future PR.
> Initial PR for new section to track CIR upstream progress

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/CIRCanonicalize.cpp
- clang/test/CIR/Transforms/vector-extract-fold.cir
> [CIR] Backport folder implementation for VecExtractOp

- clang/lib/CIR/CodeGen/CIRGenException.cpp
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/test/CIR/CodeGen/dtors.cpp
Currently, the following code snippet fails with a crash: 
```
#include <stdio.h>
struct X {
int a;
X(int a) : a(a) {}
~X() {}
};
bool foo(const X &) { return false; }
bool bar() { return foo(1) || foo(2); }
```
it fails with 
```
error: 'cir.yield' op must be the last operation in the parent block
```
The crash can be traced to the [construction of the TernaryOp](https://github.com/llvm/clangir/blob/5df50096be1a783c26b48ea437523347df8a3110/clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp#L2728). A [yield](https://github.com/llvm/clangir/blob/5df50096be1a783c26b48ea437523347df8a3110/clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp#L2776) is created and when the LexicalScope is destroyed the destructors for the object follow. 
So, the CIR looks something like:
```
%11 = "cir.ternary"(%10) ({
%13 = …
```
> [CIR][CodeGen] Emit dtor properly for objects in TernaryOp

- clang/lib/CIR/CodeGen/CIRGenCall.cpp
- clang/lib/CIR/CodeGen/CIRGenFunctionInfo.h
- clang/lib/CIR/CodeGen/TargetInfo.cpp
A previous refactoring had reduced the ArgInfo structure to contain a single member, the argument type. This change eliminates the ArgInfo structure entirely, instead just storing the argument type directly in places where ArgInfo had previously been used.
> [CIR][NFC] Eliminate ArgInfo structure

- clang/test/CIR/CallConvLowering/AArch64/aarch64-cc-structs.c
- clang/test/CIR/CodeGen/clear_cache.c
- clang/test/CIR/CodeGen/complex.c
- clang/test/CIR/CodeGen/globals-neg-index-array.c
- clang/test/CIR/CodeGen/multi-vtable.cpp
- clang/test/CIR/CodeGen/vbase.cpp
- clang/test/CIR/CodeGen/vtable-emission.cpp
- clang/test/CIR/CodeGen/vtt.cpp
- clang/test/CIR/Lowering/ThroughMLIR/ptrstride.cir
- clang/test/CIR/Lowering/global-ptr.c
This commit un-xfails some tests that were affected by upstream GEP changes. #1497 
The changes are likely introduced by inference of `inbounds` and `nuw` flags https://github.com/llvm/llvm-project/commit/10f315dc9c96ec2413881ab55a285e35d80def88. It seems to allow LLVM to enable some constant foldings, whose effects include re-calculating the address using i8 and a single offset. (This change seems to arise from https://discourse.llvm.org/t/rfc-replacing-getelementptr-with-ptradd/68699/39)
> [CIR] Un-xfail some tests affected by GEP changes

- clang/include/clang/Basic/LangStandard.h
- clang/include/clang/Driver/Types.def
- clang/lib/Frontend/CompilerInvocation.cpp
- clang/lib/Frontend/FrontendOptions.cpp
- clang/test/CIR/cc1.cir
Reapplying https://github.com/llvm/clangir/commit/e66b670f3bf9312f696e66c31152ae535207d6bb which was reverted during rebase (after fixing some conflicts). Un-xfails the test `cc1.cir` (#1497).
> [CIR] Add back ability to process cir files in cc1

- clang/lib/CIR/CodeGen/CIRGenBuilder.cpp
- clang/test/CIR/CodeGen/globals-ref-globals.c
This commit attempts to un-xfail `globals-ref-globals` test (#1497), which was causing a crash in addition to GEP changes.
The crash was caused by incorrect offsets being calculated for global view indices. The original calculation did not take paddings into consideration, hence triggering a crash. This commit adds type alignment when calculating the offset, which will take care of paddings.
Further modification to `globals-ref-globals` test includes fixing some struct names that got changed, as well as replacing the expects with constant folded GEP.
> [CIR] Fix offset calculation for global view

- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.h
Previously, when emitting a global for a string literal, we were creating a GlobalOp, building a GlobalView attr for it, and looking up the global from the symbol associated with the attr. This change splits out the function that creates the global so that the global is returned directly and the GlobalView attribute is only created in the case where it is needed.
This also updates the mechanism used for uniquing the global name used for the strings so that if different base names are used the uniquing numbers each base name separately. The mangling of the global used for strings is not implemented, but the uniquing was happening prior to the mangling. This change drops the uniquing below the placeholder for mangling.
> [CIR] Simlipify string literal global creation

- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRLoopToSCF.cpp
- clang/test/CIR/Lowering/ThroughMLIR/for-reject-1.cpp
- clang/test/CIR/Lowering/ThroughMLIR/for-reject-2.cpp
Currently the ForOp handling ignores everything except load, store and arithmetic in the step region. It does not detect whether the step and induction variable has already been assigned, either.
That might result to wrong behaviour:
```cpp
// Ignores printf
for (int i = 0; i < n; i++, printf("\n"));
// Only increments once
for (int i = 0; i < n; i++, i++);
```
I choose to rewrite the detection and do an exact match of the instruction sequence for `i++` and `i += n`. It doesn't seem easy to detect a more general pattern without phi nodes.
The new test case is xfailed, because ForOp hits an unreachable when it meets a non-canonicalized loop. We can implement that functionality later.
> [CIR][ThroughMLIR] Fix ForOp handling

- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/CodeGen/vectype-ext.cpp
- clang/test/CIR/CodeGen/vectype.cpp
- clang/test/CIR/IR/invalid.cir
Backport improvements in ShiftOp for vectors from https://github.com/llvm/llvm-project/pull/141111.
> [CIR] Backport Allow different Int types together in Vec ShiftOp

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/ConstantInitBuilder.h
- clang/lib/CIR/Dialect/IR/CIRAttrs.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRLoopToSCF.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
- Uses `getI<bitwidth>IntegerAttr` builder method instead of explicit attribute and its type creation.
- Adds few helper functions `getAlignmentAttr` to build  alignment representing `mlir::IntegerAttr`.
- Removes duplicit type parameters, that are inferred from `mlir::IntegerAttr`.
> [CIR] Streamline creation of `mlir::IntegerAttr`s using mlir::Builder

- clang/lib/CIR/CodeGen/ConstantInitBuilder.h
The current implementation incorrectly uses `mlir::IntegerAttr::get` with the unsupported type `cir::IntType`, which is not compatible and was never tested. As discussed in PR #1645, this is to be marked as NYI until a proper implementation is provided.
> [CIR] Mark `addInt` as NYI due to incorrect implementation

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/CodeGen/vectype-ext.cpp
Backport the calculation of maskbits in the lowering from `N - 1` to `NextPowerOf2(numElements - 1) - 1`, similar to Clang CG.
Backport from [#141411](https://github.com/llvm/llvm-project/pull/141411)
> [CIR] Backport fixsing ShuffleDynamicOp maskbits logic

- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/CodeGen/throw.cpp
This PR fixes [Issue#1647](https://github.com/llvm/clangir/issues/1647). 
It just takes the implementation from [`emitRethrow`](https://github.com/llvm/clangir/blob/105d898b9898d224f0baca4b161a84bdcf817617/clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp#L2273C1-L2276C77) and extends the same logic to `emitThrow`. 
The only nitpick about the fix is same as before - we have this [redundant ScopeOp](https://github.com/llvm/clangir/blob/105d898b9898d224f0baca4b161a84bdcf817617/clang/lib/CIR/CodeGen/CIRGenItaniumCXXABI.cpp#L2298C1-L2303C37) which acts as a placeholder, so there are some redundant yield blocks in some cases. Aside that, I believe this fix is okay for now. 
I have added the tests from the issue to confirm everything works as intended. 
cc: @mmha, @bcardosolopes.
> [CIR][CodeGen] Insert new blocks after ThrowOp expressions

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/Dialect/Transforms/TargetLowering/ABIInfoImpl.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/var-arg-x86_64.c
LLVM dialect now has ptrmask intrinsic, use it instead of the manual computation
Fix bitwidth of the generated mask in ABIInfoImpl
> [CIR][Lowering] Lower CIR ptrmask to LLVM ptrmask

- clang/include/clang/CIR/LoweringHelpers.h
- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/lib/CIR/Lowering/LoweringHelpers.cpp
- clang/test/CIR/CodeGen/const-complex.cpp
Backport support global initialization for ComplexType from (https://github.com/llvm/llvm-project/pull/141369)
> [CIR] Backport support for global ComplexType init

- clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp
- clang/test/CIR/CodeGen/complex.c
Backport support for Complex value initialization from the empty InitList.
Backported from https://github.com/llvm/llvm-project/pull/143192
> [CIR] Backport Complex init with empty init list

- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/test/CIR/IR/invalid-vector-shuffle-wrong-index.cir
Backport the VecShuffleOp verifier to catch invalid index
Implemented in https://github.com/llvm/llvm-project/pull/143262
> [CIR] Backport Extending VecShuffleOp verifier to catch invalid index

- clang/lib/CIR/CodeGen/CIRGenTypes.cpp
When we process a completed Enum type, we were checking to see if the completed type was in the type cache and clearing the cache if the completed and converted underlying type for the enum doesn't pass an `isInteger(32)` check. Unfortunately, this checks to see if the type is the MLIR builtin 32-bit integer type, whereas it will always be a CIR integer type, so the check always fails.
I don't believe there can ever be a case where the forward declared type for the enum doesn't match the completed type, so we should never need to clear the cache. This change replaces the previous check with an assert that compares the actual completed type to the cached type.
> [CIR] Avoid unnecessary type cache clearing with Enum type completion

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/test/CIR/CodeGen/const-baseclass.cpp
- clang/test/CIR/CodeGen/derived-cast.cpp
- clang/test/CIR/CodeGen/derived-to-base.cpp
- clang/test/CIR/CodeGen/multi-vtable.cpp
- clang/test/CIR/CodeGen/pointer-to-data-member-cast.cpp
- clang/test/CIR/CodeGen/vtable-rtti.cpp
- clang/test/CIR/CodeGen/vtt.cpp
This removes unnecessary parens from the assembly format of BaseClassAddrOp, DerivedClassAddrOp, BaseDataMemberOp, DerivedDataMemberOp, BaseMethodOp, and DerivedMethodOp to bring them into conformance with the CIR ASM Style Guide.
The is no function change beyond the assembly format change.
> [CIR] Remove parens from C++ address-related ops' assembly format

- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRLoopToSCF.cpp
- clang/test/CIR/Lowering/ThroughMLIR/while-with-continue.cpp
As the scf dialect does not support early exits, it might be necessary to change the body of WhileOp to implement the semantics of ContinueOp. I choose to add a guard `if (!cond)` for everything following the `continue`.
> [CIR][ThroughMLIR] Lower ContinueOp nested inside IfOp

- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
- clang/test/CIR/Lowering/ThroughMLIR/call.c
This PR is related to #1685 and adds some basic support for the printf function. 
Limitations:
1. It only works if all variadic params are of basic interger/float type (for more info why memref type operands don't work see #1685)
2. Only works if the format string is definied directly inside the printf function
The downside of this PR is also that the handling this edge case adds significant code bloat and reduces readability for the cir.call op lowering (I tried to insert some meanigful comments to improve the readability), but I think its worth to do this so we have some basic printf support (without adding an extra cir operation) until upstream support for variadic functions is added to the func dialect. Also a few more test (which use such a basic form of printf) in the llvm Single …
> [ThroughMLIR] basic printf support

- clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp
- clang/lib/CIR/CodeGen/TargetInfo.cpp
- clang/lib/CIR/CodeGen/TargetInfo.h
- clang/test/CIR/CodeGen/bitfields.c
- clang/test/CIR/CodeGen/bitfields.cpp
- clang/test/CIR/CodeGen/const-bitfields.c
- clang/test/CIR/CodeGen/dumb-record.cpp
This PR addresses the feedback from https://github.com/llvm/llvm-project/pull/142041#discussion_r2116554849. Our algorithm for accumulating bitfields has diverged from CodeGen since Clang 19.
There is one key difference: in CIR, we use the function `getBitfieldStorageType`, which checks whether the bit width of the current accumulation run is a valid fundamental width (i.e., a power of two: 8, 16, 32, 64). If it is, it returns a CIR type of that size otherwise, it returns an array with the closest alignment.
For example, given the following struct:
```c
struct S {
int a : 4;
int b : 27;
int c : 17;
int d : 2;
int e : 15;
unsigned f;
};
```
The CodeGen output is:
```llvm
%struct.S = type { i64, i16, i32 }
```
Whereas the new CIR algorithm produces:
```mlir
!cir.record<struct "S" …
```
> [CIR] Update Accumulate Bits Algorithm

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIRDialect.td
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenAtomic.cpp
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenCoroutine.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/FlattenCFG.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerTBAAToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerMLIRToLLVM.cpp
- clang/test/CIR/IR/invalid.cir
- Create CIR specific EnumAttr bases and prefix enum attributes with `CIR_` that automatically puts enum to `cir` namespace
- Removes unnecessary enum case definitions
- Unifies naming of enum values to use capitals consistently and make enumerations to start from 0
- Remove now unnecessary printers/parsers that gets to be generated automatically
> [CIR] Clean up enum attributes

- clang/lib/CIR/CodeGen/CIRGenBuiltinX86.cpp
- clang/test/CIR/CodeGen/X86/lzcnt-builtins.c
No test cases provided for `lzcnt_u16` as presented in the OG codegen equivalent: `test/CodeGen/X86/lzcnt-builtins.c`.
related: #1404
> [CIR][CIRGen][Builtin][X86] Lower lzcnt_u16, lzcnt_u32, lzcnt_u64

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtins-elementwise.c
Implement base-2 exponential intrinsic as part of #1192
> [CIR][CIRGen] Support for `__builtin_elementwise_exp2`

- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/test/CIR/CodeGen/AArch64/neon-arith.c
Hi, This is my first here! Tried to mirror some of the patterns already presented in both the codegen lib and its tests
I'm very excited to start contributing and potentially making an impact in this project! feedback is much appreciated.
> [CIR][CIRGen][Builtin][Neon] Lower neon_vaddlv_s8 and neon_vaddlv_u8

- clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp
- clang/test/CIR/CodeGen/agg-init-inherit.cpp
convert from codegen
```c++
assert(!Base.isVirtual() && "should not see vbases here");
auto *BaseRD = Base.getType()->getAsCXXRecordDecl();
Address V = CGF.GetAddressOfDirectBaseInCompleteClass(
Dest.getAddress(), CXXRD, BaseRD,
/*isBaseVirtual*/ false);
AggValueSlot AggSlot = AggValueSlot::forAddr(
V, Qualifiers(),
AggValueSlot::IsDestructed,
AggValueSlot::DoesNotNeedGCBarriers,
AggValueSlot::IsNotAliased,
CGF.getOverlapForBaseInit(CXXRD, BaseRD, Base.isVirtual()));
CGF.EmitAggExpr(InitExprs[curInitIndex++], AggSlot);
if (QualType::DestructionKind dtorKind =
Base.getType().isDestructedType())
CGF.pushDestroyAndDeferDeactivation(dtorKind, V, Base.getType());
```
> [CIR] Support inheritance in `InitListExpr`

- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/test/CIR/CodeGen/complex.c
Update `__real__` operation to use ComplexRealOp and act directly on the complex value.
Ref: https://github.com/llvm/llvm-project/pull/144235#pullrequestreview-2933105012
> [CIR] Use ComplexRealOp for RValue `__real__` operator

- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/test/CIR/CodeGen/complex.c
Update `__imag__` operation to use ComplexRealOp and act directly on the complex value.
Ref: https://github.com/llvm/llvm-project/pull/144235#pullrequestreview-2933105012
> [CIR] Use ComplexRealOp for RValue __imag__ operator

- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/test/CIR/CodeGen/builtin-constant-evaluated.cpp
Backport ChooseExpr for Scalar expr
> [CIR] Backport ChooseExpr for Scalar expr

- clang/lib/CIR/CodeGen/CIRGenBuiltinX86.cpp
- clang/test/CIR/CodeGen/X86/x86_64-xsave.c
Two things:
1. Added some NYI placeholders
2. Tests for i386(x86) are pending as we haven't dealt with that triple yet as compared to CG.
> [CIR][CIRGen][Builtin][X86] Lower xsave related intrinsics

- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRLoopToSCF.cpp
- clang/test/CIR/Lowering/ThroughMLIR/for_with_continue.cpp
We lower `cir::ForOp` into `cir::WhileOp` (rather than `scf::WhileOp`) when it contains break and continue. This is to reuse the rewriting functions already implemented for while loops.
> [CIR][ThroughMLIR] Lower For to While when it contains break/continue

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.h
- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
This will allow to use Attributes and Types together in tablegen without inducing cyclic dependency.
> [CIR] Untie Type and Attribute definitions

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenBuiltinX86.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/test/CIR/CodeGen/X86/avx-builtins.c
- clang/test/CIR/CodeGen/X86/mmx-builtins.c
- clang/test/CIR/CodeGen/X86/sse2-builtins.c
- clang/test/CIR/CodeGen/X86/sse41-builtins.c
Big question mark here:
When lowering target specific vector types: (`__m256i`, `__m128i`, `__m64`), I was hitting an unreachable statement which I removed and were preventing these types from being lowered. Not too familiar with it but it's related to the attribute `"min-legal-vector-width"="N"` which is not implemented for `cir::VectorType` as compared to OG. Is that a blocker for these intrinsics as of now? or is that something we wanna target before we merge x86 vector specific intrinsics?.
> [CIR][CIRGen][Builtin][X86] Lower `vec_ext` related intrinsics

- clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp
- clang/test/CIR/CodeGen/complex.c
Backport ArraySubscript for ComplexType
> [CIR] Backport ArraySubscript for ComplexType

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.h
- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/CodeGen/CIRGenModule.h
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/test/CIR/CodeGen/global-ctor-dtor.cpp
- clang/test/CIR/CodeGen/global-new.cpp
- clang/test/CIR/CodeGen/static.cpp
- clang/test/CIR/CodeGen/tempref.cpp
- This fixes default value to be expected 65535
- Introduces DefaultGlobalCtorDtorPriority constant
- Makes function to use I32Attr for priority instead of unnecessary attribute with reference to function
> [CIR] Fix Global Ctor/Dtor priority attributes

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/test/CIR/CodeGen/bswap.cpp
- clang/test/CIR/CodeGen/builtin-bits.cpp
- clang/test/CIR/CodeGen/ms-intrinsics-other.c
- clang/test/CIR/IR/bit.cir
- clang/test/CIR/IR/invalid.cir
- clang/test/CIR/Lowering/bit.cir
- clang/test/CIR/Lowering/bswap.cir
This patch backports changes made to the bit operations in the upstream PR llvm/llvm-project#148378. Namely, this patch includes the following changes:
- This patch removes the `bit.` prefix in the op mnemonic. The operation names now directly correspond to the builtin function names except for bswap which is represented by `cir.byte_swap` for more clarity.
- Since all bit operations are `SameOperandsAndResultType`, this patch updates their assembly format and avoids spelling out the operand type twice.
> [CIR][NFC] Backport upstream bit operations changes

- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/test/CIR/CodeGen/array-init-destroy.cpp
- clang/test/CIR/CodeGen/array-new-init.cpp
- clang/test/CIR/Lowering/new.cpp
The LoweringPrepare pass was generating the wrong condition for loops when lowering the ArrayCtor op, causing only one element in an array of objects to be constructed. This fixes that problem.
> [CIR] Fix array init loop condition

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenBuilder.cpp
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenExprAgg.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.h
- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
- clang/test/CIR/CallConvLowering/AArch64/aarch64-cc-structs.c
- clang/test/CIR/CodeGen/array.c
- clang/test/CIR/CodeGen/array.cpp
- clang/test/CIR/CodeGen/bitint.cpp
- clang/test/CIR/CodeGen/complex.c
- clang/test/CIR/CodeGen/struct.c
- clang/test/CIR/Lowering/ThroughMLIR/array.c
Currently, getting the pointer to an element of an array requires a pointer decay and a (possible) pointer stride. A similar pattern for records has been eliminated with the `cir.get_member` operation. This PR provides a similar level of abstraction for arrays with the `get_element` operation.
`get_element` replaces the above pattern with a single operation, which takes a pointer to an array and an index, and produces a pointer to the element at that index.
There are many places in CIR analysis and lowering where the `ptr_stride(array_to_ptrdecay(x), i)` pattern is handled as a special case. By subsuming the special case pattern with an explicit operation, we make these analyses and lowering more robust.
Adds the `cir.get_element` operation.
Extends CIRGen to emit `cir.get_element` for …
> [CIR] Add `get_element` operation for computing pointer to array element

- clang/lib/CIR/Dialect/Transforms/CIRCanonicalize.cpp
- clang/test/CIR/CodeGen/OpenCL/array-decay.cl
- clang/test/CIR/CodeGen/array-init.c
- clang/test/CIR/CodeGen/array-init.cpp
- clang/test/CIR/CodeGen/array.cpp
- clang/test/CIR/CodeGen/clear_cache.c
- clang/test/CIR/CodeGen/initlist-ptr-ptr.cpp
- clang/test/CIR/CodeGen/initlist-ptr-unsigned.cpp
- clang/test/CIR/CodeGen/new.cpp
- clang/test/CIR/CodeGen/pointer-arith-ext.c
- clang/test/CIR/CodeGen/pointers.cpp
- clang/test/CIR/CodeGen/std-array.cpp
- clang/test/CIR/Lowering/new.cpp
- clang/test/CIR/Transforms/simpl.cir
Extended the `CIRCanonicalizePass` with new rewrite rules: 
- Rewrite `ptr_stride (cast array_to_ptrdecay %base), %index` to `get_element %base[%index]` 
- Rewrite `ptr_stride (get_element %base[%index]), %stride` to `get_element %base[%index + %stride]` 
- Rewrite `cast array_to_ptrdecay %base, ptr<T>` to `get_element %base[0], ptr<T>` if it is only used by `load %ptr : T`, `store %val : T, %ptr`, or `get_member %ptr[field] : ptr<T> -> U`
Updated CodeGen tests, and extended CIR-to-CIR test.
> [CIR] Extend CIR canonicalize to rewrite `ptr_stride` and `array_to_ptrdecay` to `get_element` when possible

- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/LoweringPrepareX86CXXABI.cpp
- clang/test/CIR/Lowering/var-arg-x86_64.c
`cir::PointerType` was not included in the applicability guard for `cir::VAArg` lowering during `LoweringPrepare`. 
Since we don't have generic LLVM `cir::VAArgOp` (see [more info](https://github.com/llvm/clangir/pull/1088#issuecomment-2465769265)) this causes an NYI error during lowering that doesn't need to happen. 
To fix this I added the missing `cir::PointerType` to the `isa`. 
There is probably a more comprehensive fix to this if someone is interested, this check should be removed and let the (possible) error occur at the actual NYI site.
> [CIR][Lowering] Enabled VAArg lowering for `cir::PointerType`

- clang/include/clang/CIR/Dialect/IR/CIROps.td
- clang/lib/CIR/CodeGen/CIRGenAtomic.cpp
- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/lib/CIR/CodeGen/CIRGenBuiltinAArch64.cpp
- clang/lib/CIR/CodeGen/CIRGenBuiltinX86.cpp
- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/lib/CIR/CodeGen/CIRGenDecl.cpp
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/lib/CIR/CodeGen/CIRGenExprConst.cpp
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/CIRSimplify.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- Replaces  dyn_cast<cir::ConstantOp>(v.getDefiningOp()) and similar with v.getDefiningOp<cir::ConstantOp>()
- Adds `getValueAttr`, `getIntValue` and `getBoolValue` methods to ConstantOp
> [CIR] Simplify ConstantOp accesses and its getDefiningOp

- clang/lib/CIR/CodeGen/Address.h
- clang/lib/CIR/CodeGen/CIRGenDecl.cpp
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenExprScalar.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.cpp
- clang/lib/CIR/CodeGen/CIRGenFunction.h
- clang/lib/CIR/Dialect/IR/CIRDialect.cpp
- clang/lib/CIR/Dialect/Transforms/LibOpt.cpp
- clang/lib/CIR/Dialect/Transforms/LifetimeCheck.cpp
- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/lib/CIR/Dialect/Transforms/TargetLowering/LowerFunction.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRLoopToSCF.cpp
- clang/lib/CIR/Lowering/ThroughMLIR/LowerCIRToMLIR.cpp
This applies similar changes to https://github.com/llvm/llvm-project/pull/150428
> [CIR] Use getDefiningOp<OpTy>() instead of dyn_cast<OpTy>(getDefiningOp()) (NFC)

- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVM.cpp
- clang/test/CIR/Lowering/vec-cmp.cir
(Copied from my question on Discord)
I’ve been working on the vector to bit-mask related intrinsics for X86. I’ve been stuck specifically on `X86::BI__builtin_ia32_cvtb2mask128(_mm256_movepi16_mask`) and its variations with different vector/mask sizes.
In this case, we perform a vector comparison of `vector<16xi16>` and bitcast the resulting `vector<16xi1>` directly into a scalar integer mask (i16). 
I’m successfully able to lower to cir:
```
...
%5 = cir.vec.cmp(lt, %3, %4) : !cir.vector<!s16i x 16>, !cir.vector<!cir.int<u, 1> x 16>
%6 = cir.cast(bitcast, %5 : !cir.vector<!cir.int<u, 1> x 16>), !u16i
...
```
There's an issue arises when lowering this to LLVM, the error message I'm getting is:
```
error: integer width of the output type is smaller or equal to the integer width of the …
```
> [CIR][Lowering] Fix inconditional sign extension on vec.cmp op

- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinX86.cpp
- clang/test/CIR/CodeGen/X86/avx10_2bf16-builtins.c
- clang/test/CIR/CodeGen/X86/avx512bw-builtins.c
- clang/test/CIR/CodeGen/X86/avx512f-builtins.c
- clang/test/CIR/CodeGen/X86/avx512fp16-builtins.c
- clang/test/CIR/CodeGen/X86/avx512vl-builtins.c
- clang/test/CIR/CodeGen/X86/avx512vlbw-buiiltins.c
For these intrinsics there only seems to be one function where the IR emmited seems to diverge:
for `_mm_load_sbh` loads a single 16-bit bfloat (__bf16) value from memory into the lowest element of a 128-bit bfloat vector (__m128bh), leaving the remaining lanes unchanged or filled with a passthrough value. It is implemented using a masked load with only the first lane enabled.
[source for intrinsics with similar behaviour](https://gist.github.com/leopck/86799fee6ceb9649d0ebe32c1c6e5b85)
In the CIR lowering of `_mm_load_sbh`, we are currently emitting the mask of intrinsic (`llvm.masked.load`) operand as an explicit constant vector:
``` llvm
<8 x i1> <true, false, false, false, false, false, false, false>
```
whereas OG lowers:
```llvm
<8 x i1> bitcast (<1 x i8> splat (i8 1) to <8 x i1>) …
```
> [CIR][CIRGen][Builtin][X86] Lower AVX masked load intrinsics

- clang/lib/CIR/Dialect/Transforms/TargetLowering/Targets/LoweringPrepareX86CXXABI.cpp
- clang/test/CIR/Lowering/var-arg-x86_64.c
The `cir.va_arg` lowering may introduce an if-else control flow. 
This breaks the verifier for control flow operations, e.g., `cir.for`, where there can be only one block inside of the `cond` and `step` regions. 
This PR wraps the lowered code in a `cir.scope` (only if it will lower to the if-else control flow). A
dded a test for `va_arg` inside for loop condition, the basic pattern is: `for (; va_arg(...););`
> [CIR][LoweringPrepare] Wrap `cir.va_arg` lowered code in a `cir.scope`

- clang/lib/Driver/ToolChains/Clang.cpp
- clang/test/CIR/Driver/idiom-recognizer.cpp
- clang/test/CIR/Driver/lib-opt.cpp
We were missing argument handling for `-fclangir-idiom-recognizer` on its own, and were not propagating `-fclangir-lib-opt` for the clang toolchain.
> [CIR] Added missing argument handling to `clang` toolchain

- clang/include/clang/CIR/Dialect/IR/CIROps.td
This PR is inspired by the discussion in https://github.com/llvm/clangir/pull/1745#discussion_r2246273043.
When changing the type of
```mlir
IndexAttr:$index,
I64Attr:$index
```
in `GetMemberOp`, the `getIndex` method becomes auto-generated.
This allows us to remove the custom builder previously defined for this operation.
> [CIR][NFC] Change GetMemberOp index type

- clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp
- clang/test/CIR/CodeGen/complex.cpp
Backport AbstractConditionalOperator for ComplexType from the upstream
Fix: #1788
> [CIR] Backport AbstractConditionalOperator for ComplexType

- clang/lib/CIR/Dialect/Transforms/LoweringPrepare.cpp
- clang/test/CIR/CodeGen/array-init-destroy.cpp
- clang/test/CIR/CodeGen/array-new-init.cpp
Previously, when an array of destructible object went out of scope, the object destructors were called in the same order that they were constructed. This is incorrect. The objects should be destructed in reverse order. This change fixes that.
This fixes https://github.com/llvm/clangir/issues/1759
> [CIR] Backport a fix for array element destruction order.

- clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp
- clang/test/CIR/CodeGen/complex.cpp
Backport UnaryDeref support for ComplexType from the upstream
> [CIR] Backport UnaryDeref support for ComplexType

- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRGenExprComplex.cpp
- clang/test/CIR/CodeGen/complex.cpp
Backporting MemberExpr support for ComplexType from the upstream
> [CIR] Backport MemberExpr support for ComplexType

- clang/include/clang/CIR/Dialect/IR/CIRDataLayout.h
- clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp
- clang/test/CIR/CodeGen/mms-bitfields.c
This PR adds support for the **discrete bit-field layout**, which is used in the Microsoft bit-field ABI.
Since ClangIR does not currently support the Microsoft ABI, this uses the compiler flag 
```bash
-mms-bitfields          Set the default structure layout to be compatible with the Microsoft compiler standard
```
Fixes https://github.com/llvm/clangir/issues/1798
> [CIR] Add support for discrete bit-field ABI

- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenExpr.cpp
- clang/lib/CIR/CodeGen/CIRRecordLayoutBuilder.cpp
- clang/test/CIR/CodeGen/aapcs-volatile-bitfields.c
This PR backports support for volatile bit-fields in AAPCS.  
The corresponding upstream PRs are:  
- https://github.com/llvm/llvm-project/pull/151252
- https://github.com/llvm/llvm-project/pull/151875
> [CIR] Backport volatile bit-fields

- clang/include/clang/CIR/Dialect/IR/CIRAttrs.td
- clang/lib/CIR/CodeGen/CIRGenModule.cpp
- clang/lib/CIR/Lowering/DirectToLLVM/LowerToLLVMIR.cpp
- clang/test/CIR/CodeGen/hot-attr.cpp
Implemented missing feature for issue #1793. Also implemented LLVM lowering for the hot attribute, and added a new test case.
> [CIR][CodeGen] Attach hot attribute to CIR function

- clang/lib/CIR/CodeGen/CIRGenBuiltin.cpp
- clang/test/CIR/CodeGen/builtin-types.c
This patch adds support for IITDescriptor::Vector type and adds
NYI for the others.
> [CIR] Add IITDescriptor type cases

- clang/lib/CIR/CodeGen/CIRGenClass.cpp
- clang/test/CIR/CodeGen/delegating-ctor.cpp
This implements getting the VTT argument for a delegating constructor and enables the corresponding test in delegating-ctor.cpp.
> [CIR] Add support for delegating ctor with VTT

- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinX86.cpp
- clang/test/CIR/CodeGen/AArch64/neon-misc.c
- clang/test/CIR/CodeGen/vectype-ext.cpp
First noted at: #1829
Also:
Adjusted test cases affected by this change.
> [CIR] Use poison as second vector operand in unary shuffles.

- clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuilder.h
- clang/lib/CIR/CodeGen/CIRGenBuiltinX86.cpp
- clang/test/CIR/CodeGen/X86/avx512bw-builtins.c
- clang/test/CIR/CodeGen/X86/avx512dq-builtins.c
- clang/test/CIR/CodeGen/X86/avx512vlbw-buiiltins.c
- clang/test/CIR/CodeGen/X86/avx512vldq-builtins.c
Three things:
- Corrected comments to `getZeroInitAttr` as [we return more than only integrals in that function](https://github.com/llvm/clangir/blob/2ea4005fa0aa291295b19c200860b5edf9b864b3/clang/include/clang/CIR/Dialect/Builder/CIRBaseBuilder.h#L133).
- Given that `emitX86MaskedCompare` and `emitX86MaskedCompareResult` helpers are pretty large, Added NYI statements on paths not related to the current set of intrinsics so review is specific to the ones encoded.
- Added test comments related to the behavior observed coming from the canonicalizer on: #1770
> [CIR][CIRGen][Builtin][X86] Lower cvt*2mask intrinsics

- clang/lib/CIR/CodeGen/CIRGenExprCXX.cpp
- clang/test/CIR/CodeGen/new.cpp
Backport CXX new for ComplexType with init from the upstream
> [CIR] Backport CXX new for ComplexType with init
